export default [
  { "name": "IOTA", "symbols": ["IOT", "IOTA", "MIOTA"] },
  { "name": "Bitcoin", "symbols": ["BTC"] },
  { "name": "Ethereum", "symbols": ["ETH"] },
  { "name": "Gifto", "symbols": ["GTO"] },
  { "name": "Recently5NEO", "symbols": ["NEO"] },
  { "name": "Ripple", "symbols": ["XRP"] },
  { "name": "TRON", "symbols": ["TRX"] },
  { "name": "ICON", "symbols": ["ICX"] },
  { "name": "NEO", "symbols": ["NEO"] },
  { "name": "Binance Coin", "symbols": ["BNB"] },
  { "name": "Po.et", "symbols": ["POE"] },
  { "name": "Ethereum Classic", "symbols": ["ETC"] },
  { "name": "Nano", "symbols": ["NANO", "XRB"] },
  { "name": "VeChain", "symbols": ["VEN", "VET"] },
  { "name": "Populous", "symbols": ["PPT"] },
  { "name": "Hshare", "symbols": ["HSR"] },
  { "name": "Bluzelle", "symbols": ["BLZ"] },
  { "name": "Litecoin", "symbols": ["LTC"] },
  { "name": "Cardano", "symbols": ["ADA"] },
  { "name": "EOS", "symbols": ["EOS"] },
  { "name": "NAV Coin", "symbols": ["NAV"] },
  { "name": "Bitcoin Cash", "symbols": ["BCC", "BCH"] },
  { "name": "Agrello", "symbols": ["DLT"] },
  { "name": "Enigma", "symbols": ["ENG", "XNG"] },
  { "name": "Stellar", "symbols": ["XLM", "STR"] },
  { "name": "Lisk", "symbols": ["LSK"] },
  { "name": "INS Ecosystem", "symbols": ["INS"] },
  { "name": "Metal", "symbols": ["MTL"] },
  { "name": "Bread", "symbols": ["BRD"] },
  { "name": "IOStoken", "symbols": ["IOST"] },
  { "name": "GXShares", "symbols": ["GXS"] },
  { "name": "AdEx", "symbols": ["ADX"] },
  { "name": "Decentraland", "symbols": ["MANA", "MNA"] },
  { "name": "Kyber Network", "symbols": ["KNC"] },
  { "name": "Cindicator", "symbols": ["CND"] },
  { "name": "Viberate", "symbols": ["VIB"] },
  { "name": "Verge", "symbols": ["XVG"] },
  { "name": "Walton", "symbols": ["WTC", "WALTON"] },
  { "name": "FunFair", "symbols": ["FUN"] },
  { "name": "OmiseGO", "symbols": ["OMG"] },
  { "name": "Zcash", "symbols": ["ZEC"] },
  { "name": "Ambrosus", "symbols": ["AMB"] },
  { "name": "Qtum", "symbols": ["QTUM"] },
  { "name": "DigixDAO", "symbols": ["DGD"] },
  { "name": "CoinDash", "symbols": ["CDT"] },
  { "name": "Aion", "symbols": ["AION"] },
  { "name": "Substratum", "symbols": ["SUB"] },
  { "name": "aelf", "symbols": ["ELF"] },
  { "name": "VIBE", "symbols": ["VIBE"] },
  { "name": "Monero", "symbols": ["XMR"] },
  { "name": "Nuls", "symbols": ["NULS"] },
  { "name": "Neblio", "symbols": ["NEBL"] },
  { "name": "Stratis", "symbols": ["STRAT"] },
  { "name": "Quantstamp", "symbols": ["QSP"] },
  { "name": "ChainLink", "symbols": ["LINK"] },
  { "name": "ETHLend", "symbols": ["LEND"] },
  { "name": "Gas", "symbols": ["GAS"] },
  { "name": "BitShares", "symbols": ["BTS"] },
  { "name": "YOYOW", "symbols": ["YOYO", "YYW", "YOYOW"] },
  { "name": "Centra", "symbols": ["CTR"] },
  { "name": "Bitcoin Gold", "symbols": ["BTG"] },
  { "name": "ChatCoin", "symbols": ["CHAT"] },
  { "name": "AppCoins", "symbols": ["APPC"] },
  { "name": "Recently990x", "symbols": ["ZRX"] },
  { "name": "Dash", "symbols": ["DASH", "DSH"] },
  { "name": "Everex", "symbols": ["EVX"] },
  { "name": "Bitcoin Diamond", "symbols": ["BCD"] },
  { "name": "Triggers", "symbols": ["TRIG"] },
  { "name": "Power Ledger", "symbols": ["POWR"] },
  { "name": "SALT", "symbols": ["SALT"] },
  { "name": "Time New Bank", "symbols": ["TNB"] },
  { "name": "Request Network", "symbols": ["REQ"] },
  { "name": "Tierion", "symbols": ["TNT"] },
  { "name": "PIVX", "symbols": ["PIVX"] },
  { "name": "Ripio Credit Network", "symbols": ["RCN"] },
  { "name": "Ethos", "symbols": ["BQX", "ETHOS"] },
  { "name": "Monaco", "symbols": ["MCO"] },
  { "name": "Aeternity", "symbols": ["AE"] },
  { "name": "Enjin Coin", "symbols": ["ENJ"] },
  { "name": "WaBi", "symbols": ["WABI"] },
  { "name": "ZCoin", "symbols": ["XZC"] },
  { "name": "Genesis Vision", "symbols": ["GVT"] },
  { "name": "AirSwap", "symbols": ["AST"] },
  { "name": "CyberMiles", "symbols": ["CMT"] },
  { "name": "Recently1340x", "symbols": ["ZRX"] },
  { "name": "Simple Token", "symbols": ["OST"] },
  { "name": "Status", "symbols": ["SNT"] },
  { "name": "Waves", "symbols": ["WAVES"] },
  { "name": "district0x", "symbols": ["DNT"] },
  { "name": "Loopring", "symbols": ["LRC"] },
  { "name": "Aeron", "symbols": ["ARN"] },
  { "name": "Steem", "symbols": ["STEEM"] },
  { "name": "Lunyr", "symbols": ["LUN", "LUNYR"] },
  { "name": "Komodo", "symbols": ["KMD"] },
  { "name": "Ark", "symbols": ["ARK"] },
  { "name": "Basic Attention Token", "symbols": ["BAT"] },
  { "name": "SingularDTV", "symbols": ["SNGLS", "SNG"] },
  { "name": "BlockMason Credit Protocol", "symbols": ["BCPT"] },
  { "name": "SONM", "symbols": ["SNM"] },
  { "name": "Modum", "symbols": ["MOD"] },
  { "name": "Monetha", "symbols": ["MTH"] },
  { "name": "Etherparty", "symbols": ["FUEL"] },
  { "name": "Eidoo", "symbols": ["EDO"] },
  { "name": "Wings", "symbols": ["WINGS"] },
  { "name": "iExec RLC", "symbols": ["RLC"] },
  { "name": "Raiden Network Token", "symbols": ["RDN"] },
  { "name": "Storj", "symbols": ["STORJ"] },
  { "name": "Bancor", "symbols": ["BNT"] },
  { "name": "Moeda Loyalty Points", "symbols": ["MDA"] },
  { "name": "OAX", "symbols": ["OAX"] },
  { "name": "Viacoin", "symbols": ["VIA"] },
  { "name": "Iconomi", "symbols": ["ICN"] },
  { "name": "Bibox Token", "symbols": ["BIX"] },
  { "name": "Jibrel Network", "symbols": ["JNT"] },
  { "name": "Spectre.ai Utility Token", "symbols": ["SXUT"] },
  { "name": "Bytom", "symbols": ["BTM"] },
  { "name": "High Performance Blockchain", "symbols": ["HPB"] },
  { "name": "IoT Chain", "symbols": ["ITC"] },
  { "name": "CRYPTO20", "symbols": ["C20"] },
  { "name": "Trinity Network Credit", "symbols": ["TNC"] },
  { "name": "Genaro Network", "symbols": ["GNX"] },
  { "name": "Change", "symbols": ["CAG"] },
  { "name": "Bloom", "symbols": ["BLT"] },
  { "name": " ", "symbols": ["ELF", "MTL", "WABI"] },
  { "name": "Maker", "symbols": ["MKR"] },
  { "name": "Olympus Labs", "symbols": ["MOT"] },
  { "name": "Snovio", "symbols": ["SNOV"] },
  { "name": "WAX", "symbols": ["WAX"] },
  { "name": "AI Doctor", "symbols": ["AIDOC"] },
  { "name": "Game.com", "symbols": ["GTC"] },
  { "name": "ProChain", "symbols": ["PRA"] },
  { "name": "AWARE", "symbols": ["AWR"] },
  { "name": "Bottos", "symbols": ["BTO"] },
  { "name": "BitClave", "symbols": ["CAT"] },
  { "name": "MicroMoney", "symbols": ["AMM"] },
  { "name": "DATA", "symbols": ["DTA"] },
  { "name": "Show", "symbols": ["SHOW"] },
  { "name": "Super Bitcoin", "symbols": ["SBTC"] },
  { "name": "B2B", "symbols": ["B2B"] },
  { "name": "Russian Miner Coin", "symbols": ["RMC"] },
  { "name": "Golos Gold", "symbols": ["GBG"] },
  { "name": "Revain", "symbols": ["R"] },
  { "name": "Everus", "symbols": ["EVR"] },
  { "name": "OceanChain", "symbols": ["OC"] },
  { "name": "UG Token", "symbols": ["UGT"] },
  { "name": "CFun", "symbols": ["CFUN"] },
  { "name": "ACChain", "symbols": ["ACC"] },
  { "name": "ATN", "symbols": ["ATN"] },
  { "name": "SpaceChain", "symbols": ["SPC"] },
  { "name": "HalalChain", "symbols": ["HLC"] },
  { "name": "Profile Utility Token", "symbols": ["PUT"] },
  { "name": "Ink", "symbols": ["INK"] },
  { "name": "Energo", "symbols": ["TSL"] },
  { "name": "Internet Node Token", "symbols": ["INT"] },
  { "name": "SIGMAcoin", "symbols": ["SIGMA"] },
  { "name": "Qbao", "symbols": ["QBT"] },
  { "name": "DeepBrain Chain", "symbols": ["DBC"] },
  { "name": "Bodhi", "symbols": ["BOT"] },
  { "name": "Achain", "symbols": ["ACT"] },
  { "name": "Nebulas", "symbols": ["NAS"] },
  { "name": "GameCredits", "symbols": ["GAME"] },
  { "name": "iQuant", "symbols": ["IQT"] },
  { "name": "BITFID", "symbols": ["FID"] },
  { "name": "MarteXcoin", "symbols": ["MXT"] },
  { "name": "Crown", "symbols": ["CRW"] },
  { "name": "United Bitcoin", "symbols": ["UBTC"] },
  { "name": "Medicalchain", "symbols": ["MTN"] },
  { "name": "SophiaTX", "symbols": ["SPHTX"] },
  { "name": "QASH", "symbols": ["QASH", "QSH"] },
  { "name": "Vezt", "symbols": ["VZT"] },
  { "name": "onG.social", "symbols": ["ONG"] },
  { "name": "Gatcoin", "symbols": ["GAT"] },
  { "name": "NEM", "symbols": ["XEM"] },
  { "name": "Indorse Token", "symbols": ["IND"] },
  { "name": "FidentiaX", "symbols": ["FDX"] },
  { "name": "CanYaCoin", "symbols": ["CAN"] },
  { "name": "Blackmoon", "symbols": ["BMC"] },
  { "name": "Dent", "symbols": ["DENT"] },
  { "name": "Stox", "symbols": ["STX"] },
  { "name": "iXledger", "symbols": ["IXT"] },
  { "name": "Augur", "symbols": ["REP"] },
  { "name": "Factom", "symbols": ["FCT"] },
  { "name": "$0$0.9597460.00%Recently", "symbols": ["STORJ"] },
  { "name": "Tether", "symbols": ["USDT"] },
  { "name": "$714,873 $54.070.20%Recently", "symbols": ["REP"] },
  { "name": "Dogecoin", "symbols": ["DOGE"] },
  { "name": "Gnosis", "symbols": ["GNO"] },
  { "name": "Melon", "symbols": ["MLN"] },
  { "name": "NuBits", "symbols": ["NBT", "USNBT"] },
  { "name": "Recently6NEO", "symbols": ["NEO"] },
  { "name": "Rise", "symbols": ["RISE"] },
  { "name": "Siacoin", "symbols": ["SC"] },
  { "name": "ZClassic", "symbols": ["ZCL"] },
  { "name": "Humaniq", "symbols": ["HMQ"] },
  { "name": "ION", "symbols": ["ION"] },
  { "name": "DigiByte", "symbols": ["DGB"] },
  { "name": "Ignis", "symbols": ["IGNIS"] },
  { "name": "Swarm City", "symbols": ["SWT"] },
  { "name": "TenX", "symbols": ["PAY"] },
  { "name": "FirstBlood", "symbols": ["1ST", "FirstBlood"] },
  { "name": "DigitalNote", "symbols": ["XDN"] },
  { "name": "Einsteinium", "symbols": ["EMC2"] },
  { "name": "ReddCoin", "symbols": ["RDD"] },
  { "name": "MonaCoin", "symbols": ["MONA"] },
  { "name": "Vertcoin", "symbols": ["VTC"] },
  { "name": "Numeraire", "symbols": ["NMR"] },
  { "name": "ExclusiveCoin", "symbols": ["EXCL"] },
  { "name": "Syscoin", "symbols": ["SYS"] },
  { "name": "Unikoin Gold", "symbols": ["UKG"] },
  { "name": "Voxels", "symbols": ["VOX"] },
  { "name": "Nexus", "symbols": ["NXS"] },
  { "name": "Steem Dollars", "symbols": ["SBD"] },
  { "name": "Ardor", "symbols": ["ARDR"] },
  { "name": "adToken", "symbols": ["ADT"] },
  { "name": "Nxt", "symbols": ["NXT"] },
  { "name": "MaidSafeCoin", "symbols": ["MAID"] },
  { "name": "Sphere", "symbols": ["SPHR"] },
  { "name": "Shift", "symbols": ["SHIFT"] },
  { "name": "Golem", "symbols": ["GNT"] },
  { "name": "ZenCash", "symbols": ["ZEN"] },
  { "name": "Synereo", "symbols": ["AMP"] },
  { "name": "Decred", "symbols": ["DCR"] },
  { "name": "Matchpool", "symbols": ["GUP"] },
  { "name": "Blocknet", "symbols": ["BLOCK"] },
  { "name": "Quantum Resistant Ledger", "symbols": ["QRL"] },
  { "name": "Byteball Bytes", "symbols": ["GBYTE"] },
  { "name": "Civic", "symbols": ["CVC"] },
  { "name": "Syndicate", "symbols": ["SYNX"] },
  { "name": "VeriCoin", "symbols": ["VRC"] },
  { "name": "Burst", "symbols": ["BURST"] },
  { "name": "Expanse", "symbols": ["EXP"] },
  { "name": "BitBay", "symbols": ["BAY"] },
  { "name": "Edgeless", "symbols": ["EDG"] },
  { "name": "BlackCoin", "symbols": ["BLK"] },
  { "name": "HempCoin", "symbols": ["THC", "HMP"] },
  { "name": "LBRY Credits", "symbols": ["LBC"] },
  { "name": "Counterparty", "symbols": ["XCP"] },
  { "name": "Agoras Tokens", "symbols": ["AGRS"] },
  { "name": "OKCash", "symbols": ["OK"] },
  { "name": "Emercoin", "symbols": ["EMC"] },
  { "name": "Ubiq", "symbols": ["UBQ"] },
  { "name": "MonetaryUnit", "symbols": ["MUE"] },
  { "name": "Sequence", "symbols": ["SEQ"] },
  { "name": "Particl", "symbols": ["PART"] },
  { "name": "UnbreakableCoin", "symbols": ["UNB"] },
  { "name": "Dynamic", "symbols": ["DYN"] },
  { "name": "Groestlcoin", "symbols": ["GRS"] },
  { "name": "FoldingCoin", "symbols": ["FLDC"] },
  { "name": "PinkCoin", "symbols": ["PINK"] },
  { "name": "TransferCoin", "symbols": ["TX"] },
  { "name": "Aragon", "symbols": ["ANT"] },
  { "name": "PotCoin", "symbols": ["POT"] },
  { "name": "Omni", "symbols": ["OMNI"] },
  { "name": "DECENT", "symbols": ["DCT"] },
  { "name": "Blocktix", "symbols": ["TIX"] },
  { "name": "Internet of People", "symbols": ["IOP"] },
  { "name": "WeTrust", "symbols": ["TRST"] },
  { "name": "Circuits of Value", "symbols": ["COVAL"] },
  { "name": "Elastic", "symbols": ["XEL"] },
  { "name": "SaluS", "symbols": ["SLS"] },
  { "name": "Patientory", "symbols": ["PTOY"] },
  { "name": "Mercury", "symbols": ["MER"] },
  { "name": "Pesetacoin", "symbols": ["PTC"] },
  { "name": "ClubCoin", "symbols": ["CLUB"] },
  { "name": "eBoost", "symbols": ["EBST"] },
  { "name": "DopeCoin", "symbols": ["DOPE"] },
  { "name": "Cofound.it", "symbols": ["CFI"] },
  { "name": "Feathercoin", "symbols": ["FTC"] },
  { "name": "Golos", "symbols": ["GOLOS"] },
  { "name": "Musicoin", "symbols": ["MUSIC"] },
  { "name": "CloakCoin", "symbols": ["CLOAK"] },
  { "name": "Capricoin", "symbols": ["CPC"] },
  { "name": "BitSend", "symbols": ["BSD"] },
  { "name": "LoMoCoin", "symbols": ["LMC"] },
  { "name": "Gulden", "symbols": ["NLG"] },
  { "name": "WhiteCoin", "symbols": ["XWC"] },
  { "name": "Bean Cash", "symbols": ["BITB"] },
  { "name": "Recently", "symbols": ["MEME"] },
  { "name": "Global Currency Reserve", "symbols": ["GCR"] },
  { "name": "Auroracoin", "symbols": ["AUR"] },
  { "name": "I/O", "symbols": ["IOC"] },
  { "name": "Myriad", "symbols": ["XMY"] },
  { "name": "ArtByte", "symbols": ["ABY"] },
  { "name": "CannabisCoin", "symbols": ["CANN"] },
  { "name": "Magi", "symbols": ["XMG"] },
  { "name": "NeosCoin", "symbols": ["NEOS"] },
  { "name": "Peercoin", "symbols": ["PPC"] },
  { "name": "Aeon", "symbols": ["AEON"] },
  { "name": "Incent", "symbols": ["INCNT"] },
  { "name": "SpreadCoin", "symbols": ["SPR"] },
  { "name": "SIBCoin", "symbols": ["SIB"] },
  { "name": "Radium", "symbols": ["RADS"] },
  { "name": "GridCoin", "symbols": ["GRC"] },
  { "name": "Creditbit", "symbols": ["CRB", "CRBIT"] },
  { "name": "Kore", "symbols": ["KORE"] },
  { "name": "Bytecent", "symbols": ["BYC"] },
  { "name": "VeriumReserve", "symbols": ["VRM"] },
  { "name": "e-Gulden", "symbols": ["EFL"] },
  { "name": "Bitcrystals", "symbols": ["BCY"] },
  { "name": "Startcoin", "symbols": ["START"] },
  { "name": "Qwark", "symbols": ["QWARK"] },
  { "name": "SolarCoin", "symbols": ["SLR"] },
  { "name": "Vcash", "symbols": ["XVC"] },
  { "name": "Stealthcoin", "symbols": ["XST"] },
  { "name": "ParkByte", "symbols": ["PKB"] },
  { "name": "Project Decorum", "symbols": ["PDC"] },
  { "name": "vTorrent", "symbols": ["VTR"] },
  { "name": "Nexium", "symbols": ["NXC"] },
  { "name": "EuropeCoin", "symbols": ["ERC"] },
  { "name": "Legends Room", "symbols": ["LGD"] },
  { "name": "FairCoin", "symbols": ["FAIR"] },
  { "name": "Databits", "symbols": ["DTB"] },
  { "name": "FlorinCoin", "symbols": ["FLO"] },
  { "name": "Clams", "symbols": ["CLAM"] },
  { "name": "GIVE", "symbols": ["2GIVE"] },
  { "name": "Synergy", "symbols": ["SNRG"] },
  { "name": "Influxcoin", "symbols": ["INFX"] },
  { "name": "Tokes", "symbols": ["TKS"] },
  { "name": "Energycoin", "symbols": ["ENRG"] },
  { "name": "Diamond", "symbols": ["DMD"] },
  { "name": "GoldCoin", "symbols": ["GLD"] },
  { "name": "Breakout Stake", "symbols": ["BRX"] },
  { "name": "Breakout", "symbols": ["BRK"] },
  { "name": "Blitzcash", "symbols": ["BLITZ"] },
  { "name": "EverGreenCoin", "symbols": ["EGC"] },
  { "name": "Rubycoin", "symbols": ["RBY"] },
  { "name": "Curecoin", "symbols": ["CURE"] },
  { "name": "Gambit", "symbols": ["GAM"] },
  { "name": "TrustPlus", "symbols": ["TRUST"] },
  { "name": "Electroneum", "symbols": ["ETN"] },
  { "name": "Ormeus Coin", "symbols": ["ORME"] },
  { "name": "Cream", "symbols": ["CRM"] },
  { "name": "LUXCoin", "symbols": ["LUX"] },
  { "name": "Bitcore", "symbols": ["BTX"] },
  { "name": "GoByte", "symbols": ["GBX"] },
  { "name": "Oyster", "symbols": ["PRL"] },
  { "name": "WINCOIN", "symbols": ["WC"] },
  { "name": "GrandCoin", "symbols": ["GDC"] },
  { "name": "CryptopiaFeeShares", "symbols": ["CEFS"] },
  { "name": "XTRABYTES", "symbols": ["XBY"] },
  { "name": "Voise", "symbols": ["VOISE"] },
  { "name": "Numus", "symbols": ["NMS"] },
  { "name": "Linda", "symbols": ["LINDA"] },
  { "name": "Pillar", "symbols": ["PLR"] },
  { "name": "Cappasity", "symbols": ["CAPP"] },
  { "name": "Pirl", "symbols": ["PIRL"] },
  { "name": "CrowdCoin", "symbols": ["CRC"] },
  { "name": "Divi", "symbols": ["DIVX"] },
  { "name": "Phore", "symbols": ["PHR"] },
  { "name": "Dentacoin", "symbols": ["DCN"] },
  { "name": "SagaCoin", "symbols": ["SAGA"] },
  { "name": "HomeBlockCoin", "symbols": ["HBC"] },
  { "name": "PoSW Coin", "symbols": ["POSW"] },
  { "name": "Mintcoin", "symbols": ["MINT"] },
  { "name": "Skycoin", "symbols": ["SKY"] },
  { "name": "ClearPoll", "symbols": ["POLL"] },
  { "name": "Bulwark", "symbols": ["BWK"] },
  { "name": "BlockCAT", "symbols": ["BKCAT"] },
  { "name": "Hush", "symbols": ["HUSH"] },
  { "name": "StrikeBitClub", "symbols": ["SBC"] },
  { "name": "AdShares", "symbols": ["ADST"] },
  { "name": "Pioneer Coin", "symbols": ["PCOIN"] },
  { "name": "OP Coin", "symbols": ["OPC"] },
  { "name": "Innova", "symbols": ["INN"] },
  { "name": "Zoin", "symbols": ["ZOI"] },
  { "name": "Flash", "symbols": ["FLASH"] },
  { "name": "DubaiCoin", "symbols": ["DBIX"] },
  { "name": "Sumokoin", "symbols": ["SUMO"] },
  { "name": "EncrypGen", "symbols": ["DNA"] },
  { "name": "DeepOnion", "symbols": ["ONION"] },
  { "name": "Spectrecoin", "symbols": ["XSPEC"] },
  { "name": "SpankChain", "symbols": ["SPANK", "SPK"] },
  { "name": "Tokugawa", "symbols": ["TOK"] },
  { "name": "TerraNova", "symbols": ["TER"] },
  { "name": "Obsidian", "symbols": ["ODN"] },
  { "name": "Mothership", "symbols": ["MSP"] },
  { "name": "Denarius", "symbols": ["DNR"] },
  { "name": "Monkey Project", "symbols": ["MONK"] },
  { "name": "Photon", "symbols": ["PHO"] },
  { "name": "CampusCoin", "symbols": ["CMPCO"] },
  { "name": "DecentBet", "symbols": ["DBET"] },
  { "name": "ChainCoin", "symbols": ["CHC"] },
  { "name": "LeviarCoin", "symbols": ["XLC"] },
  { "name": "ProCurrency", "symbols": ["PROC"] },
  { "name": "Solarflarecoin", "symbols": ["SFC"] },
  { "name": "MyWish", "symbols": ["WISH"] },
  { "name": "Social Send", "symbols": ["SEND"] },
  { "name": "BestChain", "symbols": ["BEST"] },
  { "name": "Unobtanium", "symbols": ["UNO"] },
  { "name": "Monoeci", "symbols": ["XMCC"] },
  { "name": "Zap", "symbols": ["ZAP"] },
  { "name": "Interstellar Holdings", "symbols": ["HOLD"] },
  { "name": "ALIS", "symbols": ["ALIS"] },
  { "name": "Zero", "symbols": ["ZER"] },
  { "name": "Unitus", "symbols": ["UIS"] },
  { "name": "VIVO", "symbols": ["VIVO"] },
  { "name": "ToaCoin", "symbols": ["TOA"] },
  { "name": "Pascal Lite", "symbols": ["PASL"] },
  { "name": "WeAreSatoshi", "symbols": ["WSX"] },
  { "name": "Dotcoin", "symbols": ["DOT"] },
  { "name": "Bitdeal", "symbols": ["BDL"] },
  { "name": "DCORP", "symbols": ["DRP"] },
  { "name": "DRP Utility", "symbols": ["DRPU"] },
  { "name": "MyBit Token", "symbols": ["MYB"] },
  { "name": "InvestFeed", "symbols": ["IFT"] },
  { "name": "Bonpay", "symbols": ["BON", "BONPAY"] },
  { "name": "MAZA", "symbols": ["MZC"] },
  { "name": "Universal Currency", "symbols": ["UNIT"] },
  { "name": "PACcoin", "symbols": ["PAC"] },
  { "name": "Argus", "symbols": ["ARGUS"] },
  { "name": "Decision Token", "symbols": ["HST"] },
  { "name": "Rupee", "symbols": ["RUP"] },
  { "name": "MustangCoin", "symbols": ["MST"] },
  { "name": "Skeincoin", "symbols": ["SKC"] },
  { "name": "NoLimitCoin", "symbols": ["NLC2"] },
  { "name": "Ellaism", "symbols": ["ELLA"] },
  { "name": "Mineum", "symbols": ["MNM"] },
  { "name": "Namecoin", "symbols": ["NMC"] },
  { "name": "Embers", "symbols": ["MBRS"] },
  { "name": "Linx", "symbols": ["LINX"] },
  { "name": "Harvest Masternode Coin", "symbols": ["HC"] },
  { "name": "Unify", "symbols": ["UNIFY"] },
  { "name": "Publica", "symbols": ["PBL"] },
  { "name": "Neutron", "symbols": ["NTRN"] },
  { "name": "Upfiring", "symbols": ["UFR"] },
  { "name": "Comet", "symbols": ["CMT"] },
  { "name": "AsiaCoin", "symbols": ["AC"] },
  { "name": "Pura", "symbols": ["PURA"] },
  { "name": "CoinonatX", "symbols": ["XCXT"] },
  { "name": "Steneum Coin", "symbols": ["STN"] },
  { "name": "Bitcloud", "symbols": ["BTDX"] },
  { "name": "TrezarCoin", "symbols": ["TZC"] },
  { "name": "Growers International", "symbols": ["GRWI"] },
  { "name": "Atomic Coin", "symbols": ["ATOM"] },
  { "name": "DigitalPrice", "symbols": ["DP"] },
  { "name": "Copico", "symbols": ["XCPO"] },
  { "name": "Wild Crypto", "symbols": ["WILD"] },
  { "name": "EquiTrader", "symbols": ["EQT"] },
  { "name": "Cannation", "symbols": ["CNNC"] },
  { "name": "Royal Kingdom Coin", "symbols": ["RKC"] },
  { "name": "Kubera Coin", "symbols": ["KBR"] },
  { "name": "TeslaCoin", "symbols": ["TES"] },
  { "name": "Social", "symbols": ["SCL"] },
  { "name": "Pandacoin", "symbols": ["PND"] },
  { "name": "Elite", "symbols": ["1337"] },
  { "name": "Ethereum Dark", "symbols": ["ETHD"] },
  { "name": "SwagBucks", "symbols": ["BUCKS"] },
  { "name": "AdCoin", "symbols": ["ACC"] },
  { "name": "Cryptojacks", "symbols": ["CJ"] },
  { "name": "TajCoin", "symbols": ["TAJ"] },
  { "name": "Rimbit", "symbols": ["RBT"] },
  { "name": "Dimecoin", "symbols": ["DIME"] },
  { "name": "Aricoin", "symbols": ["ARI"] },
  { "name": "Machinecoin", "symbols": ["MAC"] },
  { "name": "DFSCoin", "symbols": ["DFS"] },
  { "name": "CannaCoin", "symbols": ["CCN"] },
  { "name": "808Coin", "symbols": ["808"] },
  { "name": "300 Token", "symbols": ["300"] },
  { "name": "KlondikeCoin", "symbols": ["KDC"] },
  { "name": "Terracoin", "symbols": ["TRC"] },
  { "name": "LanaCoin", "symbols": ["LANA"] },
  { "name": "Condensate", "symbols": ["RAIN"] },
  { "name": "MobileGo", "symbols": ["MGO", "EMGO"] },
  { "name": "CORION", "symbols": ["COR"] },
  { "name": "Masternodecoin", "symbols": ["MTNC"] },
  { "name": "LiteBitcoin", "symbols": ["LBTC", "LBTCX"] },
  { "name": "MarxCoin", "symbols": ["MARX"] },
  { "name": "MagicCoin", "symbols": ["MAGE"] },
  { "name": "OX Fina", "symbols": ["OX"] },
  { "name": "Atmos", "symbols": ["ATMS"] },
  { "name": "Allion", "symbols": ["ALL"] },
  { "name": "Guncoin", "symbols": ["GUN"] },
  { "name": "Creativecoin", "symbols": ["CREA"] },
  { "name": "NevaCoin", "symbols": ["NEVA"] },
  { "name": "NamoCoin", "symbols": ["NAMO"] },
  { "name": "PayCon", "symbols": ["CON"] },
  { "name": "HEAT", "symbols": ["HEAT"] },
  { "name": "Primecoin", "symbols": ["XPM"] },
  { "name": "TEKcoin", "symbols": ["TEK"] },
  { "name": "Coinonat", "symbols": ["CXT"] },
  { "name": "Karbo", "symbols": ["KRB"] },
  { "name": "Royalties", "symbols": ["XRY"] },
  { "name": "ArcticCoin", "symbols": ["ARC", "ARCX"] },
  { "name": "Open Trading Network", "symbols": ["OTN"] },
  { "name": "NetCoin", "symbols": ["NET"] },
  { "name": "Nyancoin", "symbols": ["NYAN"] },
  { "name": "DigiPulse", "symbols": ["DGPT"] },
  { "name": "Bitradio", "symbols": ["BRO"] },
  { "name": "EcoCoin", "symbols": ["ECO"] },
  { "name": "IncaKoin", "symbols": ["NKA"] },
  { "name": "DNotes", "symbols": ["NOTE"] },
  { "name": "PetroDollar", "symbols": ["XPD"] },
  { "name": "Musiconomi", "symbols": ["MCI"] },
  { "name": "Independent Money System", "symbols": ["IMS"] },
  { "name": "AudioCoin", "symbols": ["ADC"] },
  { "name": "XGOX", "symbols": ["XGOX"] },
  { "name": "FuelCoin", "symbols": ["FUEL"] },
  { "name": "PureVidz", "symbols": ["VIDZ"] },
  { "name": "DROXNE", "symbols": ["DRXNE"] },
  { "name": "HyperStake", "symbols": ["HYP"] },
  { "name": "Bitcoin Scrypt", "symbols": ["BTCS"] },
  { "name": "Footy Cash", "symbols": ["XFT"] },
  { "name": "Zeitcoin", "symbols": ["ZEIT"] },
  { "name": "Recently253Memetic", "symbols": ["PEPE"] },
  { "name": "DaxxCoin", "symbols": ["DAXX"] },
  { "name": "Billionaire Token", "symbols": ["XBL"] },
  { "name": "Chronos", "symbols": ["CRX"] },
  { "name": "OctoCoin", "symbols": ["888"] },
  { "name": "Soma", "symbols": ["SCT"] },
  { "name": "NobleCoin", "symbols": ["NOBL"] },
  { "name": "PopularCoin", "symbols": ["POP"] },
  { "name": "Hexx", "symbols": ["HXX"] },
  { "name": "CoffeeCoin", "symbols": ["CFC"] },
  { "name": "Sexcoin", "symbols": ["SXC"] },
  { "name": "FuzzBalls", "symbols": ["FUZZ"] },
  { "name": "FujiCoin", "symbols": ["FJC"] },
  { "name": "DigitalDevelopersFund", "symbols": ["DDF"] },
  { "name": "VapersCoin", "symbols": ["VPRC"] },
  { "name": "Altcoin", "symbols": ["ALT"] },
  { "name": "LiteDoge", "symbols": ["LDOGE"] },
  { "name": "Blockpool", "symbols": ["BPL"] },
  { "name": "Moin", "symbols": ["MOIN"] },
  { "name": "CryptoForecast", "symbols": ["CFT"] },
  { "name": "KushCoin", "symbols": ["KUSH"] },
  { "name": "Digitalcoin", "symbols": ["DGC"] },
  { "name": "Argentum", "symbols": ["ARG"] },
  { "name": "APX", "symbols": ["APX"] },
  { "name": "Dinastycoin", "symbols": ["DCY"] },
  { "name": "RussiaCoin", "symbols": ["RC"] },
  { "name": "Fonziecoin", "symbols": ["FONZ"] },
  { "name": "Ecobit", "symbols": ["ECOB"] },
  { "name": "TrumpCoin", "symbols": ["TRUMP"] },
  { "name": "Minex", "symbols": ["MINEX"] },
  { "name": "42-coin", "symbols": ["42", "FORTYTWO"] },
  { "name": "Phoenixcoin", "symbols": ["PXC"] },
  { "name": "Litecoin Plus", "symbols": ["LCP"] },
  { "name": "GAY Money", "symbols": ["GAY"] },
  { "name": "TittieCoin", "symbols": ["TTC"] },
  { "name": "Dalecoin", "symbols": ["DALC"] },
  { "name": "BipCoin", "symbols": ["BIP"] },
  { "name": "Beatcoin", "symbols": ["XBTS"] },
  { "name": "Titcoin", "symbols": ["TIT"] },
  { "name": "Animecoin", "symbols": ["ANI"] },
  { "name": "Cubits", "symbols": ["QBT"] },
  { "name": "Gapcoin", "symbols": ["GAP"] },
  { "name": "Quark", "symbols": ["QRK"] },
  { "name": "Halcyon", "symbols": ["HAL"] },
  { "name": "Bitcoin Fast", "symbols": ["BCF"] },
  { "name": "SkinCoin", "symbols": ["SKIN"] },
  { "name": "LiteCoin Ultra", "symbols": ["LTCU"] },
  { "name": "Megacoin", "symbols": ["MEC"] },
  { "name": "Quatloo", "symbols": ["QTL"] },
  { "name": "Joulecoin", "symbols": ["XJO"] },
  { "name": "Bolivarcoin", "symbols": ["BOLI"] },
  { "name": "Senderon", "symbols": ["SDRN"] },
  { "name": "Motocoin", "symbols": ["MOTO"] },
  { "name": "Eryllium", "symbols": ["ERY"] },
  { "name": "Francs", "symbols": ["FRN"] },
  { "name": "BitCoal", "symbols": ["COAL"] },
  { "name": "RedCoin", "symbols": ["RED"] },
  { "name": "PlexCoin", "symbols": ["PLX"] },
  { "name": "Cthulhu Offerings", "symbols": ["OFF"] },
  { "name": "Fastcoin", "symbols": ["FST"] },
  { "name": "PostCoin", "symbols": ["POST"] },
  { "name": "SixEleven", "symbols": ["611"] },
  { "name": "PutinCoin", "symbols": ["PUT"] },
  { "name": "BitcoinDark", "symbols": ["BTCD"] },
  { "name": "Triangles", "symbols": ["TRI"] },
  { "name": "Money", "symbols": [""] },
  { "name": "Kronecoin", "symbols": ["KRONE"] },
  { "name": "Renos", "symbols": ["RNS"] },
  { "name": "AquariusCoin", "symbols": ["ARCO"] },
  { "name": "Canada eCoin", "symbols": ["CDN"] },
  { "name": "Spots", "symbols": ["SPT"] },
  { "name": "SoonCoin", "symbols": ["SOON"] },
  { "name": "CacheCoin", "symbols": ["CACH"] },
  { "name": "Zetacoin", "symbols": ["ZET"] },
  { "name": "Blakecoin", "symbols": ["BLC"] },
  { "name": "Etheriya", "symbols": ["RIYA"] },
  { "name": "Tigercoin", "symbols": ["TGC"] },
  { "name": "Evil Coin", "symbols": ["EVIL"] },
  { "name": "GlobalBoost-Y", "symbols": ["BSTY"] },
  { "name": "Pakcoin", "symbols": ["PAK"] },
  { "name": "BlazeCoin", "symbols": ["BLZ"] },
  { "name": "Sakuracoin", "symbols": ["SKR"] },
  { "name": "C-Bit", "symbols": ["XCT"] },
  { "name": "SHACoin", "symbols": ["SHA"] },
  { "name": "GCN Coin", "symbols": ["GCN"] },
  { "name": "BnrtxCoin", "symbols": ["BNX"] },
  { "name": "Novacoin", "symbols": ["NVC"] },
  { "name": "Kurrent", "symbols": ["KURT"] },
  { "name": "FlutterCoin", "symbols": ["FLT"] },
  { "name": "WorldCoin", "symbols": ["WDC"] },
  { "name": "Coinlancer", "symbols": ["CL"] },
  { "name": "Magnetcoin", "symbols": ["MAGN"] },
  { "name": "Alphabit", "symbols": ["ABC"] },
  { "name": "Prototanium", "symbols": ["PR"] },
  { "name": "Gold Pressed Latinum", "symbols": ["GPL"] },
  { "name": "SpaceCoin", "symbols": ["SPACE"] },
  { "name": "MACRON", "symbols": ["MCRN"] },
  { "name": "Coin(O)", "symbols": ["CNO"] },
  { "name": "TopCoin", "symbols": ["TOP"] },
  { "name": "EncryptoTel", "symbols": ["ETT", "eETT", "wETT"] },
  { "name": "StarCredits", "symbols": ["STRC"] },
  { "name": "X-Coin", "symbols": ["XCO"] },
  { "name": "LeaCoin", "symbols": ["LEA"] },
  { "name": "iTicoin", "symbols": ["ITI"] },
  { "name": "GAIA", "symbols": ["GAIA"] },
  { "name": "Bitstar", "symbols": ["BITS"] },
  { "name": "Coin2.1", "symbols": ["C2"] },
  { "name": "InsaneCoin", "symbols": ["INSN"] },
  { "name": "Creatio", "symbols": ["XCRE"] },
  { "name": "RonPaulCoin", "symbols": ["RPC"] },
  { "name": "ChessCoin", "symbols": ["CHESS"] },
  { "name": "Ixcoin", "symbols": ["IXC"] },
  { "name": "BitBar", "symbols": ["BTB"] },
  { "name": "EDRCoin", "symbols": ["EDRC"] },
  { "name": "Eurocoin", "symbols": ["EUC"] },
  { "name": "MojoCoin", "symbols": ["MOJO"] },
  { "name": "Bitcoin Plus", "symbols": ["XBC"] },
  { "name": "Crypto Bullion", "symbols": ["CBX"] },
  { "name": "Marijuanacoin", "symbols": ["MAR"] },
  { "name": "RevolverCoin", "symbols": ["XRE"] },
  { "name": "Donationcoin", "symbols": ["DON"] },
  { "name": "Catcoin", "symbols": ["CAT"] },
  { "name": "Piggycoin", "symbols": ["PIGGY"] },
  { "name": "Bitgem", "symbols": ["BTG"] },
  { "name": "Prime-XI", "symbols": ["PXI"] },
  { "name": "BERNcash", "symbols": ["BERN"] },
  { "name": "SecureCoin", "symbols": ["SRC"] },
  { "name": "Ratecoin", "symbols": ["XRA"] },
  { "name": "$510 ", "symbols": ["UR"] },
  { "name": "SmartCoin", "symbols": ["SMC"] },
  { "name": "Swing", "symbols": ["SWING"] },
  { "name": "BumbaCoin", "symbols": ["BUMBA"] },
  { "name": "CompuCoin", "symbols": ["CPN"] },
  { "name": "ChanCoin", "symbols": ["CHAN"] },
  { "name": "Bitcedi", "symbols": ["BXC"] },
  { "name": "ZSEcoin", "symbols": ["ZSE"] },
  { "name": "Hackspace Capital", "symbols": ["HAC"] },
  { "name": "AurumCoin", "symbols": ["AU"] },
  { "name": "Elacoin", "symbols": ["ELC"] },
  { "name": "LeafCoin", "symbols": ["LEAF"] },
  { "name": "Darsek", "symbols": ["KED"] },
  { "name": "I0Coin", "symbols": ["I0C"] },
  { "name": "QubitCoin", "symbols": ["Q2C"] },
  { "name": "GoldPieces", "symbols": ["GP"] },
  { "name": "Bata", "symbols": ["BTA"] },
  { "name": "Coimatic 3.0", "symbols": ["CTIC3"] },
  { "name": "Marscoin", "symbols": ["MARS"] },
  { "name": "Kobocoin", "symbols": ["KOBO"] },
  { "name": "HODL Bucks", "symbols": ["HDLB"] },
  { "name": "SOILcoin", "symbols": ["SOIL"] },
  { "name": "Minereum", "symbols": ["MNE"] },
  { "name": "ParallelCoin", "symbols": ["DUO"] },
  { "name": "InflationCoin", "symbols": ["IFLT"] },
  { "name": "Flaxscript", "symbols": ["FLAX"] },
  { "name": "Netko", "symbols": ["NETKO"] },
  { "name": "Deutsche eMark", "symbols": ["DEM"] },
  { "name": "BenjiRolls", "symbols": ["BENJI"] },
  { "name": "BunnyCoin", "symbols": ["BUN"] },
  { "name": "Sterlingcoin", "symbols": ["SLG"] },
  { "name": "HoboNickels", "symbols": ["HBN"] },
  { "name": "ICOBID", "symbols": ["ICOB"] },
  { "name": "Truckcoin", "symbols": ["TRK"] },
  { "name": "Bit", "symbols": ["8BIT"] },
  { "name": "UniCoin", "symbols": ["UNIC"] },
  { "name": "Acoin", "symbols": ["ACOIN"] },
  { "name": "Emerald Crypto", "symbols": ["EMD"] },
  { "name": "GeertCoin", "symbols": ["GEERT"] },
  { "name": "Version", "symbols": ["V"] },
  { "name": "Opal", "symbols": ["OPAL"] },
  { "name": "Orbitcoin", "symbols": ["ORB"] },
  { "name": "SongCoin", "symbols": ["SONG"] },
  { "name": "Compcoin", "symbols": ["CMP"] },
  { "name": "Sativacoin", "symbols": ["STV"] },
  { "name": "Philosopher Stones", "symbols": ["PHS"] },
  { "name": "Fazzcoin", "symbols": ["FAZZ"] },
  { "name": "PlatinumBAR", "symbols": ["XPTX"] },
  { "name": "Granite", "symbols": ["GRN"] },
  { "name": "IrishCoin", "symbols": ["IRL"] },
  { "name": "UltraCoin", "symbols": ["UTC"] },
  { "name": "Sharkcoin", "symbols": ["SAK"] },
  { "name": "GameUnits", "symbols": ["UNITS"] },
  { "name": "Evotion", "symbols": ["EVO"] },
  { "name": "KekCoin", "symbols": ["KEK"] },
  { "name": "LiteBar", "symbols": ["LTB"] },
  { "name": "GPU Coin", "symbols": ["GPU"] },
  { "name": "GoldReserve", "symbols": ["XGR"] },
  { "name": "Metal Music Coin", "symbols": ["MTLMC", "MTLMC3"] },
  { "name": "SJWCoin", "symbols": ["SJW"] },
  { "name": "Virta Unique Coin", "symbols": ["VUC"] },
  { "name": "Safe Exchange Coin", "symbols": ["SAFEX"] },
  { "name": "CryptCoin", "symbols": ["CRYPT"] },
  { "name": "Sphre AIR", "symbols": ["XID"] },
  { "name": "Kayicoin", "symbols": ["KAYI"] },
  { "name": "Tattoocoin (Standard Edition)", "symbols": ["TSE"] },
  { "name": "SmartCash", "symbols": ["SMART"] },
  { "name": "Bismuth", "symbols": ["BIS"] },
  { "name": "HTMLCOIN", "symbols": ["HTML"] },
  { "name": "Mooncoin", "symbols": ["MOON"] },
  { "name": "Trollcoin", "symbols": ["TROLL"] },
  { "name": "GoldBlocks", "symbols": ["GB"] },
  { "name": "Virtacoinplus", "symbols": ["XVP"] },
  { "name": "MktCoin", "symbols": ["MLM"] },
  { "name": "Polis", "symbols": ["POLIS"] },
  { "name": "Qbic", "symbols": ["QBIC"] },
  { "name": "Phantomx", "symbols": ["PNX"] },
  { "name": "BiblePay", "symbols": ["BBP"] },
  { "name": "JavaScript Token", "symbols": ["JS"] },
  { "name": "NuShares", "symbols": ["NSR"] },
  { "name": "Manna", "symbols": ["MANNA"] },
  { "name": "eGold", "symbols": ["EGOLD"] },
  { "name": "KickCoin", "symbols": ["KICK"] },
  { "name": "Cobinhood", "symbols": ["COB"] },
  { "name": "NAGA", "symbols": ["NGC"] },
  { "name": "BitDegree", "symbols": ["BDG"] },
  { "name": "STK", "symbols": ["STK"] },
  { "name": "Dragonchain", "symbols": ["DRGN"] },
  { "name": "Odyssey", "symbols": ["OCN"] },
  { "name": "0x", "symbols": ["ZRX"] },
  { "name": "Santiment Network Token", "symbols": ["SAN"] },
  { "name": "Experience Points", "symbols": ["XP"] },
  { "name": "POLY AI", "symbols": ["AI"] },
  { "name": "BitSoar", "symbols": ["BSR"] },
  { "name": "Monero Gold", "symbols": ["XMRG"] },
  { "name": "ECC", "symbols": ["ECC"] },
  { "name": "LendConnect", "symbols": ["LCT"] },
  { "name": "StrongHands", "symbols": ["SHND"] },
  { "name": "WomenCoin", "symbols": ["WOMEN"] },
  { "name": "BitConnect", "symbols": ["BCC"] },
  { "name": "Elixir", "symbols": ["ELIX"] },
  { "name": "Internxt", "symbols": ["INXT"] },
  { "name": "Tristar Coin", "symbols": ["TSTR"] },
  { "name": "SHIELD", "symbols": ["XSH"] },
  { "name": "BuzzCoin", "symbols": ["BUZZ"] },
  { "name": "Magnet", "symbols": ["MAG"] },
  { "name": "DavorCoin", "symbols": ["DAV"] },
  { "name": "Swisscoin", "symbols": ["SIC"] },
  { "name": "E-coin", "symbols": ["ECN"] },
  { "name": "Uquid Coin", "symbols": ["UQC"] },
  { "name": "Sprouts", "symbols": ["SPRTS"] },
  { "name": "Centurion", "symbols": ["CNT"] },
  { "name": "LIFE", "symbols": ["LIFE"] },
  { "name": "B3Coin", "symbols": ["KB3"] },
  { "name": "Regalcoin", "symbols": ["REC"] },
  { "name": "Desire", "symbols": ["DSR"] },
  { "name": "FLiK", "symbols": ["FLIK"] },
  { "name": "CybCSec", "symbols": ["XCS"] },
  { "name": "Global Tour Coin", "symbols": ["GTC"] },
  { "name": "DigiCube", "symbols": ["CUBE"] },
  { "name": "Vsync", "symbols": ["VSX"] },
  { "name": "BLUE", "symbols": ["BLUE"] },
  { "name": "Espers", "symbols": ["ESP"] },
  { "name": "BitTokens", "symbols": ["BXT"] },
  { "name": "Ethereum Gold", "symbols": ["ETG"] },
  { "name": "LevoPlus", "symbols": ["LVPS"] },
  { "name": "UFO Coin", "symbols": ["UFO"] },
  { "name": "LiteCoin Gold", "symbols": ["LTG"] },
  { "name": "Sugar Exchange", "symbols": ["SGR"] },
  { "name": "NEO GOLD", "symbols": ["NEOG"] },
  { "name": "Equal", "symbols": ["EQL"] },
  { "name": "DraftCoin", "symbols": ["DFT"] },
  { "name": "Pure", "symbols": ["PURE"] },
  { "name": "Vulcano", "symbols": ["VULCANO", "VULC"] },
  { "name": "Speed Mining Service", "symbols": ["SMS"] },
  { "name": "Crave", "symbols": ["CRAVE"] },
  { "name": "Roofs", "symbols": ["ROOFS"] },
  { "name": "MinexCoin", "symbols": ["MNX"] },
  { "name": "Master Swiscoin", "symbols": ["MSCN"] },
  { "name": "Pabyosi Coin (Special)", "symbols": ["PCS"] },
  { "name": "Playkey", "symbols": ["PKT"] },
  { "name": "FedoraCoin", "symbols": ["TIPS"] },
  { "name": "T-coin", "symbols": ["TCOIN"] },
  { "name": "BitSerial", "symbols": ["BTE"] },
  { "name": "GOLD Reward Token", "symbols": ["GRX"] },
  { "name": "HarmonyCoin", "symbols": ["HMC"] },
  { "name": "Digital Money Bits", "symbols": ["DMB"] },
  { "name": "Cyder", "symbols": ["CYDER"] },
  { "name": "Greencoin", "symbols": ["GRE"] },
  { "name": "Safe Trade Coin", "symbols": ["XSTC"] },
  { "name": "Solaris", "symbols": ["XLR"] },
  { "name": "Runners", "symbols": ["RUNNERS"] },
  { "name": "Zlancer", "symbols": ["ZCG"] },
  { "name": "BritCoin", "symbols": ["BRIT"] },
  { "name": "eBitcoin", "symbols": ["EBTC", "EBTCNEW"] },
  { "name": "GlobalToken", "symbols": ["GLT"] },
  { "name": "ELTCOIN", "symbols": ["ELT"] },
  { "name": "Presearch", "symbols": ["PRE", "PRS"] },
  { "name": "ZoZoCoin", "symbols": ["ZZC"] },
  { "name": "Ammo Reloaded", "symbols": ["AMMO"] },
  { "name": "Ebittree Coin", "symbols": ["EBT"] },
  { "name": "PeepCoin", "symbols": ["PCN"] },
  { "name": "DynamicCoin", "symbols": ["DMC"] },
  { "name": "HOdlcoin", "symbols": ["HODL"] },
  { "name": "Coupecoin", "symbols": ["COUPE"] },
  { "name": "Bitcoin Red", "symbols": ["BTCRED"] },
  { "name": "StarCash Network", "symbols": ["STARS"] },
  { "name": "BlakeStar", "symbols": ["BLAS"] },
  { "name": "Scorecoin", "symbols": ["SCORE"] },
  { "name": "Jetcoin", "symbols": ["JET"] },
  { "name": "India Coin", "symbols": ["INDIA"] },
  { "name": "Jin Coin", "symbols": ["JIN"] },
  { "name": "Birds", "symbols": ["BIRDS"] },
  { "name": "Vault Coin", "symbols": ["VLTC"] },
  { "name": "KiloCoin", "symbols": ["KLC"] },
  { "name": "SafeCoin", "symbols": ["SFE"] },
  { "name": "Honey", "symbols": ["HONEY"] },
  { "name": "Topaz Coin", "symbols": ["TOPAZ"] },
  { "name": "MiloCoin", "symbols": ["MILO"] },
  { "name": "BROTHER", "symbols": ["BRAT"] },
  { "name": "SISA", "symbols": ["SISA"] },
  { "name": "Wowcoin", "symbols": ["WOW"] },
  { "name": "iDice", "symbols": ["ICE"] },
  { "name": "GoldMaxCoin", "symbols": ["GMX"] },
  { "name": "Dutch Coin", "symbols": ["DUTCH"] },
  { "name": "Neuro", "symbols": ["NRO"] },
  { "name": "Impact", "symbols": ["IMX"] },
  { "name": "Bitbase", "symbols": ["BTBc"] },
  { "name": "Protean", "symbols": ["PRN"] },
  { "name": "GlassCoin", "symbols": ["GLS"] },
  { "name": "Akuya Coin", "symbols": ["AKY"] },
  { "name": "Bitcoin Planet", "symbols": ["BTPL"] },
  { "name": "CaliphCoin", "symbols": ["CALC"] },
  { "name": "Goodomy", "symbols": ["GOOD"] },
  { "name": "SuperCoin", "symbols": ["SUPER"] },
  { "name": "Golfcoin", "symbols": ["GOLF"] },
  { "name": "Luna Coin", "symbols": ["LUNA"] },
  { "name": "Bela", "symbols": ["BELA"] },
  { "name": "Digital Rupees", "symbols": ["DRS"] },
  { "name": "BigUp", "symbols": ["BIGUP"] },
  { "name": "Remicoin", "symbols": ["RMC"] },
  { "name": "High Gain", "symbols": ["HIGH"] },
  { "name": "bitqy", "symbols": ["BQ"] },
  { "name": "Elysium", "symbols": ["ELS"] },
  { "name": "Magnum", "symbols": ["MGM"] },
  { "name": "Natcoin", "symbols": ["NTC"] },
  { "name": "Aces", "symbols": ["ACES"] },
  { "name": "Credence Coin", "symbols": ["CRDNC"] },
  { "name": "CHIPS", "symbols": ["CHIPS"] },
  { "name": "Huncoin", "symbols": ["HNC"] },
  { "name": "Zennies", "symbols": ["ZENI"] },
  { "name": "AmsterdamCoin", "symbols": ["AMS"] },
  { "name": "Visio", "symbols": ["VISIO"] },
  { "name": "TurboCoin", "symbols": ["TURBO"] },
  { "name": "Tellurion", "symbols": ["TELL"] },
  { "name": "Wink", "symbols": ["WINK"] },
  { "name": "FAPcoin", "symbols": ["FAP"] },
  { "name": "Bolenum", "symbols": ["BLN"] },
  { "name": "Regacoin", "symbols": ["REGA"] },
  { "name": "Fujinto", "symbols": ["NTO"] },
  { "name": "BOAT", "symbols": ["BOAT"] },
  { "name": "Coimatic 2.0", "symbols": ["CTIC2"] },
  { "name": "UGAIN", "symbols": ["GAIN"] },
  { "name": "Cheapcoin", "symbols": ["CHEAP"] },
  { "name": "Lampix", "symbols": ["PIX"] },
  { "name": "Theresa May Coin", "symbols": ["MAY"] },
  { "name": "Artex Coin", "symbols": ["ATX"] },
  { "name": "XTD Coin", "symbols": ["XTD"] },
  { "name": "Ethbits", "symbols": ["ETBS"] },
  { "name": "Target Coin", "symbols": ["TGT"] },
  { "name": "BetaCoin", "symbols": ["BET"] },
  { "name": "Peacecoin", "symbols": ["PEC"] },
  { "name": "PlayerCoin", "symbols": ["PLACO"] },
  { "name": "Commodity Ad Network", "symbols": ["CDX"] },
  { "name": "Primulon", "symbols": ["PRIMU"] },
  { "name": "Link Platform", "symbols": ["LNK"] },
  { "name": "FuturXe", "symbols": ["FXE"] },
  { "name": "Happycoin", "symbols": ["HPC"] },
  { "name": "Prospectors Gold", "symbols": ["PGL"] },
  { "name": "Torcoin", "symbols": ["TOR"] },
  { "name": "Ulatech", "symbols": ["ULA"] },
  { "name": "LandCoin", "symbols": ["LDC"] },
  { "name": "BlazerCoin", "symbols": ["BLAZR"] },
  { "name": "NumusCash", "symbols": ["NUMUS"] },
  { "name": "AnarchistsPrime", "symbols": ["ACP"] },
  { "name": "HealthyWormCoin", "symbols": ["WORM"] },
  { "name": "ZetaMicron", "symbols": ["ZMC"] },
  { "name": "PoSToken", "symbols": ["POS"] },
  { "name": "Slevin", "symbols": ["SLEVIN"] },
  { "name": "Bastonet", "symbols": ["BSN"] },
  { "name": "Halloween Coin", "symbols": ["HALLO"] },
  { "name": "Antimatter", "symbols": ["ANTX"] },
  { "name": "PinkDog", "symbols": ["PDG"] },
  { "name": "Aseancoin", "symbols": ["ASN"] },
  { "name": "netBit", "symbols": ["NBIT"] },
  { "name": "Printerium", "symbols": ["PRX"] },
  { "name": "Pirate Blocks", "symbols": ["SKULL"] },
  { "name": "Tattoocoin (Limited Edition)", "symbols": ["TLE"] },
  { "name": "REX", "symbols": ["REX"] },
  { "name": "LAToken", "symbols": ["LA"] },
  { "name": "VirtualCoin", "symbols": ["VC"] },
  { "name": "Adzcoin", "symbols": ["ADZ"] },
  { "name": "TaaS", "symbols": ["TAAS"] },
  { "name": "Metaverse ETP", "symbols": ["ETP"] },
  { "name": "AidCoin", "symbols": ["AID"] },
  { "name": "Streamr DATAcoin", "symbols": ["DATA"] },
  { "name": "Aventus", "symbols": ["AVT"] },
  { "name": "Huobi Token", "symbols": ["HT"] },
  { "name": "Elastos", "symbols": ["ELA"] },
  { "name": "WaykiChain", "symbols": ["WICC"] },
  { "name": "Propy", "symbols": ["PROPY", "PRO"] },
  { "name": "QunQun", "symbols": ["QUN"] },
  { "name": "SIRIN LABS Token", "symbols": ["SRN"] },
  { "name": "Zilliqa", "symbols": ["ZIL"] },
  { "name": "Red Pulse", "symbols": ["RPX"] },
  { "name": "LinkEye", "symbols": ["LET"] },
  { "name": "Ruff", "symbols": ["RUFF"] },
  { "name": "WePower", "symbols": ["WPR"] },
  { "name": "Theta Token", "symbols": ["THETA"] },
  { "name": "All Sports", "symbols": ["SOC"] },
  { "name": "MediShares", "symbols": ["MDS"] },
  { "name": "Zilla", "symbols": ["ZLA"] },
  { "name": "TopChain", "symbols": ["TOPC"] },
  { "name": "SmartMesh", "symbols": ["SMT"] },
  { "name": "Matryx", "symbols": ["MTX"] },
  { "name": "SunContract", "symbols": ["SNC"] },
  { "name": "CoinMeet", "symbols": ["MEE"] },
  { "name": "UTRUST", "symbols": ["UTK"] },
  { "name": "Yee", "symbols": ["YEE"] },
  { "name": "EchoLink", "symbols": ["EKO"] },
  { "name": "Datum", "symbols": ["DAT"] },
  { "name": "SwftCoin", "symbols": ["SWFTC"] },
  { "name": "BitcoinX", "symbols": ["BCX"] },
  { "name": "LockChain", "symbols": ["LOC"] },
  { "name": "REAL", "symbols": ["REA"] },
  { "name": "Selfkey", "symbols": ["KEY"] },
  { "name": "Dai", "symbols": ["DAI"] },
  { "name": "HelloGold", "symbols": ["HGT"] },
  { "name": "$0$0.9458240.00%", "symbols": ["WINGS"] },
  { "name": "$0$1.380.00%Recently", "symbols": ["ZRX"] },
  { "name": "OFCOIN", "symbols": ["OF"] },
  { "name": "True Chain", "symbols": ["TRUE"] },
  { "name": "FairGame", "symbols": ["FAIR"] },
  { "name": "Delphy", "symbols": ["DPY"] },
  { "name": "ugChain", "symbols": ["UGC"] },
  { "name": "LightChain", "symbols": ["LIGHT"] },
  { "name": "SportyCo", "symbols": ["SPF"] },
  { "name": "Kcash", "symbols": ["KCASH"] },
  { "name": "Molecular Future", "symbols": ["MOF"] },
  { "name": "Worldcore", "symbols": ["WRC"] },
  { "name": "Exchange Union", "symbols": ["XUC"] },
  { "name": "RealChain", "symbols": ["RCT"] },
  { "name": "BLOCKv", "symbols": ["VEE"] },
  { "name": "StarChain", "symbols": ["STC"] },
  { "name": "Acute Angle Cloud", "symbols": ["AAC"] },
  { "name": "Health Mutual Society", "symbols": ["HMC"] },
  { "name": "Hydro Protocol", "symbols": ["HOT"] },
  { "name": "SelfSell", "symbols": ["SSC"] },
  { "name": "Ace", "symbols": ["ACE"] },
  { "name": "Primas", "symbols": ["PST"] },
  { "name": "Read", "symbols": ["READ"] },
  { "name": "Content and AD Network", "symbols": ["CAN"] },
  { "name": "Trade Token", "symbols": ["TIO"] },
  { "name": "RefToken", "symbols": ["REF"] },
  { "name": "Measurable Data Token", "symbols": ["MDT"] },
  { "name": "OneRoot Network", "symbols": ["RNT"] },
  { "name": "TokenClub", "symbols": ["TCT"] },
  { "name": "x", "symbols": ["ZRX"] },
  { "name": "Viuly", "symbols": ["VIU"] },
  { "name": "Qvolta", "symbols": ["QVT"] },
  { "name": "Leverj", "symbols": ["LEV"] },
  { "name": "BT2", "symbols": ["BT2"] },
  { "name": "ATLANT", "symbols": ["ATL"] },
  { "name": "Maggie", "symbols": ["MAG"] },
  { "name": "IPChain", "symbols": ["IPC"] },
  { "name": "COMSA", "symbols": ["CMS.ETH", "CMS.XEM", "CMS"] },
  { "name": "Pepe Cash", "symbols": ["PEPECASH"] },
  { "name": "Storjcoin X", "symbols": ["SJCX"] },
  { "name": "Primalbase Token", "symbols": ["PBT"] },
  { "name": "TIES Network", "symbols": ["TIE"] },
  { "name": "indaHash", "symbols": ["IDH"] },
  { "name": "Kolion", "symbols": ["KOLION"] },
  { "name": "Waves Community Token", "symbols": ["WCT"] },
  { "name": "ZrCoin", "symbols": ["ZRC"] },
  { "name": "Titanium Blockchain", "symbols": ["BAR"] },
  { "name": "SingularityNET", "symbols": ["AGI"] },
  { "name": "Miners' Reward Token", "symbols": ["MRT"] },
  { "name": "MSD", "symbols": ["MSD"] },
  { "name": "Tracto", "symbols": ["TRCT"] },
  { "name": "Bowhead", "symbols": ["AHT"] },
  { "name": "Wagerr", "symbols": ["WGR"] },
  { "name": "Starta", "symbols": ["STA"] },
  { "name": "EOT Token", "symbols": ["EOT"] },
  { "name": "CryptoPing", "symbols": ["PING"] },
  { "name": "ANRYZE", "symbols": ["RYZ"] },
  { "name": "Suretly", "symbols": ["SUR"] },
  { "name": "Credo", "symbols": ["CREDO"] },
  { "name": "Oceanlab", "symbols": ["OCL"] },
  { "name": "Paragon", "symbols": ["PRG"] },
  { "name": "Ripto Bux", "symbols": ["RBX"] },
  { "name": "Chronobank", "symbols": ["TIME"] },
  { "name": "Bankcoin", "symbols": ["B@"] },
  { "name": "InPay", "symbols": ["INPAY"] },
  { "name": "ICOS", "symbols": ["ICOS"] },
  { "name": "WavesGo", "symbols": ["WGO"] },
  { "name": "Bytecoin", "symbols": ["BCN"] },
  { "name": "Pascal Coin", "symbols": ["PASC"] },
  { "name": "Riecoin", "symbols": ["RIC"] },
  { "name": "Bitmark", "symbols": ["BTM"] },
  { "name": "HunterCoin", "symbols": ["HUC"] },
  { "name": "Hacken", "symbols": ["HKN"] },
  { "name": "GoldMint", "symbols": ["MNTP"] },
  { "name": "SwapToken", "symbols": ["TOKEN"] },
  { "name": "TOKYO", "symbols": ["TOKC"] },
  { "name": "Tokenbox", "symbols": ["TBX"] },
  { "name": "vSlice", "symbols": ["VSLICE", "VSL"] },
  { "name": "Cryptonex", "symbols": ["CNX"] },
  { "name": "HitCoin", "symbols": ["HTC"] },
  { "name": "Peerguess", "symbols": ["GUESS"] },
  { "name": "HTML5COIN", "symbols": ["HTML5"] },
  { "name": "E-Dinar Coin", "symbols": ["EDR2", "EDR"] },
  { "name": "NewYorkCoin", "symbols": ["NYC"] },
  { "name": "Bitvolt", "symbols": ["VOLT"] },
  { "name": "FirstCoin", "symbols": ["FRST"] },
  { "name": "Bitcoin Atom", "symbols": ["BCA"] },
  { "name": "SONO", "symbols": ["ALTCOM"] },
  { "name": "Lightning Bitcoin", "symbols": ["LBTC"] },
  { "name": "Veltor", "symbols": ["VLT"] },
  { "name": "SegWit2x", "symbols": ["B2X"] },
  { "name": "Bitcoin God", "symbols": ["GOD"] },
  { "name": "Ethereum Cash", "symbols": ["ECASH"] },
  { "name": "Covesting", "symbols": ["COVX", "COV"] },
  { "name": "iEthereum", "symbols": ["IETH"] },
  { "name": "Shadow Token", "symbols": ["SHDW"] },
  { "name": "RubleBit", "symbols": ["RUBIT"] },
  { "name": "bitJob", "symbols": ["STU"] },
  { "name": "Quebecoin", "symbols": ["QBC"] },
  { "name": "ATBCoin", "symbols": ["ATB"] },
  { "name": "Rupaya", "symbols": ["RUPX"] },
  { "name": "ArbitrageCT", "symbols": ["ARCT"] },
  { "name": "Project-X", "symbols": ["NANOX"] },
  { "name": "Wi Coin", "symbols": ["WIC"] },
  { "name": "JobsCoin", "symbols": ["JOBS"] },
  { "name": "Onix", "symbols": ["ONX"] },
  { "name": "Advanced Internet Blocks", "symbols": ["AIB"] },
  { "name": "Ethereum Lite", "symbols": ["ELITE"] },
  { "name": "Braincoin", "symbols": ["BRAIN"] },
  { "name": "XDE II", "symbols": ["XDE2"] },
  { "name": "RoyalCoin", "symbols": ["ROYAL"] },
  { "name": "TrueFlip", "symbols": ["TFL"] },
  { "name": "Valorbit", "symbols": ["VAL"] },
  { "name": "Polybius", "symbols": ["PLBT"] },
  { "name": "TagCoin", "symbols": ["TAG"] },
  { "name": "Crystal Clear", "symbols": ["CCT"] },
  { "name": "Opescoin", "symbols": ["OPES"] },
  { "name": "CrevaCoin", "symbols": ["CREVA"] },
  { "name": "TrickyCoin", "symbols": ["TRICK"] },
  { "name": "Carboncoin", "symbols": ["CARBON"] },
  { "name": "RabbitCoin", "symbols": ["RBBT"] },
  { "name": "BTCMoon", "symbols": ["BTCM"] },
  { "name": "Quotient", "symbols": ["XQN"] },
  { "name": "AntiBitcoin", "symbols": ["ANTI"] },
  { "name": "Speedcash", "symbols": ["SCS"] },
  { "name": "Mao Zedong", "symbols": ["MAO"] },
  { "name": "Bubble", "symbols": ["BUB"] },
  { "name": "MetalCoin", "symbols": ["METAL"] },
  { "name": "Unrealcoin", "symbols": ["URC"] },
  { "name": "Rialto", "symbols": ["XRL"] },
  { "name": "BioBar", "symbols": ["BIOB"] },
  { "name": "Universe", "symbols": ["UNI"] },
  { "name": "LePen", "symbols": ["LEPEN"] },
  { "name": "GeyserCoin", "symbols": ["GSR"] },
  { "name": "Eternity", "symbols": ["ENT"] },
  { "name": "iCoin", "symbols": ["ICN"] },
  { "name": "Xios", "symbols": ["XIOS"] },
  { "name": "Bitcoin 21", "symbols": ["XBTC21"] },
  { "name": "PrismChain", "symbols": ["PRM"] },
  { "name": "Wild Beast Block", "symbols": ["WBB"] },
  { "name": "Debitcoin", "symbols": ["DBTC"] },
  { "name": "DAPPSTER", "symbols": ["DLISK"] },
  { "name": "KingN Coin", "symbols": ["KNC"] },
  { "name": "Bitok", "symbols": ["BITOK"] },
  { "name": "Happy Creator Coin", "symbols": ["HCC"] },
  { "name": "PayPeer", "symbols": ["PAYP"] },
  { "name": "BitBoost", "symbols": ["BBT"] },
  { "name": "RSGPcoin", "symbols": ["RSGP"] },
  { "name": "Zayedcoin", "symbols": ["ZYD"] },
  { "name": "Ultimate Secure Cash", "symbols": ["USC"] },
  { "name": "SocialCoin", "symbols": ["SOCC"] },
  { "name": "Elementrem", "symbols": ["ELE"] },
  { "name": "ShellCoin", "symbols": ["SHELL"] },
  { "name": "SportsCoin", "symbols": ["SPORT"] },
  { "name": "BowsCoin", "symbols": ["BSC"] },
  { "name": "Blackstar", "symbols": ["BSTAR"] },
  { "name": "Californium", "symbols": ["CF"] },
  { "name": "LetItRide", "symbols": ["LIR"] },
  { "name": "Verify", "symbols": ["CRED"] },
  { "name": "Voyacoin", "symbols": ["VOYA"] },
  { "name": "BlueCoin", "symbols": ["BLU"] },
  { "name": "SatoshiMadness", "symbols": ["MAD"] },
  { "name": "PayCoin", "symbols": ["XPY"] },
  { "name": "Litecred", "symbols": ["LTCR"] },
  { "name": "MaxCoin", "symbols": ["MAX"] },
  { "name": "CryptoWorldX Token", "symbols": ["CWXT"] },
  { "name": "Dollarcoin", "symbols": ["DLC"] },
  { "name": "ImpulseCoin", "symbols": ["IMPS"] },
  { "name": "Ride My Car", "symbols": ["RIDE"] },
  { "name": "LuckChain", "symbols": ["BASH"] },
  { "name": "Digital Bullion Gold", "symbols": ["DBG"] },
  { "name": "Lazaruscoin", "symbols": ["LAZ"] },
  { "name": "Iconic", "symbols": ["ICON"] },
  { "name": "OsmiumCoin", "symbols": ["OS76"] },
  { "name": "2GIVE", "symbols": ["2GIVE"] },
  { "name": "TodayCoin", "symbols": ["TODAY"] },
  { "name": "PosEx", "symbols": ["PEX"] },
  { "name": "MindCoin", "symbols": ["MND"] },
  { "name": "G3N", "symbols": ["GEN"] },
  { "name": "OCOW", "symbols": ["OCOW"] },
  { "name": "Signatum", "symbols": ["SIGT"] },
  { "name": "P7Coin", "symbols": ["P7C"] },
  { "name": "Xaucoin", "symbols": ["XAU"] },
  { "name": "Firecoin", "symbols": ["FIRE"] },
  { "name": "DarkLisk", "symbols": ["DISK"] },
  { "name": "DomRaider", "symbols": ["DRT"] },
  { "name": "Antilitecoin", "symbols": ["ALTC"] },
  { "name": "Zonecoin", "symbols": ["ZNE"] },
  { "name": "Concoin", "symbols": ["CONX"] },
  { "name": "BiosCrypto", "symbols": ["BIOS"] },
  { "name": "Zurcoin", "symbols": ["ZUR"] },
  { "name": "RichCoin", "symbols": ["RICHX"] },
  { "name": "Rubies", "symbols": ["RBIES"] },
  { "name": "Cashme", "symbols": ["CME"] },
  { "name": "EGO", "symbols": ["EGO"] },
  { "name": "Shilling", "symbols": ["SH"] },
  { "name": "DeltaCredits", "symbols": ["DCRE"] },
  { "name": "Privatix", "symbols": ["PRIX"] },
  { "name": "FireFlyCoin", "symbols": ["FFC"] },
  { "name": "Colossuscoin V2", "symbols": ["CV2"] },
  { "name": "HiCoin", "symbols": ["XHI"] },
  { "name": "Destiny", "symbols": ["DES"] },
  { "name": "Flycoin", "symbols": ["FLY"] },
  { "name": "Axiom", "symbols": ["AXIOM"] },
  { "name": "ARbit", "symbols": ["ARB"] },
  { "name": "Uro", "symbols": ["URO"] },
  { "name": "Yescoin", "symbols": ["YES"] },
  { "name": "The Vegan Initiative", "symbols": ["XVE"] },
  { "name": "Bitcurrency", "symbols": ["BTCR"] },
  { "name": "Operand", "symbols": ["OP"] },
  { "name": "Cypher", "symbols": ["CYP"] },
  { "name": "Xonecoin", "symbols": ["XOC"] },
  { "name": "AmberCoin", "symbols": ["AMBER"] },
  { "name": "Cabbage", "symbols": ["CAB"] },
  { "name": "Selfiecoin", "symbols": ["SLFI"] },
  { "name": "ShadowCash", "symbols": ["SDC"] },
  { "name": "PX", "symbols": ["PX"] },
  { "name": "GlobalCoin", "symbols": ["GLC"] },
  { "name": "TheCreed", "symbols": ["TCR"] },
  { "name": "Pulse", "symbols": ["PULSE"] },
  { "name": "Franko", "symbols": ["FRK"] },
  { "name": "PLNcoin", "symbols": ["PLNC"] },
  { "name": "Yacoin", "symbols": ["YAC"] },
  { "name": "Hedge", "symbols": ["HDG"] },
  { "name": "PokeCoin", "symbols": ["POKE"] },
  { "name": "Moneta", "symbols": ["MONETA"] },
  { "name": "WayGuide", "symbols": ["WAY"] },
  { "name": "TAGRcoin", "symbols": ["TAGR"] },
  { "name": "LinkedCoin", "symbols": ["LKC"] },
  { "name": "BTCtalkcoin", "symbols": ["TALK"] },
  { "name": "VIP Tokens", "symbols": ["VIP"] },
  { "name": "High Voltage", "symbols": ["HVCO"] },
  { "name": "Cycling Coin", "symbols": ["CYC"] },
  { "name": "Dashs", "symbols": ["DASHS"] },
  { "name": "Psilocybin", "symbols": ["PSY"] },
  { "name": "InvisibleCoin", "symbols": ["IVZ"] },
  { "name": "Rcoin", "symbols": ["RCN"] },
  { "name": "Omicron", "symbols": ["OMC"] },
  { "name": "BillaryCoin", "symbols": ["BLRY"] },
  { "name": "Dreamcoin", "symbols": ["DRM"] },
  { "name": "EggCoin", "symbols": ["EGG"] },
  { "name": "VectorAI", "symbols": ["VEC2"] },
  { "name": "Karmacoin", "symbols": ["KARMA"] },
  { "name": "SecretCoin", "symbols": ["SCRT"] },
  { "name": "Hyper", "symbols": ["HYPERX"] },
  { "name": "NodeCoin", "symbols": ["NODC"] },
  { "name": "Steps", "symbols": ["STEPS"] },
  { "name": "Bitz", "symbols": ["BITZ"] },
  { "name": "IslaCoin", "symbols": ["ISL"] },
  { "name": "Digital Credits", "symbols": ["DGCS"] },
  { "name": "MMXVI", "symbols": ["MMXVI"] },
  { "name": "GameLeagueCoin", "symbols": ["GML"] },
  { "name": "Jewels", "symbols": ["JWL"] },
  { "name": "TeamUp", "symbols": ["TEAM"] },
  { "name": "WARP", "symbols": ["WARP"] },
  { "name": "SydPak", "symbols": ["SDP"] },
  { "name": "Dubstep", "symbols": ["DUB"] },
  { "name": "Stress", "symbols": ["STS"] },
  { "name": "PonziCoin", "symbols": ["PONZI"] },
  { "name": "Save and Gain", "symbols": ["SANDG"] },
  { "name": "GameBet Coin", "symbols": ["GBT"] },
  { "name": "FrankyWillCoin", "symbols": ["FRWC"] },
  { "name": "X2", "symbols": ["X2"] },
  { "name": "BitAlphaCoin", "symbols": ["BAC"] },
  { "name": "FlavorCoin", "symbols": ["FLVR"] },
  { "name": "iBank", "symbols": ["IBANK"] },
  { "name": "ATMChain", "symbols": ["ATMCHA", "ATM"] },
  { "name": "AvatarCoin", "symbols": ["AV"] },
  { "name": "Shorty", "symbols": ["SHORTY"] },
  { "name": "SproutsExtreme", "symbols": ["SPEX"] },
  { "name": "WMCoin", "symbols": ["WMC"] },
  { "name": "Orlycoin", "symbols": ["ORLY"] },
  { "name": "BeaverCoin", "symbols": ["BVC"] },
  { "name": "GuccioneCoin", "symbols": ["GCC"] },
  { "name": "LAthaan", "symbols": ["LTH"] },
  { "name": "MoneyCoin", "symbols": ["MONEY"] },
  { "name": "PIECoin", "symbols": ["PIE"] },
  { "name": "CyberCoin", "symbols": ["CC"] },
  { "name": "Sling", "symbols": ["SLING"] },
  { "name": "CBD Crystals", "symbols": ["CBD"] },
  { "name": "KashhCoin", "symbols": ["KASHH"] },
  { "name": "Nimiq", "symbols": ["NET"] },
  { "name": "Mysterium", "symbols": ["MYST"] },
  { "name": "Neumark", "symbols": ["NEU"] },
  { "name": "TokenCard", "symbols": ["TKN"] },
  { "name": "Pluton", "symbols": ["PLU"] },
  { "name": "BCAP", "symbols": ["BCAP"] },
  { "name": "Unity Ingot", "symbols": ["UNY"] },
  { "name": "Soarcoin", "symbols": ["SOAR"] },
  { "name": "Eroscoin", "symbols": ["ERO"] },
  { "name": "Dynamic Trading Rights", "symbols": ["DTR"] },
  { "name": "RouletteToken", "symbols": ["RLT"] },
  { "name": "SwissBorg", "symbols": ["CHSB"] },
  { "name": "InsurePal", "symbols": ["IPL"] },
  { "name": "Xaurum", "symbols": ["XAUR"] },
  { "name": "President Trump", "symbols": ["PRES"] },
  { "name": "Yocoin", "symbols": ["YOC"] },
  { "name": "UniversalRoyalCoin", "symbols": ["UNRC"] },
  { "name": "Hive", "symbols": ["HVN"] },
  { "name": "Peerplays", "symbols": ["PPY"] },
  { "name": "LEOcoin", "symbols": ["LEO"] },
  { "name": "OBITS", "symbols": ["OBITS"] },
  { "name": "Veros", "symbols": ["VRS"] },
  { "name": "Quantum", "symbols": ["QAU"] },
  { "name": "Macro", "symbols": ["MCR"] },
  { "name": "CryptoCarbon", "symbols": ["CCRB"] },
  { "name": "Elcoin", "symbols": ["EL"] },
  { "name": "Chronologic", "symbols": ["DAY"] },
  { "name": "Zilbercoin", "symbols": ["ZBC"] },
  { "name": "Helleniccoin", "symbols": ["HNC"] },
  { "name": "Escroco", "symbols": ["ESC"] },
  { "name": "PiplCoin", "symbols": ["PIPL"] },
  { "name": "Flixxo", "symbols": ["FLIXX"] },
  { "name": "Abncoin", "symbols": ["ABN"] },
  { "name": "ReeCoin", "symbols": ["REE"] },
  { "name": "Oxycoin", "symbols": ["OXY"] },
  { "name": "FinCoin", "symbols": ["FNC"] },
  { "name": "TechShares", "symbols": ["THS"] },
  { "name": "First Bitcoin", "symbols": ["BIT"] },
  { "name": "DIBCOIN", "symbols": ["DIBC"] },
  { "name": "Nitro", "symbols": ["NOX"] },
  { "name": "AllSafe", "symbols": ["ASAFE2"] },
  { "name": "Dollar Online", "symbols": ["DOLLAR"] },
  { "name": "Bitpark Coin", "symbols": ["BPC"] },
  { "name": "EventChain", "symbols": ["EVC"] },
  { "name": "FUNCoin", "symbols": ["FUNC"] },
  { "name": "UNCoin", "symbols": ["UNC"] },
  { "name": "Avoncoin", "symbols": ["ACN"] },
  { "name": "Rawcoin", "symbols": ["XRC"] },
  { "name": "Cloud", "symbols": ["CLD"] },
  { "name": "Animation Vision Cash", "symbols": ["AVH"] },
  { "name": "Tezos (Pre-Launch)", "symbols": ["XTZ"] },
  { "name": "AirToken", "symbols": ["AIR"] },
  { "name": "Rivetz", "symbols": ["RVT"] },
  { "name": "Etheroll", "symbols": ["DICE"] },
  { "name": "Storm", "symbols": ["STORM"] },
  { "name": "Veritaseum", "symbols": ["VERI"] },
  { "name": "Zeusshield", "symbols": ["ZSC"] },
  { "name": "OriginTrail", "symbols": ["TRAC"] },
  { "name": "MCAP", "symbols": ["MCAP"] },
  { "name": "Lamden", "symbols": ["TAU"] },
  { "name": "DIMCOIN", "symbols": ["DIM"] },
  { "name": "FlypMe", "symbols": ["FYP"] },
  { "name": "Indicoin", "symbols": ["INDI"] },
  { "name": "Cryptopay", "symbols": ["CPAY"] },
  { "name": "BitDice", "symbols": ["CSNO"] },
  { "name": "COSS", "symbols": ["COSS"] },
  { "name": "Bitair", "symbols": ["BTCA"] },
  { "name": "Maecenas", "symbols": ["ART"] },
  { "name": "Octanox", "symbols": ["OTX"] },
  { "name": "Dovu", "symbols": ["DOV"] },
  { "name": "Authorship", "symbols": ["ATS"] },
  { "name": "CarTaxi Token", "symbols": ["CTX"] },
  { "name": "DAO.Casino", "symbols": ["BET"] },
  { "name": "BOScoin", "symbols": ["BOS"] },
  { "name": "CryptoInsight", "symbols": ["TKR"] },
  { "name": "Opus", "symbols": ["OPT"] },
  { "name": "QuazarCoin", "symbols": ["QCN"] },
  { "name": "ExchangeN", "symbols": ["EXN"] },
  { "name": "NEVERDIE", "symbols": ["NDC"] },
  { "name": "Useless Ethereum Token", "symbols": ["UET"] },
  { "name": "United Traders Token", "symbols": ["UTT"] },
  { "name": "Dashcoin", "symbols": ["DSH"] },
  { "name": "Farad", "symbols": ["FRD"] },
  { "name": "BitAsean", "symbols": ["BAS"] },
  { "name": "EthBet", "symbols": ["EBET"] },
  { "name": "FundYourselfNow", "symbols": ["FYN"] },
  { "name": "Starbase", "symbols": ["STAR"] },
  { "name": "Fantomcoin", "symbols": ["FCN"] },
  { "name": "Fortuna", "symbols": ["FOTA"] },
  { "name": "THEKEY", "symbols": ["TKY"] },
  { "name": "Zeepin", "symbols": ["ZPT"] },
  { "name": "KuCoin Shares", "symbols": ["KCS"] },
  { "name": "QLINK", "symbols": ["QLC"] },
  { "name": "Telcoin", "symbols": ["TEL"] },
  { "name": "RChain", "symbols": ["RHOC"] },
  { "name": "carVertical", "symbols": ["CV"] },
  { "name": "LOCIcoin", "symbols": ["LOCI"] },
  { "name": "Hawala.Today", "symbols": ["HAT"] },
  { "name": "Block Array", "symbols": ["ARY"] },
  { "name": "aXpire", "symbols": ["AXP"] },
  { "name": "CargoX", "symbols": ["CXO"] },
  { "name": "CoinFi", "symbols": ["COFI"] },
  { "name": "Pareto Network", "symbols": ["PARETO"] },
  { "name": "Bounty0x", "symbols": ["BNTY"] },
  { "name": "Iungo", "symbols": ["ING"] },
  { "name": "adbank", "symbols": ["ADB"] },
  { "name": "Aigang", "symbols": ["AIX"] },
  { "name": "Asch", "symbols": ["XAS"] },
  { "name": "Confido", "symbols": ["CFD"] }
]
