export default [
  { name: "IOTA", symbols: ["IOT", "IOTA", "MIOTA"], cmcId: "iota" },
  { name: "Bitcoin", symbols: ["BTC"], cmcId: "bitcoin" },
  { name: "Ethereum", symbols: ["ETH"], cmcId: "ethereum" },
  { name: "Recently4NEO", symbols: ["NEO"], cmcId: "neo" },
  { name: "TRON", symbols: ["TRX"], cmcId: "tron" },
  {
    name: "Ethereum Classic",
    symbols: ["ETC"],
    cmcId: "ethereum-classic"
  },
  { name: "Gifto", symbols: ["GTO"], cmcId: "gifto" },
  { name: "Ripple", symbols: ["XRP"], cmcId: "ripple" },
  { name: "ICON", symbols: ["ICX"], cmcId: "icon" },
  { name: "Nano", symbols: ["NANO", "XRB"], cmcId: "raiblocks" },
  { name: "Red Pulse", symbols: ["RPX"], cmcId: "red-pulse" },
  { name: "Cardano", symbols: ["ADA"], cmcId: "cardano" },
  { name: "NEO", symbols: ["NEO"], cmcId: "neo" },
  { name: "Agrello", symbols: ["DLT"], cmcId: "agrello-delta" },
  { name: "EOS", symbols: ["EOS"], cmcId: "eos" },
  { name: "Binance Coin", symbols: ["BNB"], cmcId: "binance-coin" },
  { name: "Populous", symbols: ["PPT"], cmcId: "populous" },
  { name: "Po.et", symbols: ["POE"], cmcId: "poet" },
  { name: "Litecoin", symbols: ["LTC"], cmcId: "litecoin" },
  { name: "Hshare", symbols: ["HSR"], cmcId: "hshare" },
  { name: "OAX", symbols: ["OAX"], cmcId: "oax" },
  { name: "VeChain", symbols: ["VEN", "VET"], cmcId: "vechain" },
  { name: "Metal", symbols: ["MTL"], cmcId: "metal" },
  { name: "INS Ecosystem", symbols: ["INS"], cmcId: "ins-ecosystem" },
  { name: "Enigma", symbols: ["ENG", "XNG"], cmcId: "enigma-project" },
  { name: "Stellar", symbols: ["XLM", "STR"], cmcId: "stellar" },
  { name: "Lisk", symbols: ["LSK"], cmcId: "lisk" },
  {
    name: "Bitcoin Cash",
    symbols: ["BCC", "BCH"],
    cmcId: "bitcoin-cash"
  },
  { name: "Modum", symbols: ["MOD"], cmcId: "modum" },
  { name: "Bluzelle", symbols: ["BLZ"], cmcId: "bluzelle" },
  { name: "ChainLink", symbols: ["LINK"], cmcId: "chainlink" },
  { name: "Bread", symbols: ["BRD"], cmcId: "bread" },
  { name: "Kyber Network", symbols: ["KNC"], cmcId: "kyber-network" },
  { name: "IOStoken", symbols: ["IOST"], cmcId: "iostoken" },
  { name: "AdEx", symbols: ["ADX"], cmcId: "adx-net" },
  { name: "Verge", symbols: ["XVG"], cmcId: "verge" },
  { name: "Walton", symbols: ["WTC", "WALTON"], cmcId: "walton" },
  { name: "GXShares", symbols: ["GXS"], cmcId: "gxshares" },
  { name: "AirSwap", symbols: ["AST"], cmcId: "airswap" },
  { name: "Cindicator", symbols: ["CND"], cmcId: "cindicator" },
  { name: "aelf", symbols: ["ELF"], cmcId: "aelf" },
  { name: "Aeron", symbols: ["ARN"], cmcId: "aeron" },
  { name: "OmiseGO", symbols: ["OMG"], cmcId: "omisego" },
  { name: "Stratis", symbols: ["STRAT"], cmcId: "stratis" },
  { name: "Zcash", symbols: ["ZEC"], cmcId: "zcash" },
  { name: "Qtum", symbols: ["QTUM"], cmcId: "qtum" },
  { name: "x", symbols: ["ZRX"], cmcId: "0x" },
  { name: "district0x", symbols: ["DNT"], cmcId: "district0x" },
  { name: "FunFair", symbols: ["FUN"], cmcId: "funfair" },
  { name: "BitShares", symbols: ["BTS"], cmcId: "bitshares" },
  { name: "NAV Coin", symbols: ["NAV"], cmcId: "nav-coin" },
  { name: "DigixDAO", symbols: ["DGD"], cmcId: "digixdao" },
  { name: "Aion", symbols: ["AION"], cmcId: "aion" },
  { name: "Substratum", symbols: ["SUB"], cmcId: "substratum" },
  { name: "Tierion", symbols: ["TNT"], cmcId: "tierion" },
  { name: "Monero", symbols: ["XMR"], cmcId: "monero" },
  { name: "Neblio", symbols: ["NEBL"], cmcId: "neblio" },
  { name: "VIBE", symbols: ["VIBE"], cmcId: "vibe" },
  { name: "Aeternity", symbols: ["AE"], cmcId: "aeternity" },
  { name: "Viberate", symbols: ["VIB"], cmcId: "viberate" },
  {
    name: "BlockMason Credit Protocol",
    symbols: ["BCPT"],
    cmcId: "blockmason"
  },
  { name: "ETHLend", symbols: ["LEND"], cmcId: "ethlend" },
  { name: "Request Network", symbols: ["REQ"], cmcId: "request-network" },
  { name: "Viacoin", symbols: ["VIA"], cmcId: "viacoin" },
  { name: "Bitcoin Gold", symbols: ["BTG"], cmcId: "bitcoin-gold" },
  { name: "Gas", symbols: ["GAS"], cmcId: "gas" },
  { name: "Eidoo", symbols: ["EDO"], cmcId: "eidoo" },
  { name: "Quantstamp", symbols: ["QSP"], cmcId: "quantstamp" },
  { name: "PIVX", symbols: ["PIVX"], cmcId: "pivx" },
  { name: "AppCoins", symbols: ["APPC"], cmcId: "appcoins" },
  { name: "Bitcoin Diamond", symbols: ["BCD"], cmcId: "bitcoin-diamond" },
  { name: "Genesis Vision", symbols: ["GVT"], cmcId: "genesis-vision" },
  { name: "CoinDash", symbols: ["CDT"], cmcId: "coindash" },
  { name: "Monetha", symbols: ["MTH"], cmcId: "monetha" },
  { name: "Nuls", symbols: ["NULS"], cmcId: "nuls" },
  { name: "Power Ledger", symbols: ["POWR"], cmcId: "power-ledger" },
  { name: "Ambrosus", symbols: ["AMB"], cmcId: "amber" },
  { name: "Recently1170x", symbols: ["ZRX"], cmcId: "0x" },
  { name: "SALT", symbols: ["SALT"], cmcId: "salt" },
  { name: "Centra", symbols: ["CTR"], cmcId: "centra" },
  { name: "Time New Bank", symbols: ["TNB"], cmcId: "time-new-bank" },
  { name: "WaBi", symbols: ["WABI"], cmcId: "wabi" },
  { name: "Triggers", symbols: ["TRIG"], cmcId: "triggers" },
  { name: "Dash", symbols: ["DASH", "DSH"], cmcId: "dash" },
  { name: "Everex", symbols: ["EVX"], cmcId: "everex" },
  {
    name: "Decentraland",
    symbols: ["MANA", "MNA"],
    cmcId: "decentraland"
  },
  { name: "Ethos", symbols: ["BQX", "ETHOS"], cmcId: "ethos" },
  { name: "ChatCoin", symbols: ["CHAT"], cmcId: "chatcoin" },
  { name: "Simple Token", symbols: ["OST"], cmcId: "simple-token" },
  { name: "ZCoin", symbols: ["XZC"], cmcId: "zcoin" },
  { name: "Enjin Coin", symbols: ["ENJ"], cmcId: "enjin-coin" },
  { name: "Waves", symbols: ["WAVES"], cmcId: "waves" },
  { name: "Status", symbols: ["SNT"], cmcId: "status" },
  { name: "CyberMiles", symbols: ["CMT"], cmcId: "cybermiles" },
  { name: "YOYOW", symbols: ["YOYO", "YYW", "YOYOW"], cmcId: "yoyow" },
  {
    name: "Raiden Network Token",
    symbols: ["RDN"],
    cmcId: "raiden-network-token"
  },
  { name: "Steem", symbols: ["STEEM"], cmcId: "steem" },
  { name: "Wings", symbols: ["WINGS"], cmcId: "wings" },
  { name: "Monaco", symbols: ["MCO"], cmcId: "monaco" },
  { name: "Storj", symbols: ["STORJ"], cmcId: "storj" },
  {
    name: "Basic Attention Token",
    symbols: ["BAT"],
    cmcId: "basic-attention-token"
  },
  { name: "Lunyr", symbols: ["LUN", "LUNYR"], cmcId: "lunyr" },
  { name: "Komodo", symbols: ["KMD"], cmcId: "komodo" },
  { name: "Bancor", symbols: ["BNT"], cmcId: "bancor" },
  { name: "SONM", symbols: ["SNM"], cmcId: "sonm" },
  { name: "Etherparty", symbols: ["FUEL"], cmcId: "etherparty" },
  {
    name: "SingularDTV",
    symbols: ["SNGLS", "SNG"],
    cmcId: "singulardtv"
  },
  { name: "Loopring", symbols: ["LRC"], cmcId: "loopring" },
  {
    name: "Ripio Credit Network",
    symbols: ["RCN"],
    cmcId: "ripio-credit-network"
  },
  { name: "Ark", symbols: ["ARK"], cmcId: "ark" },
  {
    name: "Moeda Loyalty Points",
    symbols: ["MDA"],
    cmcId: "moeda-loyalty-points"
  },
  { name: "iExec RLC", symbols: ["RLC"], cmcId: "rlc" },
  { name: "Iconomi", symbols: ["ICN"], cmcId: "iconomi" },
  { name: "United Bitcoin", symbols: ["UBTC"], cmcId: "united-bitcoin" },
  { name: "MktCoin", symbols: ["MLM"], cmcId: "mktcoin" },
  { name: "Qbic", symbols: ["QBIC"], cmcId: "qbic" },
  { name: "Polis", symbols: ["POLIS"], cmcId: "polis" },
  { name: "Dogecoin", symbols: ["DOGE"], cmcId: "dogecoin" },
  { name: "NuBits", symbols: ["USNBT", "NBT"], cmcId: "nubits" },
  { name: "GCN Coin", symbols: ["GCN"], cmcId: "gcn-coin" },
  {
    name: "JavaScript Token",
    symbols: ["JS"],
    cmcId: "javascript-token"
  },
  { name: "Phantomx", symbols: ["PNX"], cmcId: "phantomx" },
  { name: "BiblePay", symbols: ["BBP"], cmcId: "biblepay" },
  { name: "Manna", symbols: ["MANNA"], cmcId: "grantcoin" },
  { name: "Mintcoin", symbols: ["MINT"], cmcId: "mintcoin" },
  { name: "Vertcoin", symbols: ["VTC"], cmcId: "vertcoin" },
  { name: "Namecoin", symbols: ["NMC"], cmcId: "namecoin" },
  { name: "XGOX", symbols: ["XGOX"], cmcId: "xgox" },
  { name: "Zeitcoin", symbols: ["ZEIT"], cmcId: "zeitcoin" },
  { name: "BitSend", symbols: ["BSD"], cmcId: "bitsend" },
  { name: "eGold", symbols: ["EGOLD"], cmcId: "egold" },
  { name: "NuShares", symbols: ["NSR"], cmcId: "nushares" },
  { name: "Nxt", symbols: ["NXT"], cmcId: "nxt" },
  { name: "Pesetacoin", symbols: ["PTC"], cmcId: "pesetacoin" },
  { name: "Bata", symbols: ["BTA"], cmcId: "bata" },
  { name: "Denarius", symbols: ["DNR"], cmcId: "denarius-dnr" },
  { name: "Peercoin", symbols: ["PPC"], cmcId: "peercoin" },
  { name: "OceanChain", symbols: ["OC"], cmcId: "oceanchain" },
  { name: "UG Token", symbols: ["UGT"], cmcId: "ug-token" },
  { name: "CFun", symbols: ["CFUN"], cmcId: "cfun" },
  { name: "ACChain", symbols: ["ACC"], cmcId: "acchain" },
  { name: "ATN", symbols: ["ATN"], cmcId: "atn" },
  {
    name: "Profile Utility Token",
    symbols: ["PUT"],
    cmcId: "profile-utility-token"
  },
  { name: "AWARE", symbols: ["AWR"], cmcId: "aware" },
  { name: "HalalChain", symbols: ["HLC"], cmcId: "halalchain" },
  { name: "SpaceChain", symbols: ["SPC"], cmcId: "spacechain" },
  { name: "SIGMAcoin", symbols: ["SIGMA"], cmcId: "sigmacoin" },
  { name: "Bytom", symbols: ["BTM"], cmcId: "bytom" },
  { name: "Ink", symbols: ["INK"], cmcId: "ink" },
  { name: "Energo", symbols: ["TSL"], cmcId: "energo" },
  { name: "Qbao", symbols: ["QBT"], cmcId: "qbao" },
  {
    name: "Internet Node Token",
    symbols: ["INT"],
    cmcId: "internet-node-token"
  },
  { name: "Achain", symbols: ["ACT"], cmcId: "achain" },
  {
    name: "High Performance Blockchain",
    symbols: ["HPB"],
    cmcId: "high-performance-blockchain"
  },
  { name: "Bodhi", symbols: ["BOT"], cmcId: "bodhi" },
  { name: "DeepBrain Chain", symbols: ["DBC"], cmcId: "deepbrain-chain" },
  { name: "Nebulas", symbols: ["NAS"], cmcId: "nebulas-token" },
  { name: "GameCredits", symbols: ["GAME"], cmcId: "gamecredits" },
  { name: "iQuant", symbols: ["IQT"], cmcId: "iquant" },
  { name: "BITFID", symbols: ["FID"], cmcId: "bitfid" },
  { name: "Novacoin", symbols: ["NVC"], cmcId: "novacoin" },
  { name: "NEM", symbols: ["XEM"], cmcId: "nem" },
  { name: "Siacoin", symbols: ["SC"], cmcId: "siacoin" },
  { name: "Factom", symbols: ["FCT"], cmcId: "factom" },
  { name: "Augur", symbols: ["REP"], cmcId: "augur" },
  { name: "0x", symbols: ["ZRX"], cmcId: "0x" },
  { name: "DigiByte", symbols: ["DGB"], cmcId: "digibyte" },
  { name: "Decred", symbols: ["DCR"], cmcId: "decred" },
  { name: "Ardor", symbols: ["ARDR"], cmcId: "ardor" },
  { name: "MaidSafeCoin", symbols: ["MAID"], cmcId: "maidsafecoin" },
  { name: "Bytecoin", symbols: ["BCN"], cmcId: "bytecoin-bcn" },
  { name: "Counterparty", symbols: ["XCP"], cmcId: "counterparty" },
  { name: "Riecoin", symbols: ["RIC"], cmcId: "riecoin" },
  { name: "Bitcrystals", symbols: ["BCY"], cmcId: "bitcrystals" },
  { name: "Golem", symbols: ["GNT"], cmcId: "golem-network-tokens" },
  { name: "Syscoin", symbols: ["SYS"], cmcId: "syscoin" },
  { name: "Einsteinium", symbols: ["EMC2"], cmcId: "einsteinium" },
  { name: "Burst", symbols: ["BURST"], cmcId: "burst" },
  { name: "Synereo", symbols: ["AMP"], cmcId: "synereo" },
  { name: "Civic", symbols: ["CVC"], cmcId: "civic" },
  { name: "NeosCoin", symbols: ["NEOS"], cmcId: "neoscoin" },
  { name: "VeriCoin", symbols: ["VRC"], cmcId: "vericoin" },
  { name: "Pascal Coin", symbols: ["PASC"], cmcId: "pascal-coin" },
  { name: "PotCoin", symbols: ["POT"], cmcId: "potcoin" },
  { name: "Primecoin", symbols: ["XPM"], cmcId: "primecoin" },
  { name: "LBRY Credits", symbols: ["LBC"], cmcId: "library-credit" },
  { name: "Clams", symbols: ["CLAM"], cmcId: "clams" },
  { name: "Omni", symbols: ["OMNI"], cmcId: "omni" },
  { name: "Gnosis", symbols: ["GNO"], cmcId: "gnosis-gno" },
  { name: "Expanse", symbols: ["EXP"], cmcId: "expanse" },
  { name: "Bela", symbols: ["BELA"], cmcId: "belacoin" },
  { name: "PinkCoin", symbols: ["PINK"], cmcId: "pinkcoin" },
  { name: "BlackCoin", symbols: ["BLK"], cmcId: "blackcoin" },
  { name: "Steem Dollars", symbols: ["SBD"], cmcId: "steem-dollars" },
  { name: "Nexium", symbols: ["NXC"], cmcId: "nexium" },
  { name: "Radium", symbols: ["RADS"], cmcId: "radium" },
  { name: "FoldingCoin", symbols: ["FLDC"], cmcId: "foldingcoin" },
  { name: "Bitmark", symbols: ["BTM"], cmcId: "bitmark" },
  { name: "Vcash", symbols: ["XVC"], cmcId: "vcash" },
  { name: "FlorinCoin", symbols: ["FLO"], cmcId: "florincoin" },
  { name: "GridCoin", symbols: ["GRC"], cmcId: "gridcoin" },
  { name: "Bitcoin Plus", symbols: ["XBC"], cmcId: "bitcoin-plus" },
  { name: "BitcoinDark", symbols: ["BTCD"], cmcId: "bitcoindark" },
  { name: "HunterCoin", symbols: ["HUC"], cmcId: "huntercoin" },
  { name: "Bibox Token", symbols: ["BIX"], cmcId: "bibox-token" },
  { name: "Jibrel Network", symbols: ["JNT"], cmcId: "jibrel-network" },
  {
    name: "Spectre.ai Utility Token",
    symbols: ["SXUT"],
    cmcId: "spectre-utility"
  },
  { name: "IoT Chain", symbols: ["ITC"], cmcId: "iot-chain" },
  { name: "CRYPTO20", symbols: ["C20"], cmcId: "c20" },
  { name: "Genaro Network", symbols: ["GNX"], cmcId: "genaro-network" },
  {
    name: "Trinity Network Credit",
    symbols: ["TNC"],
    cmcId: "trinity-network-credit"
  },
  { name: "Change", symbols: ["CAG"], cmcId: "change" },
  { name: "Game.com", symbols: ["GTC"], cmcId: "game" },
  { name: "Olympus Labs", symbols: ["MOT"], cmcId: "olympus-labs" },
  { name: "Doctor", symbols: ["AIDOC"], cmcId: "aidoc" },
  { name: "AI Doctor", symbols: ["AIDOC"], cmcId: "aidoc" },
  { name: "Bloom", symbols: ["BLT"], cmcId: "bloomtoken" },
  { name: "Maker", symbols: ["MKR"], cmcId: "maker" },
  { name: "ProChain", symbols: ["PRA"], cmcId: "prochain" },
  { name: "Snovio", symbols: ["SNOV"], cmcId: "snovio" },
  { name: "MicroMoney", symbols: ["AMM"], cmcId: "micromoney" },
  { name: "WAX", symbols: ["WAX"], cmcId: "wax" },
  { name: "Bottos", symbols: ["BTO"], cmcId: "bottos" },
  { name: "BitClave", symbols: ["CAT"], cmcId: "bitclave" },
  { name: "DATA", symbols: ["DTA"], cmcId: "data" },
  { name: "Show", symbols: ["SHOW"], cmcId: "show" },
  { name: "Super Bitcoin", symbols: ["SBTC"], cmcId: "super-bitcoin" },
  { name: "HTMLCOIN", symbols: ["HTML"], cmcId: "html-coin" },
  { name: "ReddCoin", symbols: ["RDD"], cmcId: "reddcoin" },
  { name: "Mooncoin", symbols: ["MOON"], cmcId: "mooncoin" },
  { name: "FujiCoin", symbols: ["FJC"], cmcId: "fujicoin" },
  { name: "OKCash", symbols: ["OK"], cmcId: "okcash" },
  { name: "Gulden", symbols: ["NLG"], cmcId: "gulden" },
  { name: "Bean Cash", symbols: ["BITB"], cmcId: "bean-cash" },
  { name: "AudioCoin", symbols: ["ADC"], cmcId: "audiocoin" },
  { name: "Unobtanium", symbols: ["UNO"], cmcId: "unobtanium" },
  { name: "MonaCoin", symbols: ["MONA"], cmcId: "monacoin" },
  { name: "Canada eCoin", symbols: ["CDN"], cmcId: "canada-ecoin" },
  { name: "Virtacoinplus", symbols: ["XVP"], cmcId: "virtacoinplus" },
  { name: "DigitalPrice", symbols: ["DP"], cmcId: "digitalprice" },
  { name: "GoldBlocks", symbols: ["GB"], cmcId: "goldblocks" },
  { name: "Startcoin", symbols: ["START"], cmcId: "startcoin" },
  { name: "Digitalcoin", symbols: ["DGC"], cmcId: "digitalcoin" },
  { name: "Zetacoin", symbols: ["ZET"], cmcId: "zetacoin" },
  { name: "SolarCoin", symbols: ["SLR"], cmcId: "solarcoin" },
  { name: "Trollcoin", symbols: ["TROLL"], cmcId: "trollcoin" },
  { name: "GlobalBoost-Y", symbols: ["BSTY"], cmcId: "globalboost-y" },
  { name: "WorldCoin", symbols: ["WDC"], cmcId: "worldcoin" },
  { name: "e-Gulden", symbols: ["EFL"], cmcId: "e-gulden" },
  { name: "Sterlingcoin", symbols: ["SLG"], cmcId: "sterlingcoin" },
  { name: "Primalbase Token", symbols: ["PBT"], cmcId: "primalbase" },
  { name: "TIES Network", symbols: ["TIE"], cmcId: "ties-network" },
  { name: "indaHash", symbols: ["IDH"], cmcId: "indahash" },
  { name: "Kolion", symbols: ["KOLION"], cmcId: "kolion" },
  {
    name: "Waves Community Token",
    symbols: ["WCT"],
    cmcId: "waves-community-token"
  },
  { name: "B2BX", symbols: ["B2B"], cmcId: "b2bx" },
  { name: "ZrCoin", symbols: ["ZRC"], cmcId: "zrcoin" },
  { name: "MSD", symbols: ["MSD"], cmcId: "msd" },
  {
    name: "Titanium Blockchain",
    symbols: ["BAR"],
    cmcId: "titanium-blockchain"
  },
  { name: "Edgeless", symbols: ["EDG"], cmcId: "edgeless" },
  {
    name: "Miners' Reward Token",
    symbols: ["MRT"],
    cmcId: "miners-reward-token"
  },
  { name: "BitDegree", symbols: ["BDG"], cmcId: "bitdegree" },
  { name: "LIFE", symbols: ["LIFE"], cmcId: "life" },
  { name: "SingularityNET", symbols: ["AGI"], cmcId: "singularitynet" },
  { name: "Tracto", symbols: ["TRCT"], cmcId: "tracto" },
  { name: "BLOCKv", symbols: ["VEE"], cmcId: "blockv" },
  { name: "Selfkey", symbols: ["KEY"], cmcId: "selfkey" },
  { name: "Wagerr", symbols: ["WGR"], cmcId: "wagerr" },
  {
    name: "SIRIN LABS Token",
    symbols: ["SRN"],
    cmcId: "sirin-labs-token"
  },
  { name: "Starta", symbols: ["STA"], cmcId: "starta" },
  { name: "Dragonchain", symbols: ["DRGN"], cmcId: "dragonchain" },
  { name: "Credo", symbols: ["CREDO"], cmcId: "credo" },
  { name: "ANRYZE", symbols: ["RYZ"], cmcId: "anryze" },
  { name: "Bowhead", symbols: ["AHT"], cmcId: "bowhead" },
  { name: "InPay", symbols: ["INPAY"], cmcId: "inpay" },
  { name: "MobileGo", symbols: ["MGO", "EMGO"], cmcId: "mobilego" },
  { name: "CryptoPing", symbols: ["PING"], cmcId: "cryptoping" },
  { name: "Suretly", symbols: ["SUR"], cmcId: "suretly" },
  { name: "EOT Token", symbols: ["EOT"], cmcId: "eot-token" },
  { name: "Mercury", symbols: ["MER"], cmcId: "mercury" },
  { name: "Oceanlab", symbols: ["OCL"], cmcId: "oceanlab" },
  { name: "Blackmoon", symbols: ["BMC"], cmcId: "blackmoon" },
  { name: "Incent", symbols: ["INCNT"], cmcId: "incent" },
  { name: "Paragon", symbols: ["PRG"], cmcId: "paragon" },
  { name: "Ripto Bux", symbols: ["RBX"], cmcId: "ripto-bux" },
  { name: "Chronobank", symbols: ["TIME"], cmcId: "chronobank" },
  { name: "Bankcoin", symbols: ["B@"], cmcId: "bankcoin" },
  { name: "ICOS", symbols: ["ICOS"], cmcId: "icos" },
  { name: "Trade Token", symbols: ["TIO"], cmcId: "trade-token" },
  { name: "WavesGo", symbols: ["WGO"], cmcId: "wavesgo" },
  {
    name: "Quantum Resistant Ledger",
    symbols: ["QRL"],
    cmcId: "quantum-resistant-ledger"
  },
  { name: "Tether", symbols: ["USDT"], cmcId: "tether" },
  {
    name: "Santiment Network Token",
    symbols: ["SAN"],
    cmcId: "santiment"
  },
  { name: "Metaverse ETP", symbols: ["ETP"], cmcId: "metaverse" },
  { name: "QASH", symbols: ["QSH", "QASH"], cmcId: "qash" },
  {
    name: "Streamr DATAcoin",
    symbols: ["DATA"],
    cmcId: "streamr-datacoin"
  },
  { name: "AidCoin", symbols: ["AID"], cmcId: "aidcoin" },
  { name: "SpankChain", symbols: ["SPK", "SPANK"], cmcId: "spankchain" },
  { name: "Aventus", symbols: ["AVT"], cmcId: "aventus" },
  { name: "Medicalchain", symbols: ["MTN"], cmcId: "medical-chain" },
  { name: "SophiaTX", symbols: ["SPHTX"], cmcId: "sophiatx" },
  { name: "Vezt", symbols: ["VZT"], cmcId: "vezt" },
  { name: "onG.social", symbols: ["ONG"], cmcId: "ongsocial" },
  { name: "CanYaCoin", symbols: ["CAN"], cmcId: "canyacoin" },
  { name: "FidentiaX", symbols: ["FDX"], cmcId: "fidentiax" },
  { name: "Dent", symbols: ["DENT"], cmcId: "dent" },
  { name: "Gatcoin", symbols: ["GAT"], cmcId: "gatcoin" },
  { name: "Stox", symbols: ["STX"], cmcId: "stox" },
  { name: "Indorse Token", symbols: ["IND"], cmcId: "indorse-token" },
  { name: "iXledger", symbols: ["IXT"], cmcId: "ixledger" },
  { name: "Rise", symbols: ["RISE"], cmcId: "rise" },
  { name: "ZClassic", symbols: ["ZCL"], cmcId: "zclassic" },
  { name: "Humaniq", symbols: ["HMQ"], cmcId: "humaniq" },
  { name: "Syndicate", symbols: ["SYNX"], cmcId: "syndicate" },
  { name: "Ignis", symbols: ["IGNIS"], cmcId: "ignis" },
  { name: "ION", symbols: ["ION"], cmcId: "ion" },
  { name: "Voxels", symbols: ["VOX"], cmcId: "voxels" },
  { name: "Numeraire", symbols: ["NMR"], cmcId: "numeraire" },
  { name: "TenX", symbols: ["PAY"], cmcId: "tenx" },
  { name: "ZenCash", symbols: ["ZEN"], cmcId: "zencash" },
  { name: "Shift", symbols: ["SHIFT"], cmcId: "shift" },
  { name: "Crown", symbols: ["CRW"], cmcId: "crown" },
  { name: "adToken", symbols: ["ADT"], cmcId: "adtoken" },
  { name: "Blocknet", symbols: ["BLOCK"], cmcId: "blocknet" },
  { name: "Unikoin Gold", symbols: ["UKG"], cmcId: "unikoin-gold" },
  { name: "GeoCoin", symbols: ["GEO"], cmcId: "geocoin" },
  { name: "Golos", symbols: ["GOLOS"], cmcId: "golos" },
  { name: "Aragon", symbols: ["ANT"], cmcId: "aragon" },
  { name: "Cofound.it", symbols: ["CFI"], cmcId: "cofound-it" },
  { name: "BitBay", symbols: ["BAY"], cmcId: "bitbay" },
  { name: "Byteball Bytes", symbols: ["GBYTE"], cmcId: "byteball" },
  { name: "Nexus", symbols: ["NXS"], cmcId: "nexus" },
  { name: "ExclusiveCoin", symbols: ["EXCL"], cmcId: "exclusivecoin" },
  {
    name: "FirstBlood",
    symbols: ["1ST", "FirstBlood"],
    cmcId: "firstblood"
  },
  { name: "Matchpool", symbols: ["GUP"], cmcId: "guppy" },
  { name: "Blocktix", symbols: ["TIX"], cmcId: "blocktix" },
  { name: "Groestlcoin", symbols: ["GRS"], cmcId: "groestlcoin" },
  { name: "Ubiq", symbols: ["UBQ"], cmcId: "ubiq" },
  { name: "HempCoin", symbols: ["THC", "HMP"], cmcId: "hempcoin" },
  { name: "Sphere", symbols: ["SPHR"], cmcId: "sphere" },
  { name: "Recently123I/O", symbols: ["IOC"], cmcId: "iocoin" },
  { name: "Swarm City", symbols: ["SWT"], cmcId: "swarm-city" },
  { name: "Aeon", symbols: ["AEON"], cmcId: "aeon" },
  { name: "", symbols: ["MEME", "QTUM"], cmcId: "memetic" },
  { name: "Bitswift", symbols: ["SWIFT"], cmcId: "bitswift" },
  { name: "Patientory", symbols: ["PTOY"], cmcId: "patientory" },
  {
    name: "Internet of People",
    symbols: ["IOP"],
    cmcId: "internet-of-people"
  },
  { name: "UnbreakableCoin", symbols: ["UNB"], cmcId: "unbreakablecoin" },
  { name: "Emercoin", symbols: ["EMC"], cmcId: "emercoin" },
  { name: "TransferCoin", symbols: ["TX"], cmcId: "transfercoin" },
  { name: "Particl", symbols: ["PART"], cmcId: "particl" },
  { name: "Elastic", symbols: ["XEL"], cmcId: "elastic" },
  { name: "LoMoCoin", symbols: ["LMC"], cmcId: "lomocoin" },
  { name: "Agoras Tokens", symbols: ["AGRS"], cmcId: "agoras-tokens" },
  { name: "EuropeCoin", symbols: ["ERC"], cmcId: "europecoin" },
  {
    name: "Circuits of Value",
    symbols: ["COVAL"],
    cmcId: "circuits-of-value"
  },
  { name: "MonetaryUnit", symbols: ["MUE"], cmcId: "monetaryunit" },
  { name: "SaluS", symbols: ["SLS"], cmcId: "salus" },
  { name: "WeTrust", symbols: ["TRST"], cmcId: "trust" },
  { name: "CloakCoin", symbols: ["CLOAK"], cmcId: "cloakcoin" },
  { name: "ClubCoin", symbols: ["CLUB"], cmcId: "clubcoin" },
  { name: "DECENT", symbols: ["DCT"], cmcId: "decent" },
  { name: "Auroracoin", symbols: ["AUR"], cmcId: "auroracoin" },
  { name: "eBoost", symbols: ["EBST"], cmcId: "eboostcoin" },
  { name: "Kore", symbols: ["KORE"], cmcId: "korecoin" },
  { name: "Capricoin", symbols: ["CPC"], cmcId: "capricoin" },
  { name: "Dynamic", symbols: ["DYN"], cmcId: "dynamic" },
  { name: "ParkByte", symbols: ["PKB"], cmcId: "parkbyte" },
  { name: "Musicoin", symbols: ["MUSIC"], cmcId: "musicoin" },
  {
    name: "Global Currency Reserve",
    symbols: ["GCR"],
    cmcId: "global-currency-reserve"
  },
  { name: "Golos Gold", symbols: ["GBG"], cmcId: "golos-gold" },
  { name: "Feathercoin", symbols: ["FTC"], cmcId: "feathercoin" },
  { name: "Creditbit", symbols: ["CRB", "CRBIT"], cmcId: "creditbit" },
  { name: "VeriumReserve", symbols: ["VRM"], cmcId: "veriumreserve" },
  { name: "DopeCoin", symbols: ["DOPE"], cmcId: "dopecoin" },
  { name: "Myriad", symbols: ["XMY"], cmcId: "myriad" },
  { name: "Bytecent", symbols: ["BYC"], cmcId: "bytecent" },
  { name: "Sequence", symbols: ["SEQ"], cmcId: "sequence" },
  { name: "WhiteCoin", symbols: ["XWC"], cmcId: "whitecoin" },
  { name: "SpreadCoin", symbols: ["SPR"], cmcId: "spreadcoin" },
  { name: "Curecoin", symbols: ["CURE"], cmcId: "curecoin" },
  { name: "Melon", symbols: ["MLN"], cmcId: "melon" },
  { name: "GoldCoin", symbols: ["GLD"], cmcId: "goldcoin" },
  { name: "CannabisCoin", symbols: ["CANN"], cmcId: "cannabiscoin" },
  { name: "Blitzcash", symbols: ["BLITZ"], cmcId: "blitzcash" },
  { name: "vTorrent", symbols: ["VTR"], cmcId: "vtorrent" },
  { name: "SIBCoin", symbols: ["SIB"], cmcId: "sibcoin" },
  { name: "ArtByte", symbols: ["ABY"], cmcId: "artbyte" },
  { name: "Synergy", symbols: ["SNRG"], cmcId: "synergy" },
  { name: "Magi", symbols: ["XMG"], cmcId: "magi" },
  { name: "Legends Room", symbols: ["LGD"], cmcId: "legends-room" },
  { name: "Qwark", symbols: ["QWARK"], cmcId: "qwark" },
  { name: "Breakout Stake", symbols: ["BRX"], cmcId: "breakout-stake" },
  { name: "Project Decorum", symbols: ["PDC"], cmcId: "project-decorum" },
  { name: "Energycoin", symbols: ["ENRG"], cmcId: "energycoin" },
  { name: "EverGreenCoin", symbols: ["EGC"], cmcId: "evergreencoin" },
  { name: "FairCoin", symbols: ["FAIR"], cmcId: "faircoin" },
  { name: "Breakout", symbols: ["BRK"], cmcId: "breakout" },
  { name: "Diamond", symbols: ["DMD"], cmcId: "diamond" },
  { name: "Influxcoin", symbols: ["INFX"], cmcId: "influxcoin" },
  { name: "Rubycoin", symbols: ["RBY"], cmcId: "rubycoin" },
  { name: "Stealthcoin", symbols: ["XST"], cmcId: "stealthcoin" },
  { name: "GIVE", symbols: ["2GIVE"], cmcId: "2give" },
  { name: "Gambit", symbols: ["GAM"], cmcId: "gambit" },
  { name: "Databits", symbols: ["DTB"], cmcId: "databits" },
  { name: "TrustPlus", symbols: ["TRUST"], cmcId: "trustplus" },
  { name: "Tokes", symbols: ["TKS"], cmcId: "tokes" },
  { name: "Nimiq", symbols: ["NET"], cmcId: "nimiq" },
  { name: "TaaS", symbols: ["TAAS"], cmcId: "taas" },
  { name: "Neumark", symbols: ["NEU"], cmcId: "neumark" },
  { name: "TokenCard", symbols: ["TKN"], cmcId: "tokencard" },
  { name: "Propy", symbols: ["PRO", "PROPY"], cmcId: "propy" },
  { name: "Mysterium", symbols: ["MYST"], cmcId: "mysterium" },
  { name: "Sphre AIR", symbols: ["XID"], cmcId: "sphre-air" },
  { name: "vSlice", symbols: ["VSL", "VSLICE"], cmcId: "vslice" },
  { name: "Pluton", symbols: ["PLU"], cmcId: "pluton" },
  { name: "BCAP", symbols: ["BCAP"], cmcId: "bcap" },
  { name: "MarteXcoin", symbols: ["MXT"], cmcId: "martexcoin" },
  { name: "KickCoin", symbols: ["KICK"], cmcId: "kickico" },
  { name: "LockChain", symbols: ["LOC"], cmcId: "lockchain" },
  { name: "REAL", symbols: ["REA"], cmcId: "real" },
  { name: "Lampix", symbols: ["PIX"], cmcId: "lampix" },
  { name: "Dai", symbols: ["DAI"], cmcId: "dai" },
  { name: "HelloGold", symbols: ["HGT"], cmcId: "hellogold" },
  { name: "InvestFeed", symbols: ["IFT"], cmcId: "investfeed" },
  { name: "$0$0.9240400.00%", symbols: ["WINGS"], cmcId: "wings" },
  { name: "$0$1.340.00%Recently", symbols: ["ZRX"], cmcId: "0x" },
  { name: "Cobinhood", symbols: ["COB"], cmcId: "cobinhood" },
  { name: "NAGA", symbols: ["NGC"], cmcId: "naga" },
  { name: "STK", symbols: ["STK"], cmcId: "stk" },
  { name: "Odyssey", symbols: ["OCN"], cmcId: "odyssey" },
  { name: "Voise", symbols: ["VOISE"], cmcId: "voisecom" },
  {
    name: "COMSA",
    symbols: ["CMS.ETH", "CMS.XEM", "CMS"],
    cmcId: "[ETH] comsa-eth"
  },
  { name: "Pepe Cash", symbols: ["PEPECASH"], cmcId: "pepe-cash" },
  { name: "Storjcoin X", symbols: ["SJCX"], cmcId: "storjcoin-x" },
  { name: "Huobi Token", symbols: ["HT"], cmcId: "huobi-token" },
  { name: "Elastos", symbols: ["ELA"], cmcId: "elastos" },
  { name: "WaykiChain", symbols: ["WICC"], cmcId: "waykichain" },
  { name: "QunQun", symbols: ["QUN"], cmcId: "qunqun" },
  { name: "Zilliqa", symbols: ["ZIL"], cmcId: "zilliqa" },
  { name: "TopChain", symbols: ["TOPC"], cmcId: "topchain" },
  { name: "Theta Token", symbols: ["THETA"], cmcId: "theta-token" },
  { name: "Ruff", symbols: ["RUFF"], cmcId: "ruff" },
  { name: "All Sports", symbols: ["SOC"], cmcId: "all-sports" },
  { name: "LinkEye", symbols: ["LET"], cmcId: "linkeye" },
  { name: "WePower", symbols: ["WPR"], cmcId: "wepower" },
  { name: "MediShares", symbols: ["MDS"], cmcId: "medishares" },
  { name: "Zilla", symbols: ["ZLA"], cmcId: "zilla" },
  { name: "SmartMesh", symbols: ["SMT"], cmcId: "smartmesh" },
  { name: "CoinMeet", symbols: ["MEE"], cmcId: "coinmeet" },
  { name: "Matryx", symbols: ["MTX"], cmcId: "matryx" },
  { name: "SunContract", symbols: ["SNC"], cmcId: "suncontract" },
  { name: "UTRUST", symbols: ["UTK"], cmcId: "utrust" },
  { name: "Yee", symbols: ["YEE"], cmcId: "yee" },
  { name: "EchoLink", symbols: ["EKO"], cmcId: "echolink" },
  { name: "SwftCoin", symbols: ["SWFTC"], cmcId: "swftcoin" },
  { name: "Datum", symbols: ["DAT"], cmcId: "datum" },
  { name: "BitcoinX", symbols: ["BCX"], cmcId: "bitcoinx" },
  {
    name: "Russian Miner Coin",
    symbols: ["RMC"],
    cmcId: "russian-mining-coin"
  },
  { name: "Revain", symbols: ["R"], cmcId: "revain" },
  { name: "Everus", symbols: ["EVR"], cmcId: "everus" },
  { name: "Fortuna", symbols: ["FOTA"], cmcId: "fortuna" },
  { name: "Zeepin", symbols: ["ZPT"], cmcId: "zeepin" },
  { name: "THEKEY", symbols: ["TKY"], cmcId: "thekey" },
  { name: "Oyster", symbols: ["PRL"], cmcId: "oyster" },
  { name: "KuCoin Shares", symbols: ["KCS"], cmcId: "kucoin-shares" },
  { name: "BOScoin", symbols: ["BOS"], cmcId: "boscoin" },
  { name: "Telcoin", symbols: ["TEL"], cmcId: "telcoin" },
  { name: "QLINK", symbols: ["QLC"], cmcId: "qlink" },
  { name: "RChain", symbols: ["RHOC"], cmcId: "rchain" },
  { name: "carVertical", symbols: ["CV"], cmcId: "carvertical" },
  {
    name: "Pareto Network",
    symbols: ["PARETO"],
    cmcId: "pareto-network"
  },
  { name: "Hawala.Today", symbols: ["HAT"], cmcId: "hawala-today" },
  { name: "LAToken", symbols: ["LA"], cmcId: "latoken" },
  { name: "ClearPoll", symbols: ["POLL"], cmcId: "clearpoll" },
  { name: "LOCIcoin", symbols: ["LOCI"], cmcId: "locicoin" },
  { name: "CargoX", symbols: ["CXO"], cmcId: "cargox" },
  { name: "Decision Token", symbols: ["HST"], cmcId: "decision-token" },
  { name: "CoinFi", symbols: ["COFI"], cmcId: "coinfi" },
  { name: "Solaris", symbols: ["XLR"], cmcId: "solaris" },
  { name: "Block Array", symbols: ["ARY"], cmcId: "block-array" },
  { name: "Bounty0x", symbols: ["BNTY"], cmcId: "bounty0x" },
  { name: "aXpire", symbols: ["AXP"], cmcId: "axpire" },
  { name: "adbank", symbols: ["ADB"], cmcId: "adbank" },
  { name: "Iungo", symbols: ["ING"], cmcId: "iungo" },
  { name: "Elixir", symbols: ["ELIX"], cmcId: "elixir" },
  { name: "DeepOnion", symbols: ["ONION"], cmcId: "deeponion" },
  { name: "EncrypGen", symbols: ["DNA"], cmcId: "encrypgen" },
  { name: "Asch", symbols: ["XAS"], cmcId: "asch" },
  { name: "Aigang", symbols: ["AIX"], cmcId: "aigang" },
  { name: "Publica", symbols: ["PBL"], cmcId: "publica" },
  { name: "Flixxo", symbols: ["FLIXX"], cmcId: "flixxo" },
  { name: "Pura", symbols: ["PURA"], cmcId: "pura" },
  { name: "eBitcoin", symbols: ["EBTC", "EBTCNEW"], cmcId: "ebtcnew" },
  { name: "TrueFlip", symbols: ["TFL"], cmcId: "trueflip" },
  { name: "Confido", symbols: ["CFD"], cmcId: "confido" },
  { name: "Electroneum", symbols: ["ETN"], cmcId: "electroneum" },
  { name: "Bitcore", symbols: ["BTX"], cmcId: "bitcore" },
  { name: "Ormeus Coin", symbols: ["ORME"], cmcId: "ormeus-coin" },
  { name: "LUXCoin", symbols: ["LUX"], cmcId: "luxcoin" },
  { name: "WINCOIN", symbols: ["WC"], cmcId: "win-coin" },
  { name: "Cream", symbols: ["CRM"], cmcId: "cream" },
  { name: "GoByte", symbols: ["GBX"], cmcId: "gobyte" },
  { name: "GrandCoin", symbols: ["GDC"], cmcId: "grandcoin" },
  { name: "Cappasity", symbols: ["CAPP"], cmcId: "cappasity" },
  { name: "Pioneer Coin", symbols: ["PCOIN"], cmcId: "pioneer-coin" },
  { name: "XTRABYTES", symbols: ["XBY"], cmcId: "xtrabytes" },
  { name: "Numus", symbols: ["NMS"], cmcId: "numus" },
  { name: "Dotcoin", symbols: ["DOT"], cmcId: "dotcoin" },
  {
    name: "CryptopiaFeeShares",
    symbols: ["CEFS"],
    cmcId: "cryptopiafeeshares"
  },
  { name: "Pillar", symbols: ["PLR"], cmcId: "pillar" },
  { name: "Neutron", symbols: ["NTRN"], cmcId: "neutron" },
  { name: "Hush", symbols: ["HUSH"], cmcId: "hush" },
  { name: "Dinastycoin", symbols: ["DCY"], cmcId: "dinastycoin" },
  { name: "Mothership", symbols: ["MSP"], cmcId: "mothership" },
  { name: "Skycoin", symbols: ["SKY"], cmcId: "skycoin" },
  { name: "HomeBlockCoin", symbols: ["HBC"], cmcId: "homeblockcoin" },
  { name: "CrowdCoin", symbols: ["CRC"], cmcId: "crowdcoin" },
  { name: "Innova", symbols: ["INN"], cmcId: "innova" },
  { name: "Linda", symbols: ["LINDA"], cmcId: "linda" },
  { name: "Phore", symbols: ["PHR"], cmcId: "phore" },
  { name: "Bulwark", symbols: ["BWK"], cmcId: "bulwark" },
  { name: "SagaCoin", symbols: ["SAGA"], cmcId: "sagacoin" },
  { name: "Divi", symbols: ["DIVX"], cmcId: "divi" },
  { name: "Obsidian", symbols: ["ODN"], cmcId: "obsidian" },
  { name: "BlockCAT", symbols: ["BKCAT"], cmcId: "blockcat" },
  { name: "DubaiCoin", symbols: ["DBIX"], cmcId: "dubaicoin-dbix" },
  { name: "Dentacoin", symbols: ["DCN"], cmcId: "dentacoin" },
  { name: "DecentBet", symbols: ["DBET"], cmcId: "decent-bet" },
  { name: "Monkey Project", symbols: ["MONK"], cmcId: "monkey-project" },
  { name: "Flash", symbols: ["FLASH"], cmcId: "flash" },
  { name: "Tokugawa", symbols: ["TOK"], cmcId: "tokugawa" },
  {
    name: "Royal Kingdom Coin",
    symbols: ["RKC"],
    cmcId: "royal-kingdom-coin"
  },
  { name: "CampusCoin", symbols: ["CMPCO"], cmcId: "campuscoin" },
  { name: "Pirl", symbols: ["PIRL"], cmcId: "pirl" },
  { name: "PoSW Coin", symbols: ["POSW"], cmcId: "posw-coin" },
  { name: "AdShares", symbols: ["ADST"], cmcId: "adshares" },
  { name: "Zoin", symbols: ["ZOI"], cmcId: "zoin" },
  { name: "Monoeci", symbols: ["XMCC"], cmcId: "monacocoin" },
  { name: "OP Coin", symbols: ["OPC"], cmcId: "op-coin" },
  { name: "Spectrecoin", symbols: ["XSPEC"], cmcId: "spectrecoin" },
  { name: "InsaneCoin", symbols: ["INSN"], cmcId: "insanecoin-insn" },
  { name: "Sumokoin", symbols: ["SUMO"], cmcId: "sumokoin" },
  { name: "StrikeBitClub", symbols: ["SBC"], cmcId: "strikebitclub" },
  { name: "VIVO", symbols: ["VIVO"], cmcId: "vivo" },
  { name: "DCORP", symbols: ["DRP"], cmcId: "dcorp" },
  { name: "BestChain", symbols: ["BEST"], cmcId: "bestchain" },
  { name: "MyWish", symbols: ["WISH"], cmcId: "mywish" },
  { name: "ProCurrency", symbols: ["PROC"], cmcId: "procurrency" },
  { name: "Embers", symbols: ["MBRS"], cmcId: "embers" },
  { name: "Zap", symbols: ["ZAP"], cmcId: "zap" },
  { name: "DigiPulse", symbols: ["DGPT"], cmcId: "digipulse" },
  { name: "DRP Utility", symbols: ["DRPU"], cmcId: "drp-utility" },
  { name: "Pandacoin", symbols: ["PND"], cmcId: "pandacoin-pnd" },
  { name: "Zero", symbols: ["ZER"], cmcId: "zero" },
  { name: "CoinonatX", symbols: ["XCXT"], cmcId: "coinonatx" },
  { name: "MyBit Token", symbols: ["MYB"], cmcId: "mybit-token" },
  {
    name: "Universal Currency",
    symbols: ["UNIT"],
    cmcId: "universal-currency"
  },
  {
    name: "Interstellar Holdings",
    symbols: ["HOLD"],
    cmcId: "interstellar-holdings"
  },
  { name: "DFSCoin", symbols: ["DFS"], cmcId: "dfscoin" },
  { name: "Linx", symbols: ["LINX"], cmcId: "linx" },
  { name: "Bonpay", symbols: ["BON", "BONPAY"], cmcId: "bonpay" },
  { name: "Photon", symbols: ["PHO"], cmcId: "photon" },
  { name: "ALIS", symbols: ["ALIS"], cmcId: "alis" },
  { name: "Rupee", symbols: ["RUP"], cmcId: "rupee" },
  { name: "Social Send", symbols: ["SEND"], cmcId: "social-send" },
  { name: "NoLimitCoin", symbols: ["NLC2"], cmcId: "nolimitcoin" },
  { name: "TeslaCoin", symbols: ["TES"], cmcId: "teslacoin" },
  { name: "Ellaism", symbols: ["ELLA"], cmcId: "ellaism" },
  { name: "FuelCoin", symbols: ["FUEL"], cmcId: "fuelcoin" },
  { name: "Wild Crypto", symbols: ["WILD"], cmcId: "wild-crypto" },
  { name: "PACcoin", symbols: ["PAC"], cmcId: "paccoin" },
  { name: "Bitcloud", symbols: ["BTDX"], cmcId: "bitcloud" },
  { name: "ChainCoin", symbols: ["CHC"], cmcId: "chaincoin" },
  { name: "LeviarCoin", symbols: ["XLC"], cmcId: "leviarcoin" },
  { name: "APX", symbols: ["APX"], cmcId: "apx" },
  { name: "Ethereum Dark", symbols: ["ETHD"], cmcId: "ethereum-dark" },
  { name: "Kubera Coin", symbols: ["KBR"], cmcId: "kubera-coin" },
  { name: "Dimecoin", symbols: ["DIME"], cmcId: "dimecoin" },
  { name: "TajCoin", symbols: ["TAJ"], cmcId: "tajcoin" },
  { name: "EquiTrader", symbols: ["EQT"], cmcId: "equitrader" },
  { name: "Copico", symbols: ["XCPO"], cmcId: "copico" },
  { name: "Steneum Coin", symbols: ["STN"], cmcId: "steneum-coin" },
  { name: "Upfiring", symbols: ["UFR"], cmcId: "upfiring" },
  { name: "TerraNova", symbols: ["TER"], cmcId: "terranova" },
  { name: "AsiaCoin", symbols: ["AC"], cmcId: "asiacoin" },
  { name: "Karbo", symbols: ["KRB"], cmcId: "karbowanec" },
  { name: "Halcyon", symbols: ["HAL"], cmcId: "halcyon" },
  { name: "Atomic Coin", symbols: ["ATOM"], cmcId: "atomic-coin" },
  { name: "Cryptojacks", symbols: ["CJ"], cmcId: "cryptojacks" },
  { name: "Unify", symbols: ["UNIFY"], cmcId: "unify" },
  { name: "Altcoin", symbols: ["ALT"], cmcId: "altcoin-alt" },
  { name: "Creativecoin", symbols: ["CREA"], cmcId: "creativecoin" },
  { name: "LanaCoin", symbols: ["LANA"], cmcId: "lanacoin" },
  { name: "Condensate", symbols: ["RAIN"], cmcId: "condensate" },
  {
    name: "Harvest Masternode Coin",
    symbols: ["HC"],
    cmcId: "harvest-masternode-coin"
  },
  { name: "TrezarCoin", symbols: ["TZC"], cmcId: "trezarcoin" },
  { name: "Rimbit", symbols: ["RBT"], cmcId: "rimbit" },
  { name: "Elite", symbols: ["1337"], cmcId: "1337coin" },
  { name: "Terracoin", symbols: ["TRC"], cmcId: "terracoin" },
  { name: "VapersCoin", symbols: ["VPRC"], cmcId: "vaperscoin" },
  { name: "Skeincoin", symbols: ["SKC"], cmcId: "skeincoin" },
  { name: "Quatloo", symbols: ["QTL"], cmcId: "quatloo" },
  { name: "iTicoin", symbols: ["ITI"], cmcId: "iticoin" },
  { name: "Moin", symbols: ["MOIN"], cmcId: "moin" },
  { name: "Atmos", symbols: ["ATMS"], cmcId: "atmos" },
  { name: "ToaCoin", symbols: ["TOA"], cmcId: "toacoin" },
  { name: "SkinCoin", symbols: ["SKIN"], cmcId: "skincoin" },
  { name: "AdCoin", symbols: ["ACC"], cmcId: "adcoin" },
  { name: "HEAT", symbols: ["HEAT"], cmcId: "heat-ledger" },
  {
    name: "Growers International",
    symbols: ["GRWI"],
    cmcId: "growers-international"
  },
  { name: "IncaKoin", symbols: ["NKA"], cmcId: "incakoin" },
  { name: "TEKcoin", symbols: ["TEK"], cmcId: "tekcoin" },
  { name: "Bitradio", symbols: ["BRO"], cmcId: "bitradio" },
  { name: "CompuCoin", symbols: ["CPN"], cmcId: "compucoin" },
  { name: "808Coin", symbols: ["808"], cmcId: "808coin" },
  { name: "Bitdeal", symbols: ["BDL"], cmcId: "bitdeal" },
  { name: "NobleCoin", symbols: ["NOBL"], cmcId: "noblecoin" },
  { name: "NevaCoin", symbols: ["NEVA"], cmcId: "nevacoin" },
  { name: "MAZA", symbols: ["MZC"], cmcId: "mazacoin" },
  { name: "CannaCoin", symbols: ["CCN"], cmcId: "cannacoin" },
  { name: "GPU Coin", symbols: ["GPU"], cmcId: "gpu-coin" },
  { name: "PutinCoin", symbols: ["PUT"], cmcId: "putincoin" },
  { name: "Allion", symbols: ["ALL"], cmcId: "allion" },
  {
    name: "Open Trading Network",
    symbols: ["OTN"],
    cmcId: "open-trading-network"
  },
  { name: "Unitus", symbols: ["UIS"], cmcId: "unitus" },
  { name: "LiteDoge", symbols: ["LDOGE"], cmcId: "litedoge" },
  { name: "KlondikeCoin", symbols: ["KDC"], cmcId: "klondikecoin" },
  { name: "Fonziecoin", symbols: ["FONZ"], cmcId: "fonziecoin" },
  { name: "Royalties", symbols: ["XRY"], cmcId: "royalties" },
  { name: "PopularCoin", symbols: ["POP"], cmcId: "popularcoin" },
  { name: "ArcticCoin", symbols: ["ARC", "ARCX"], cmcId: "arcticcoin" },
  { name: "MagicCoin", symbols: ["MAGE"], cmcId: "magiccoin" },
  { name: "Soma", symbols: ["SCT"], cmcId: "soma" },
  { name: "Pascal Lite", symbols: ["PASL"], cmcId: "pascal-lite" },
  { name: "Fastcoin", symbols: ["FST"], cmcId: "fastcoin" },
  { name: "SecureCoin", symbols: ["SRC"], cmcId: "securecoin" },
  { name: "Prototanium", symbols: ["PR"], cmcId: "prototanium" },
  { name: "LeaCoin", symbols: ["LEA"], cmcId: "leacoin" },
  { name: "Footy Cash", symbols: ["XFT"], cmcId: "footy-cash" },
  { name: "OX Fina", symbols: ["OX"], cmcId: "ox-fina" },
  { name: "Argus", symbols: ["ARGUS"], cmcId: "argus" },
  { name: "Solarflarecoin", symbols: ["SFC"], cmcId: "solarflarecoin" },
  {
    name: "LiteBitcoin",
    symbols: ["LBTC", "LBTCX"],
    cmcId: "litebitcoin"
  },
  { name: "DROXNE", symbols: ["DRXNE"], cmcId: "droxne" },
  { name: "Recently248Memetic", symbols: ["PEPE"], cmcId: "memetic" },
  { name: "Social", symbols: ["SCL"], cmcId: "social" },
  { name: "CoffeeCoin", symbols: ["CFC"], cmcId: "coffeecoin" },
  {
    name: "Billionaire Token",
    symbols: ["XBL"],
    cmcId: "billionaire-token"
  },
  { name: "Cannation", symbols: ["CNNC"], cmcId: "cannation" },
  { name: "ChessCoin", symbols: ["CHESS"], cmcId: "chesscoin" },
  { name: "Eryllium", symbols: ["ERY"], cmcId: "eryllium" },
  { name: "HyperStake", symbols: ["HYP"], cmcId: "hyperstake" },
  { name: "PetroDollar", symbols: ["XPD"], cmcId: "petrodollar" },
  { name: "DaxxCoin", symbols: ["DAXX"], cmcId: "daxxcoin" },
  { name: "Bitcoin Scrypt", symbols: ["BTCS"], cmcId: "bitcoin-scrypt" },
  { name: "Guncoin", symbols: ["GUN"], cmcId: "guncoin" },
  { name: "TittieCoin", symbols: ["TTC"], cmcId: "tittiecoin" },
  { name: "Masternodecoin", symbols: ["MTNC"], cmcId: "masternodecoin" },
  {
    name: "DigitalDevelopersFund",
    symbols: ["DDF"],
    cmcId: "digital-developers-fund"
  },
  { name: "WeAreSatoshi", symbols: ["WSX"], cmcId: "wearesatoshi" },
  { name: "Argentum", symbols: ["ARG"], cmcId: "argentum" },
  { name: "Phoenixcoin", symbols: ["PXC"], cmcId: "phoenixcoin" },
  { name: "Megacoin", symbols: ["MEC"], cmcId: "megacoin" },
  { name: "42-coin", symbols: ["42", "FORTYTWO"], cmcId: "42-coin" },
  { name: "PlexCoin", symbols: ["PLX"], cmcId: "plexcoin" },
  { name: "OctoCoin", symbols: ["888"], cmcId: "octocoin" },
  { name: "BlazeCoin", symbols: ["BLZ"], cmcId: "blazecoin" },
  { name: "Minereum", symbols: ["MNE"], cmcId: "minereum" },
  { name: "Nyancoin", symbols: ["NYAN"], cmcId: "nyancoin" },
  { name: "Coin(O)", symbols: ["CNO"], cmcId: "coin" },
  { name: "Dalecoin", symbols: ["DALC"], cmcId: "dalecoin" },
  { name: "Aricoin", symbols: ["ARI"], cmcId: "aricoin" },
  { name: "Coinlancer", symbols: ["CL"], cmcId: "coinlancer" },
  { name: "Litecoin Plus", symbols: ["LCP"], cmcId: "litecoin-plus" },
  { name: "Evotion", symbols: ["EVO"], cmcId: "evotion" },
  { name: "CryptoForecast", symbols: ["CFT"], cmcId: "cryptoforecast" },
  { name: "Marijuanacoin", symbols: ["MAR"], cmcId: "marijuanacoin" },
  { name: "PureVidz", symbols: ["VIDZ"], cmcId: "purevidz" },
  { name: "NamoCoin", symbols: ["NAMO"], cmcId: "namocoin" },
  { name: "BitCoal", symbols: ["COAL"], cmcId: "bitcoal" },
  { name: "Sakuracoin", symbols: ["SKR"], cmcId: "sakuracoin" },
  { name: "Hexx", symbols: ["HXX"], cmcId: "hexx" },
  { name: "FlutterCoin", symbols: ["FLT"], cmcId: "fluttercoin" },
  { name: "PlatinumBAR", symbols: ["XPTX"], cmcId: "platinumbar" },
  { name: "Bitcoin Fast", symbols: ["BCF"], cmcId: "bitcoinfast" },
  { name: "Coinonat", symbols: ["CXT"], cmcId: "coinonat" },
  { name: "LiteCoin Ultra", symbols: ["LTCU"], cmcId: "litecoin-ultra" },
  { name: "Bitgem", symbols: ["BTG"], cmcId: "bitgem" },
  { name: "TrumpCoin", symbols: ["TRUMP"], cmcId: "trumpcoin" },
  { name: "DNotes", symbols: ["NOTE"], cmcId: "dnotes" },
  { name: "Animecoin", symbols: ["ANI"], cmcId: "animecoin" },
  { name: "Blockpool", symbols: ["BPL"], cmcId: "blockpool" },
  { name: "FuzzBalls", symbols: ["FUZZ"], cmcId: "fuzzballs" },
  { name: "Eurocoin", symbols: ["EUC"], cmcId: "eurocoin" },
  { name: "Pakcoin", symbols: ["PAK"], cmcId: "pakcoin" },
  { name: "Titcoin", symbols: ["TIT"], cmcId: "titcoin" },
  { name: "CORION", symbols: ["COR"], cmcId: "corion" },
  { name: "Mineum", symbols: ["MNM"], cmcId: "mineum" },
  { name: "UniCoin", symbols: ["UNIC"], cmcId: "unicoin" },
  { name: "GoldReserve", symbols: ["XGR"], cmcId: "goldreserve" },
  { name: "Francs", symbols: ["FRN"], cmcId: "francs" },
  { name: "Spots", symbols: ["SPT"], cmcId: "spots" },
  { name: "Machinecoin", symbols: ["MAC"], cmcId: "machinecoin" },
  { name: "MarxCoin", symbols: ["MARX"], cmcId: "marxcoin" },
  { name: "Gapcoin", symbols: ["GAP"], cmcId: "gapcoin" },
  { name: "Sativacoin", symbols: ["STV"], cmcId: "sativacoin" },
  { name: "RussiaCoin", symbols: ["RC"], cmcId: "russiacoin" },
  { name: "Netko", symbols: ["NETKO"], cmcId: "netko" },
  { name: "GAY Money", symbols: ["GAY"], cmcId: "gaycoin" },
  { name: "Kronecoin", symbols: ["KRONE"], cmcId: "kronecoin" },
  { name: "Chronos", symbols: ["CRX"], cmcId: "chronos" },
  { name: "SHACoin", symbols: ["SHA"], cmcId: "shacoin" },
  { name: "Kurrent", symbols: ["KURT"], cmcId: "kurrent" },
  { name: "Piggycoin", symbols: ["PIGGY"], cmcId: "piggycoin" },
  { name: "Tigercoin", symbols: ["TGC"], cmcId: "tigercoin" },
  { name: "Motocoin", symbols: ["MOTO"], cmcId: "motocoin" },
  { name: "Minex", symbols: ["MINEX"], cmcId: "minex" },
  { name: "Sexcoin", symbols: ["SXC"], cmcId: "sexcoin" },
  { name: "Renos", symbols: ["RNS"], cmcId: "renos" },
  { name: "MustangCoin", symbols: ["MST"], cmcId: "mustangcoin" },
  { name: "Money", symbols: [""], cmcId: "money" },
  { name: "QubitCoin", symbols: ["Q2C"], cmcId: "qubitcoin" },
  { name: "Blakecoin", symbols: ["BLC"], cmcId: "blakecoin" },
  { name: "Triangles", symbols: ["TRI"], cmcId: "triangles" },
  { name: "BERNcash", symbols: ["BERN"], cmcId: "berncash" },
  { name: "Joulecoin", symbols: ["XJO"], cmcId: "joulecoin" },
  { name: "PayCon", symbols: ["CON"], cmcId: "paycon" },
  { name: "Darsek", symbols: ["KED"], cmcId: "darsek" },
  { name: "Comet", symbols: ["CMT"], cmcId: "comet" },
  { name: "ICOBID", symbols: ["ICOB"], cmcId: "icobid" },
  { name: "Deutsche eMark", symbols: ["DEM"], cmcId: "deutsche-emark" },
  { name: "SpaceCoin", symbols: ["SPACE"], cmcId: "spacecoin" },
  { name: "Prime-XI", symbols: ["PXI"], cmcId: "prime-xi" },
  { name: "Catcoin", symbols: ["CAT"], cmcId: "catcoin" },
  { name: "Fazzcoin", symbols: ["FAZZ"], cmcId: "fazzcoin" },
  { name: "ChanCoin", symbols: ["CHAN"], cmcId: "chancoin" },
  { name: "BunnyCoin", symbols: ["BUN"], cmcId: "bunnycoin" },
  { name: "BumbaCoin", symbols: ["BUMBA"], cmcId: "bumbacoin" },
  { name: "Coimatic 3.0", symbols: ["CTIC3"], cmcId: "coimatic-3" },
  { name: "IrishCoin", symbols: ["IRL"], cmcId: "irishcoin" },
  { name: "GAIA", symbols: ["GAIA"], cmcId: "gaia" },
  { name: "Quark", symbols: ["QRK"], cmcId: "quark" },
  { name: "SmartCoin", symbols: ["SMC"], cmcId: "smartcoin" },
  { name: "C-Bit", symbols: ["XCT"], cmcId: "c-bit" },
  { name: "CacheCoin", symbols: ["CACH"], cmcId: "cachecoin" },
  { name: "BnrtxCoin", symbols: ["BNX"], cmcId: "bnrtxcoin" },
  { name: "Bolivarcoin", symbols: ["BOLI"], cmcId: "bolivarcoin" },
  { name: "AquariusCoin", symbols: ["ARCO"], cmcId: "aquariuscoin" },
  { name: "SwagBucks", symbols: ["BUCKS"], cmcId: "swagbucks" },
  { name: "Marscoin", symbols: ["MARS"], cmcId: "marscoin" },
  { name: "Creatio", symbols: ["XCRE"], cmcId: "creatio" },
  { name: "X-Coin", symbols: ["XCO"], cmcId: "x-coin" },
  { name: "Ixcoin", symbols: ["IXC"], cmcId: "ixcoin" },
  { name: "NetCoin", symbols: ["NET"], cmcId: "netcoin" },
  { name: "SongCoin", symbols: ["SONG"], cmcId: "songcoin" },
  { name: "300 Token", symbols: ["300"], cmcId: "300-token" },
  { name: "PostCoin", symbols: ["POST"], cmcId: "postcoin" },
  { name: "BitBar", symbols: ["BTB"], cmcId: "bitbar" },
  { name: "Musiconomi", symbols: ["MCI"], cmcId: "musiconomi" },
  { name: "Ecobit", symbols: ["ECOB"], cmcId: "ecobit" },
  { name: "HODL Bucks", symbols: ["HDLB"], cmcId: "hodl-bucks" },
  { name: "Swing", symbols: ["SWING"], cmcId: "swing" },
  { name: "Magnetcoin", symbols: ["MAGN"], cmcId: "magnetcoin" },
  { name: "BipCoin", symbols: ["BIP"], cmcId: "bipcoin" },
  { name: "LeafCoin", symbols: ["LEAF"], cmcId: "leafcoin" },
  { name: "Ratecoin", symbols: ["XRA"], cmcId: "ratecoin" },
  { name: "Etheriya", symbols: ["RIYA"], cmcId: "etheriya" },
  { name: "KushCoin", symbols: ["KUSH"], cmcId: "kushcoin" },
  {
    name: "Cthulhu Offerings",
    symbols: ["OFF"],
    cmcId: "cthulhu-offerings"
  },
  { name: "SoonCoin", symbols: ["SOON"], cmcId: "sooncoin" },
  { name: "I0Coin", symbols: ["I0C"], cmcId: "i0coin" },
  { name: "Coin2.1", symbols: ["C2"], cmcId: "coin2-1" },
  { name: "Bitstar", symbols: ["BITS"], cmcId: "bitstar" },
  { name: "InflationCoin", symbols: ["IFLT"], cmcId: "inflationcoin" },
  { name: "Version", symbols: ["V"], cmcId: "version" },
  { name: "GoldPieces", symbols: ["GP"], cmcId: "goldpieces" },
  { name: "Granite", symbols: ["GRN"], cmcId: "granitecoin" },
  { name: "MACRON", symbols: ["MCRN"], cmcId: "macron" },
  { name: "SixEleven", symbols: ["611"], cmcId: "sixeleven" },
  {
    name: "EncryptoTel",
    symbols: ["ETT", "eETT", "wETT"],
    cmcId: "[ETH] encryptotel-eth"
  },
  { name: "EcoCoin", symbols: ["ECO"], cmcId: "ecocoin" },
  {
    name: "Gold Pressed Latinum",
    symbols: ["GPL"],
    cmcId: "gold-pressed-latinum"
  },
  { name: "Opal", symbols: ["OPAL"], cmcId: "opal" },
  { name: "BenjiRolls", symbols: ["BENJI"], cmcId: "benjirolls" },
  { name: "Beatcoin", symbols: ["XBTS"], cmcId: "beatcoin" },
  { name: "StarCredits", symbols: ["STRC"], cmcId: "starcredits" },
  { name: "$326", symbols: ["UR"], cmcId: "ur" },
  { name: "LiteBar", symbols: ["LTB"], cmcId: "litebar" },
  {
    name: "Crypto Bullion",
    symbols: ["CBX"],
    cmcId: "cryptogenic-bullion"
  },
  { name: "GeertCoin", symbols: ["GEERT"], cmcId: "geertcoin" },
  { name: "RedCoin", symbols: ["RED"], cmcId: "redcoin" },
  { name: "Cubits", symbols: ["QBT"], cmcId: "cubits" },
  {
    name: "Independent Money System",
    symbols: ["IMS"],
    cmcId: "independent-money-system"
  },
  { name: "RevolverCoin", symbols: ["XRE"], cmcId: "revolvercoin" },
  { name: "Bit", symbols: ["8BIT"], cmcId: "8bit" },
  { name: "Bitcedi", symbols: ["BXC"], cmcId: "bitcedi" },
  { name: "Donationcoin", symbols: ["DON"], cmcId: "donationcoin" },
  { name: "AurumCoin", symbols: ["AU"], cmcId: "aurumcoin" },
  { name: "ZSEcoin", symbols: ["ZSE"], cmcId: "zsecoin" },
  { name: "TopCoin", symbols: ["TOP"], cmcId: "topcoin" },
  { name: "Kobocoin", symbols: ["KOBO"], cmcId: "kobocoin" },
  { name: "MojoCoin", symbols: ["MOJO"], cmcId: "mojocoin" },
  { name: "Senderon", symbols: ["SDRN"], cmcId: "senderon" },
  { name: "Emerald Crypto", symbols: ["EMD"], cmcId: "emerald" },
  { name: "Flaxscript", symbols: ["FLAX"], cmcId: "flaxscript" },
  { name: "Evil Coin", symbols: ["EVIL"], cmcId: "evil-coin" },
  { name: "SOILcoin", symbols: ["SOIL"], cmcId: "soilcoin" },
  { name: "RonPaulCoin", symbols: ["RPC"], cmcId: "ronpaulcoin" },
  {
    name: "Philosopher Stones",
    symbols: ["PHS"],
    cmcId: "philosopher-stones"
  },
  { name: "Sharkcoin", symbols: ["SAK"], cmcId: "sharkcoin" },
  { name: "ParallelCoin", symbols: ["DUO"], cmcId: "parallelcoin" },
  { name: "UltraCoin", symbols: ["UTC"], cmcId: "ultracoin" },
  { name: "Orbitcoin", symbols: ["ORB"], cmcId: "orbitcoin" },
  {
    name: "Hackspace Capital",
    symbols: ["HAC"],
    cmcId: "hackspace-capital"
  },
  { name: "Truckcoin", symbols: ["TRK"], cmcId: "truckcoin" },
  { name: "GameUnits", symbols: ["UNITS"], cmcId: "gameunits" },
  { name: "KekCoin", symbols: ["KEK"], cmcId: "kekcoin" },
  { name: "Acoin", symbols: ["ACOIN"], cmcId: "acoin" },
  { name: "HoboNickels", symbols: ["HBN"], cmcId: "hobonickels" },
  { name: "Elacoin", symbols: ["ELC"], cmcId: "elacoin" },
  { name: "Compcoin", symbols: ["CMP"], cmcId: "compcoin" },
  { name: "EDRCoin", symbols: ["EDRC"], cmcId: "edrcoin" },
  { name: "Alphabit", symbols: ["ABC"], cmcId: "alphabitcoinfund" },
  {
    name: "Metal Music Coin",
    symbols: ["MTLMC", "MTLMC3"],
    cmcId: "metal-music-coin"
  },
  { name: "SJWCoin", symbols: ["SJW"], cmcId: "sjwcoin" },
  {
    name: "Virta Unique Coin",
    symbols: ["VUC"],
    cmcId: "virta-unique-coin"
  },
  {
    name: "Safe Exchange Coin",
    symbols: ["SAFEX"],
    cmcId: "safe-exchange-coin"
  },
  { name: "CryptCoin", symbols: ["CRYPT"], cmcId: "cryptcoin" },
  { name: "Bismuth", symbols: ["BIS"], cmcId: "bismuth" },
  { name: "Kayicoin", symbols: ["KAYI"], cmcId: "kayicoin" },
  {
    name: "Tattoocoin (Standard Edition)",
    symbols: ["TSE"],
    cmcId: "tattoocoin"
  },
  {
    name: "Experience Points",
    symbols: ["XP"],
    cmcId: "experience-points"
  },
  { name: "POLY AI", symbols: ["AI"], cmcId: "poly-ai" },
  { name: "BitSoar", symbols: ["BSR"], cmcId: "bitsoar" },
  { name: "Monero Gold", symbols: ["XMRG"], cmcId: "monero-gold" },
  { name: "LendConnect", symbols: ["LCT"], cmcId: "lendconnect" },
  { name: "StrongHands", symbols: ["SHND"], cmcId: "stronghands" },
  { name: "ECC", symbols: ["ECC"], cmcId: "eccoin" },
  { name: "BitConnect", symbols: ["BCC"], cmcId: "bitconnect" },
  { name: "BuzzCoin", symbols: ["BUZZ"], cmcId: "buzzcoin" },
  { name: "SmartCash", symbols: ["SMART"], cmcId: "smartcash" },
  { name: "Uquid Coin", symbols: ["UQC"], cmcId: "uquid-coin" },
  { name: "Magnet", symbols: ["MAG"], cmcId: "magnet" },
  { name: "DavorCoin", symbols: ["DAV"], cmcId: "davorcoin" },
  { name: "Internxt", symbols: ["INXT"], cmcId: "internxt" },
  { name: "Sprouts", symbols: ["SPRTS"], cmcId: "sprouts" },
  { name: "SHIELD", symbols: ["XSH"], cmcId: "shield-xsh" },
  { name: "E-coin", symbols: ["ECN"], cmcId: "e-coin" },
  { name: "WomenCoin", symbols: ["WOMEN"], cmcId: "women" },
  { name: "Pure", symbols: ["PURE"], cmcId: "pure" },
  { name: "Espers", symbols: ["ESP"], cmcId: "espers" },
  { name: "Swisscoin", symbols: ["SIC"], cmcId: "swisscoin" },
  { name: "FLiK", symbols: ["FLIK"], cmcId: "flik" },
  { name: "Centurion", symbols: ["CNT"], cmcId: "centurion" },
  { name: "Tristar Coin", symbols: ["TSTR"], cmcId: "tristar-coin" },
  { name: "B3Coin", symbols: ["KB3"], cmcId: "b3coin" },
  { name: "Regalcoin", symbols: ["REC"], cmcId: "regalcoin" },
  { name: "BitSerial", symbols: ["BTE"], cmcId: "bitserial" },
  { name: "CybCSec", symbols: ["XCS"], cmcId: "cybcsec" },
  { name: "Desire", symbols: ["DSR"], cmcId: "desire" },
  { name: "BitTokens", symbols: ["BXT"], cmcId: "bittokens" },
  { name: "Vsync", symbols: ["VSX"], cmcId: "vsync-vsx" },
  {
    name: "GOLD Reward Token",
    symbols: ["GRX"],
    cmcId: "gold-reward-token"
  },
  { name: "Crave", symbols: ["CRAVE"], cmcId: "crave" },
  { name: "Sugar Exchange", symbols: ["SGR"], cmcId: "sugar-exchange" },
  { name: "Equal", symbols: ["EQL"], cmcId: "equal" },
  { name: "DigiCube", symbols: ["CUBE"], cmcId: "digicube" },
  { name: "Presearch", symbols: ["PRE", "PRS"], cmcId: "presearch" },
  { name: "LevoPlus", symbols: ["LVPS"], cmcId: "levoplus" },
  { name: "BLUE", symbols: ["BLUE"], cmcId: "ethereum-blue" },
  {
    name: "Global Tour Coin",
    symbols: ["GTC"],
    cmcId: "global-tour-coin"
  },
  { name: "Cyder", symbols: ["CYDER"], cmcId: "cyder" },
  { name: "Jetcoin", symbols: ["JET"], cmcId: "jetcoin" },
  { name: "LiteCoin Gold", symbols: ["LTG"], cmcId: "litecoin-gold" },
  { name: "NEO GOLD", symbols: ["NEOG"], cmcId: "neo-gold" },
  { name: "ELTCOIN", symbols: ["ELT"], cmcId: "eltcoin" },
  { name: "UFO Coin", symbols: ["UFO"], cmcId: "ufo-coin" },
  { name: "Ethereum Gold", symbols: ["ETG"], cmcId: "ethereum-gold" },
  { name: "Vulcano", symbols: ["VULCANO", "VULC"], cmcId: "vulcano" },
  { name: "HarmonyCoin", symbols: ["HMC"], cmcId: "harmonycoin-hmc" },
  { name: "FedoraCoin", symbols: ["TIPS"], cmcId: "fedoracoin" },
  { name: "SafeCoin", symbols: ["SFE"], cmcId: "safecoin" },
  { name: "Visio", symbols: ["VISIO"], cmcId: "visio" },
  { name: "Greencoin", symbols: ["GRE"], cmcId: "greencoin" },
  { name: "Coupecoin", symbols: ["COUPE"], cmcId: "coupecoin" },
  { name: "DraftCoin", symbols: ["DFT"], cmcId: "draftcoin" },
  {
    name: "Safe Trade Coin",
    symbols: ["XSTC"],
    cmcId: "safe-trade-coin"
  },
  {
    name: "Digital Money Bits",
    symbols: ["DMB"],
    cmcId: "digital-money-bits"
  },
  { name: "Antimatter", symbols: ["ANTX"], cmcId: "antimatter" },
  { name: "Birds", symbols: ["BIRDS"], cmcId: "birds" },
  { name: "T-coin", symbols: ["TCOIN"], cmcId: "t-coin" },
  { name: "BlakeStar", symbols: ["BLAS"], cmcId: "blakestar" },
  { name: "BOAT", symbols: ["BOAT"], cmcId: "doubloon" },
  { name: "Bitcoin Red", symbols: ["BTCRED"], cmcId: "bitcoin-red" },
  { name: "Ammo Reloaded", symbols: ["AMMO"], cmcId: "ammo-rewards" },
  { name: "GlobalToken", symbols: ["GLT"], cmcId: "globaltoken" },
  { name: "Runners", symbols: ["RUNNERS"], cmcId: "runners" },
  { name: "KiloCoin", symbols: ["KLC"], cmcId: "kilocoin" },
  { name: "PeepCoin", symbols: ["PCN"], cmcId: "peepcoin" },
  { name: "Playkey", symbols: ["PKT"], cmcId: "playkey" },
  { name: "Elysium", symbols: ["ELS"], cmcId: "elysium" },
  { name: "bitqy", symbols: ["BQ"], cmcId: "bitqy" },
  {
    name: "Master Swiscoin",
    symbols: ["MSCN"],
    cmcId: "master-swiscoin"
  },
  { name: "BritCoin", symbols: ["BRIT"], cmcId: "britcoin" },
  { name: "HOdlcoin", symbols: ["HODL"], cmcId: "hodlcoin" },
  {
    name: "Speed Mining Service",
    symbols: ["SMS"],
    cmcId: "speed-mining-service"
  },
  { name: "Neuro", symbols: ["NRO"], cmcId: "neuro" },
  { name: "Topaz Coin", symbols: ["TOPAZ"], cmcId: "topaz" },
  { name: "MinexCoin", symbols: ["MNX"], cmcId: "minexcoin" },
  { name: "GlassCoin", symbols: ["GLS"], cmcId: "glasscoin" },
  { name: "Wowcoin", symbols: ["WOW"], cmcId: "wowcoin" },
  { name: "Honey", symbols: ["HONEY"], cmcId: "honey" },
  { name: "Dutch Coin", symbols: ["DUTCH"], cmcId: "dutch-coin" },
  { name: "ZoZoCoin", symbols: ["ZZC"], cmcId: "zozocoin" },
  { name: "DynamicCoin", symbols: ["DMC"], cmcId: "dynamiccoin" },
  { name: "CHIPS", symbols: ["CHIPS"], cmcId: "chips" },
  { name: "Goodomy", symbols: ["GOOD"], cmcId: "goodomy" },
  { name: "Scorecoin", symbols: ["SCORE"], cmcId: "scorecoin" },
  { name: "Zlancer", symbols: ["ZCG"], cmcId: "zcash-gold" },
  { name: "MiloCoin", symbols: ["MILO"], cmcId: "milocoin" },
  { name: "Protean", symbols: ["PRN"], cmcId: "protean" },
  {
    name: "Pabyosi Coin (Special)",
    symbols: ["PCS"],
    cmcId: "pabyosi-coin-special"
  },
  { name: "Torcoin", symbols: ["TOR"], cmcId: "torcoin-tor" },
  { name: "FAPcoin", symbols: ["FAP"], cmcId: "fapcoin" },
  { name: "Bitcoin Planet", symbols: ["BTPL"], cmcId: "bitcoin-planet" },
  { name: "Roofs", symbols: ["ROOFS"], cmcId: "roofs" },
  { name: "Credence Coin", symbols: ["CRDNC"], cmcId: "credence-coin" },
  { name: "Impact", symbols: ["IMX"], cmcId: "impact" },
  { name: "SuperCoin", symbols: ["SUPER"], cmcId: "supercoin" },
  { name: "Wink", symbols: ["WINK"], cmcId: "wink" },
  { name: "Target Coin", symbols: ["TGT"], cmcId: "target-coin" },
  { name: "Aces", symbols: ["ACES"], cmcId: "aces" },
  { name: "BROTHER", symbols: ["BRAT"], cmcId: "brat" },
  { name: "Remicoin", symbols: ["RMC"], cmcId: "remicoin" },
  {
    name: "StarCash Network",
    symbols: ["STARS"],
    cmcId: "starcash-network"
  },
  { name: "Natcoin", symbols: ["NTC"], cmcId: "natcoin" },
  { name: "AmsterdamCoin", symbols: ["AMS"], cmcId: "amsterdamcoin" },
  { name: "BigUp", symbols: ["BIGUP"], cmcId: "bigup" },
  { name: "Bolenum", symbols: ["BLN"], cmcId: "bolenum" },
  {
    name: "Commodity Ad Network",
    symbols: ["CDX"],
    cmcId: "commodity-ad-network"
  },
  { name: "Ethbits", symbols: ["ETBS"], cmcId: "ethbits" },
  { name: "Pirate Blocks", symbols: ["SKULL"], cmcId: "pirate-blocks" },
  { name: "Fujinto", symbols: ["NTO"], cmcId: "fujinto" },
  { name: "Jin Coin", symbols: ["JIN"], cmcId: "jin-coin" },
  { name: "High Gain", symbols: ["HIGH"], cmcId: "high-gain" },
  { name: "Luna Coin", symbols: ["LUNA"], cmcId: "luna-coin" },
  { name: "India Coin", symbols: ["INDIA"], cmcId: "india-coin" },
  { name: "iDice", symbols: ["ICE"], cmcId: "idice" },
  { name: "Golfcoin", symbols: ["GOLF"], cmcId: "golfcoin" },
  { name: "GoldMaxCoin", symbols: ["GMX"], cmcId: "goldmaxcoin" },
  {
    name: "Prospectors Gold",
    symbols: ["PGL"],
    cmcId: "prospectors-gold"
  },
  { name: "Ebittree Coin", symbols: ["EBT"], cmcId: "ebittree-coin" },
  { name: "Akuya Coin", symbols: ["AKY"], cmcId: "akuya-coin" },
  { name: "CaliphCoin", symbols: ["CALC"], cmcId: "caliphcoin" },
  { name: "Vault Coin", symbols: ["VLTC"], cmcId: "vault-coin" },
  { name: "TurboCoin", symbols: ["TURBO"], cmcId: "turbocoin" },
  { name: "BetaCoin", symbols: ["BET"], cmcId: "betacoin" },
  {
    name: "HealthyWormCoin",
    symbols: ["WORM"],
    cmcId: "healthywormcoin"
  },
  { name: "Digital Rupees", symbols: ["DRS"], cmcId: "digital-rupees" },
  { name: "Magnum", symbols: ["MGM"], cmcId: "magnum" },
  { name: "Bitbase", symbols: ["BTBc"], cmcId: "bitbase" },
  { name: "Happycoin", symbols: ["HPC"], cmcId: "happycoin" },
  { name: "Slevin", symbols: ["SLEVIN"], cmcId: "slevin" },
  { name: "Regacoin", symbols: ["REGA"], cmcId: "regacoin" },
  { name: "UGAIN", symbols: ["GAIN"], cmcId: "ugain" },
  { name: "XTD Coin", symbols: ["XTD"], cmcId: "xtd-coin" },
  { name: "Zennies", symbols: ["ZENI"], cmcId: "zennies" },
  { name: "PinkDog", symbols: ["PDG"], cmcId: "pinkdog" },
  { name: "Peacecoin", symbols: ["PEC"], cmcId: "peacecoin" },
  { name: "SISA", symbols: ["SISA"], cmcId: "sisa" },
  { name: "Primulon", symbols: ["PRIMU"], cmcId: "primulon" },
  { name: "LandCoin", symbols: ["LDC"], cmcId: "landcoin" },
  { name: "FuturXe", symbols: ["FXE"], cmcId: "futurexe" },
  { name: "Artex Coin", symbols: ["ATX"], cmcId: "artex-coin" },
  {
    name: "Theresa May Coin",
    symbols: ["MAY"],
    cmcId: "theresa-may-coin"
  },
  { name: "Adzcoin", symbols: ["ADZ"], cmcId: "adzcoin" },
  { name: "Huncoin", symbols: ["HNC"], cmcId: "huncoin" },
  { name: "Coimatic 2.0", symbols: ["CTIC2"], cmcId: "coimatic-2" },
  { name: "Tellurion", symbols: ["TELL"], cmcId: "tellurion" },
  { name: "BlazerCoin", symbols: ["BLAZR"], cmcId: "blazercoin" },
  { name: "AnarchistsPrime", symbols: ["ACP"], cmcId: "anarchistsprime" },
  { name: "Ulatech", symbols: ["ULA"], cmcId: "ulatech" },
  { name: "NumusCash", symbols: ["NUMUS"], cmcId: "numuscash" },
  { name: "Halloween Coin", symbols: ["HALLO"], cmcId: "halloween-coin" },
  { name: "REX", symbols: ["REX"], cmcId: "real-estate-tokens" },
  { name: "Bastonet", symbols: ["BSN"], cmcId: "bastonet" },
  { name: "ZetaMicron", symbols: ["ZMC"], cmcId: "zetamicron" },
  { name: "Printerium", symbols: ["PRX"], cmcId: "printerium" },
  { name: "VirtualCoin", symbols: ["VC"], cmcId: "virtualcoin" },
  { name: "Cheapcoin", symbols: ["CHEAP"], cmcId: "cheapcoin" },
  { name: "PoSToken", symbols: ["POS"], cmcId: "postoken" },
  { name: "PlayerCoin", symbols: ["PLACO"], cmcId: "playercoin" },
  {
    name: "Tattoocoin (Limited Edition)",
    symbols: ["TLE"],
    cmcId: "tattoocoin-limited"
  },
  { name: "netBit", symbols: ["NBIT"], cmcId: "netbit" },
  { name: "Aseancoin", symbols: ["ASN"], cmcId: "aseancoin" },
  { name: "Link Platform", symbols: ["LNK"], cmcId: "link-platform" },
  { name: "GoldMint", symbols: ["MNTP"], cmcId: "goldmint" },
  { name: "SwapToken", symbols: ["TOKEN"], cmcId: "swaptoken" },
  { name: "Hacken", symbols: ["HKN"], cmcId: "hacken" },
  { name: "Tokenbox", symbols: ["TBX"], cmcId: "tokenbox" },
  { name: "TOKYO", symbols: ["TOKC"], cmcId: "tokyo" },
  { name: "Peerguess", symbols: ["GUESS"], cmcId: "guess" },
  { name: "FirstCoin", symbols: ["FRST"], cmcId: "firstcoin" },
  { name: "Bitcoin Atom", symbols: ["BCA"], cmcId: "bitcoin-atom" },
  { name: "NewYorkCoin", symbols: ["NYC"], cmcId: "newyorkcoin" },
  { name: "Worldcore", symbols: ["WRC"], cmcId: "worldcore" },
  { name: "HTML5COIN", symbols: ["HTML5"], cmcId: "htmlcoin" },
  {
    name: "E-Dinar Coin",
    symbols: ["EDR2", "EDR"],
    cmcId: "e-dinar-coin"
  },
  { name: "Quebecoin", symbols: ["QBC"], cmcId: "quebecoin" },
  { name: "Bitcoin God", symbols: ["GOD"], cmcId: "bitcoin-god" },
  { name: "SONO", symbols: ["ALTCOM"], cmcId: "altcommunity-coin" },
  { name: "Ethereum Cash", symbols: ["ECASH"], cmcId: "ethereumcash" },
  { name: "Covesting", symbols: ["COVX", "COV"], cmcId: "covesting" },
  { name: "Veltor", symbols: ["VLT"], cmcId: "veltor" },
  {
    name: "Lightning Bitcoin",
    symbols: ["LBTC"],
    cmcId: "[Futures] lightning-bitcoin"
  },
  { name: "iEthereum", symbols: ["IETH"], cmcId: "iethereum" },
  { name: "SegWit2x", symbols: ["B2X"], cmcId: "segwit2x" },
  { name: "Shadow Token", symbols: ["SHDW"], cmcId: "shadow-token" },
  { name: "Cryptonex", symbols: ["CNX"], cmcId: "cryptonex" },
  { name: "TagCoin", symbols: ["TAG"], cmcId: "tagcoin" },
  { name: "Project-X", symbols: ["NANOX"], cmcId: "project-x" },
  { name: "ATBCoin", symbols: ["ATB"], cmcId: "atbcoin" },
  { name: "JobsCoin", symbols: ["JOBS"], cmcId: "jobscoin" },
  { name: "ArbitrageCT", symbols: ["ARCT"], cmcId: "arbitragect" },
  { name: "ATLANT", symbols: ["ATL"], cmcId: "atlant" },
  { name: "Polybius", symbols: ["PLBT"], cmcId: "polybius" },
  { name: "Iconic", symbols: ["ICON"], cmcId: "iconic" },
  { name: "Signatum", symbols: ["SIGT"], cmcId: "signatum" },
  { name: "RoyalCoin", symbols: ["ROYAL"], cmcId: "royalcoin" },
  { name: "BTCMoon", symbols: ["BTCM"], cmcId: "btcmoon" },
  { name: "Speedcash", symbols: ["SCS"], cmcId: "speedcash" },
  { name: "Braincoin", symbols: ["BRAIN"], cmcId: "braincoin" },
  {
    name: "Advanced Internet Blocks",
    symbols: ["AIB"],
    cmcId: "advanced-internet-blocks"
  },
  { name: "Bitvolt", symbols: ["VOLT"], cmcId: "bitvolt" },
  { name: "Elementrem", symbols: ["ELE"], cmcId: "elementrem" },
  { name: "DAPPSTER", symbols: ["DLISK"], cmcId: "dappster" },
  { name: "Wi Coin", symbols: ["WIC"], cmcId: "wi-coin" },
  {
    name: "Happy Creator Coin",
    symbols: ["HCC"],
    cmcId: "happy-creator-coin"
  },
  { name: "Quotient", symbols: ["XQN"], cmcId: "quotient" },
  { name: "Carboncoin", symbols: ["CARBON"], cmcId: "carboncoin" },
  { name: "Crystal Clear", symbols: ["CCT"], cmcId: "crystal-clear" },
  { name: "CrevaCoin", symbols: ["CREVA"], cmcId: "crevacoin" },
  { name: "Onix", symbols: ["ONX"], cmcId: "onix" },
  { name: "Mao Zedong", symbols: ["MAO"], cmcId: "mao-zedong" },
  { name: "Xios", symbols: ["XIOS"], cmcId: "xios" },
  { name: "RubleBit", symbols: ["RUBIT"], cmcId: "rublebit" },
  { name: "Universe", symbols: ["UNI"], cmcId: "universe" },
  { name: "BitBoost", symbols: ["BBT"], cmcId: "bitboost" },
  { name: "Verify", symbols: ["CRED"], cmcId: "verify" },
  { name: "FireFlyCoin", symbols: ["FFC"], cmcId: "fireflycoin" },
  { name: "TrickyCoin", symbols: ["TRICK"], cmcId: "trickycoin" },
  { name: "RabbitCoin", symbols: ["RBBT"], cmcId: "rabbitcoin" },
  { name: "HitCoin", symbols: ["HTC"], cmcId: "hitcoin" },
  { name: "Rupaya", symbols: ["RUPX"], cmcId: "[OLD] rupaya-old" },
  { name: "Ethereum Lite", symbols: ["ELITE"], cmcId: "ethereum-lite" },
  {
    name: "Wild Beast Block",
    symbols: ["WBB"],
    cmcId: "wild-beast-block"
  },
  { name: "iCoin", symbols: ["ICN"], cmcId: "icoin" },
  { name: "GeyserCoin", symbols: ["GSR"], cmcId: "geysercoin" },
  { name: "Bitok", symbols: ["BITOK"], cmcId: "bitok" },
  { name: "BioBar", symbols: ["BIOB"], cmcId: "biobar" },
  { name: "LePen", symbols: ["LEPEN"], cmcId: "lepen" },
  { name: "SocialCoin", symbols: ["SOCC"], cmcId: "socialcoin-socc" },
  { name: "Rialto", symbols: ["XRL"], cmcId: "rialto" },
  { name: "Unrealcoin", symbols: ["URC"], cmcId: "unrealcoin" },
  { name: "LetItRide", symbols: ["LIR"], cmcId: "letitride" },
  { name: "TodayCoin", symbols: ["TODAY"], cmcId: "todaycoin" },
  { name: "Debitcoin", symbols: ["DBTC"], cmcId: "debitcoin" },
  { name: "Firecoin", symbols: ["FIRE"], cmcId: "firecoin" },
  { name: "Shilling", symbols: ["SH"], cmcId: "shilling" },
  { name: "Privatix", symbols: ["PRIX"], cmcId: "privatix" },
  { name: "SportsCoin", symbols: ["SPORT"], cmcId: "sportscoin" },
  { name: "P7Coin", symbols: ["P7C"], cmcId: "p7coin" },
  { name: "bitJob", symbols: ["STU"], cmcId: "student-coin" },
  { name: "KingN Coin", symbols: ["KNC"], cmcId: "kingn-coin" },
  { name: "Bubble", symbols: ["BUB"], cmcId: "bubble" },
  { name: "Dollarcoin", symbols: ["DLC"], cmcId: "dollarcoin" },
  { name: "Zayedcoin", symbols: ["ZYD"], cmcId: "zayedcoin" },
  { name: "RSGPcoin", symbols: ["RSGP"], cmcId: "rsgpcoin" },
  { name: "Uro", symbols: ["URO"], cmcId: "uro" },
  { name: "AntiBitcoin", symbols: ["ANTI"], cmcId: "antibitcoin" },
  { name: "MaxCoin", symbols: ["MAX"], cmcId: "maxcoin" },
  { name: "Ride My Car", symbols: ["RIDE"], cmcId: "ride-my-car" },
  { name: "Valorbit", symbols: ["VAL"], cmcId: "valorbit" },
  { name: "Voyacoin", symbols: ["VOYA"], cmcId: "voyacoin" },
  { name: "XDE II", symbols: ["XDE2"], cmcId: "xde-ii" },
  { name: "Hedge", symbols: ["HDG"], cmcId: "hedge" },
  { name: "Eternity", symbols: ["ENT"], cmcId: "eternity" },
  { name: "SatoshiMadness", symbols: ["MAD"], cmcId: "satoshimadness" },
  { name: "Blackstar", symbols: ["BSTAR"], cmcId: "blackstar" },
  { name: "Opescoin", symbols: ["OPES"], cmcId: "opescoin" },
  { name: "Bitcoin 21", symbols: ["XBTC21"], cmcId: "bitcoin-21" },
  { name: "PayPeer", symbols: ["PAYP"], cmcId: "paypeer" },
  { name: "MoneyCoin", symbols: ["MONEY"], cmcId: "moneycoin" },
  {
    name: "Digital Credits",
    symbols: ["DGCS"],
    cmcId: "digital-credits"
  },
  { name: "PIECoin", symbols: ["PIE"], cmcId: "piecoin" },
  { name: "VectorAI", symbols: ["VEC2"], cmcId: "vector" },
  { name: "SproutsExtreme", symbols: ["SPEX"], cmcId: "sproutsextreme" },
  { name: "PLNcoin", symbols: ["PLNC"], cmcId: "plncoin" },
  { name: "DeltaCredits", symbols: ["DCRE"], cmcId: "deltacredits" },
  { name: "Rcoin", symbols: ["RCN"], cmcId: "rcoin" },
  { name: "BlueCoin", symbols: ["BLU"], cmcId: "bluecoin" },
  { name: "TAGRcoin", symbols: ["TAGR"], cmcId: "tagrcoin" },
  { name: "PosEx", symbols: ["PEX"], cmcId: "posex" },
  { name: "Hyper", symbols: ["HYPERX"], cmcId: "hyper" },
  { name: "OCOW", symbols: ["OCOW"], cmcId: "ocow" },
  { name: "BTCtalkcoin", symbols: ["TALK"], cmcId: "btctalkcoin" },
  { name: "Zurcoin", symbols: ["ZUR"], cmcId: "zurcoin" },
  { name: "PayCoin", symbols: ["XPY"], cmcId: "paycoin2" },
  { name: "SydPak", symbols: ["SDP"], cmcId: "sydpak" },
  { name: "2GIVE", symbols: ["2GIVE"], cmcId: "2give" },
  {
    name: "CryptoWorldX Token",
    symbols: ["CWXT"],
    cmcId: "cryptoworldx-token"
  },
  { name: "Antilitecoin", symbols: ["ALTC"], cmcId: "antilitecoin" },
  { name: "AmberCoin", symbols: ["AMBER"], cmcId: "ambercoin" },
  {
    name: "Digital Bullion Gold",
    symbols: ["DBG"],
    cmcId: "digital-bullion-gold"
  },
  { name: "DarkLisk", symbols: ["DISK"], cmcId: "darklisk" },
  { name: "EGO", symbols: ["EGO"], cmcId: "ego" },
  { name: "MetalCoin", symbols: ["METAL"], cmcId: "metalcoin" },
  { name: "Cashme", symbols: ["CME"], cmcId: "cashme" },
  { name: "G3N", symbols: ["GEN"], cmcId: "genstake" },
  { name: "Destiny", symbols: ["DES"], cmcId: "destiny" },
  { name: "VIP Tokens", symbols: ["VIP"], cmcId: "vip-tokens" },
  { name: "Rubies", symbols: ["RBIES"], cmcId: "rubies" },
  { name: "Flycoin", symbols: ["FLY"], cmcId: "flycoin" },
  { name: "ShellCoin", symbols: ["SHELL"], cmcId: "shellcoin" },
  { name: "Bitcurrency", symbols: ["BTCR"], cmcId: "bitcurrency" },
  { name: "Concoin", symbols: ["CONX"], cmcId: "concoin" },
  { name: "Orlycoin", symbols: ["ORLY"], cmcId: "orlycoin" },
  {
    name: "The Vegan Initiative",
    symbols: ["XVE"],
    cmcId: "the-vegan-initiative"
  },
  {
    name: "Ultimate Secure Cash",
    symbols: ["USC"],
    cmcId: "ultimate-secure-cash"
  },
  { name: "ShadowCash", symbols: ["SDC"], cmcId: "shadowcash" },
  { name: "Californium", symbols: ["CF"], cmcId: "californium" },
  { name: "NodeCoin", symbols: ["NODC"], cmcId: "nodecoin" },
  { name: "Lazaruscoin", symbols: ["LAZ"], cmcId: "lazaruscoin" },
  { name: "HiCoin", symbols: ["XHI"], cmcId: "hicoin" },
  { name: "Psilocybin", symbols: ["PSY"], cmcId: "psilocybin" },
  { name: "ImpulseCoin", symbols: ["IMPS"], cmcId: "impulsecoin" },
  { name: "Moneta", symbols: ["MONETA"], cmcId: "moneta2" },
  { name: "Cypher", symbols: ["CYP"], cmcId: "cypher" },
  { name: "DomRaider", symbols: ["DRT"], cmcId: "domraider" },
  { name: "BowsCoin", symbols: ["BSC"], cmcId: "bowscoin" },
  { name: "Dreamcoin", symbols: ["DRM"], cmcId: "dreamcoin" },
  { name: "ARbit", symbols: ["ARB"], cmcId: "arbit" },
  { name: "GlobalCoin", symbols: ["GLC"], cmcId: "globalcoin" },
  { name: "LinkedCoin", symbols: ["LKC"], cmcId: "linkedcoin" },
  { name: "Yescoin", symbols: ["YES"], cmcId: "yescoin" },
  { name: "X2", symbols: ["X2"], cmcId: "x2" },
  { name: "Litecred", symbols: ["LTCR"], cmcId: "litecred" },
  { name: "BiosCrypto", symbols: ["BIOS"], cmcId: "bios-crypto" },
  { name: "Cabbage", symbols: ["CAB"], cmcId: "cabbage" },
  { name: "WayGuide", symbols: ["WAY"], cmcId: "wayguide" },
  { name: "Dubstep", symbols: ["DUB"], cmcId: "dubstep" },
  { name: "SecretCoin", symbols: ["SCRT"], cmcId: "secretcoin" },
  { name: "Colossuscoin V2", symbols: ["CV2"], cmcId: "colossuscoin-v2" },
  { name: "Cycling Coin", symbols: ["CYC"], cmcId: "cycling-coin" },
  { name: "RichCoin", symbols: ["RICHX"], cmcId: "richcoin" },
  { name: "Dashs", symbols: ["DASHS"], cmcId: "dashs" },
  { name: "InvisibleCoin", symbols: ["IVZ"], cmcId: "invisiblecoin" },
  { name: "PX", symbols: ["PX"], cmcId: "px" },
  { name: "Omicron", symbols: ["OMC"], cmcId: "omicron" },
  { name: "Steps", symbols: ["STEPS"], cmcId: "steps" },
  { name: "GuccioneCoin", symbols: ["GCC"], cmcId: "guccionecoin" },
  { name: "iBank", symbols: ["IBANK"], cmcId: "ibank" },
  { name: "IslaCoin", symbols: ["ISL"], cmcId: "islacoin" },
  { name: "MMXVI", symbols: ["MMXVI"], cmcId: "mmxvi" },
  { name: "GameLeagueCoin", symbols: ["GML"], cmcId: "gameleaguecoin" },
  { name: "Jewels", symbols: ["JWL"], cmcId: "jewels" },
  { name: "TeamUp", symbols: ["TEAM"], cmcId: "teamup" },
  { name: "WARP", symbols: ["WARP"], cmcId: "warp" },
  { name: "Pulse", symbols: ["PULSE"], cmcId: "pulse" },
  { name: "Operand", symbols: ["OP"], cmcId: "operand" },
  { name: "Karmacoin", symbols: ["KARMA"], cmcId: "karmacoin" },
  { name: "MindCoin", symbols: ["MND"], cmcId: "mindcoin" },
  { name: "Stress", symbols: ["STS"], cmcId: "stress" },
  { name: "TheCreed", symbols: ["TCR"], cmcId: "thecreed" },
  { name: "PonziCoin", symbols: ["PONZI"], cmcId: "ponzicoin" },
  { name: "LuckChain", symbols: ["BASH"], cmcId: "luckchain" },
  { name: "Selfiecoin", symbols: ["SLFI"], cmcId: "selfiecoin" },
  { name: "Save and Gain", symbols: ["SANDG"], cmcId: "save-and-gain" },
  { name: "Axiom", symbols: ["AXIOM"], cmcId: "axiom" },
  { name: "GameBet Coin", symbols: ["GBT"], cmcId: "gamebet-coin" },
  { name: "FrankyWillCoin", symbols: ["FRWC"], cmcId: "frankywillcoin" },
  { name: "BitAlphaCoin", symbols: ["BAC"], cmcId: "bitalphacoin" },
  { name: "High Voltage", symbols: ["HVCO"], cmcId: "high-voltage" },
  { name: "FlavorCoin", symbols: ["FLVR"], cmcId: "flavorcoin" },
  { name: "Zonecoin", symbols: ["ZNE"], cmcId: "zonecoin" },
  {
    name: "ATMChain",
    symbols: ["ATMCHA", "ATM"],
    cmcId: "attention-token-of-media"
  },
  { name: "Bitz", symbols: ["BITZ"], cmcId: "bitz" },
  { name: "AvatarCoin", symbols: ["AV"], cmcId: "avatarcoin" },
  { name: "PrismChain", symbols: ["PRM"], cmcId: "prismchain" },
  { name: "PokeCoin", symbols: ["POKE"], cmcId: "pokecoin" },
  { name: "Shorty", symbols: ["SHORTY"], cmcId: "shorty" },
  { name: "WMCoin", symbols: ["WMC"], cmcId: "wmcoin" },
  { name: "BeaverCoin", symbols: ["BVC"], cmcId: "beavercoin" },
  { name: "Xaucoin", symbols: ["XAU"], cmcId: "xaucoin" },
  { name: "Yacoin", symbols: ["YAC"], cmcId: "yacoin" },
  { name: "Franko", symbols: ["FRK"], cmcId: "franko" },
  { name: "LAthaan", symbols: ["LTH"], cmcId: "lathaan" },
  { name: "BillaryCoin", symbols: ["BLRY"], cmcId: "billarycoin" },
  { name: "Xonecoin", symbols: ["XOC"], cmcId: "xonecoin" },
  { name: "CyberCoin", symbols: ["CC"], cmcId: "cybercoin" },
  { name: "OsmiumCoin", symbols: ["OS76"], cmcId: "osmiumcoin" },
  { name: "EggCoin", symbols: ["EGG"], cmcId: "eggcoin" },
  { name: "Sling", symbols: ["SLING"], cmcId: "sling" },
  { name: "CBD Crystals", symbols: ["CBD"], cmcId: "cbd-crystals" },
  { name: "KashhCoin", symbols: ["KASHH"], cmcId: "kashhcoin" },
  { name: "DigitalNote", symbols: ["XDN"], cmcId: "digitalnote" },
  { name: "Tezos (Pre-Launch)", symbols: ["XTZ"], cmcId: "tezos" },
  {
    name: "Animation Vision Cash",
    symbols: ["AVH"],
    cmcId: "animation-vision-cash"
  },
  { name: "Storm", symbols: ["STORM"], cmcId: "storm" },
  { name: "Rivetz", symbols: ["RVT"], cmcId: "rivetz" },
  { name: "SwissBorg", symbols: ["CHSB"], cmcId: "swissborg" },
  { name: "Lamden", symbols: ["TAU"], cmcId: "lamden" },
  { name: "AirToken", symbols: ["AIR"], cmcId: "airtoken" },
  { name: "Hive", symbols: ["HVN"], cmcId: "hive" },
  { name: "SportyCo", symbols: ["SPF"], cmcId: "sportyco" },
  { name: "Etheroll", symbols: ["DICE"], cmcId: "etheroll" },
  { name: "DIMCOIN", symbols: ["DIM"], cmcId: "dimcoin" },
  { name: "Veritaseum", symbols: ["VERI"], cmcId: "veritaseum" },
  { name: "Zeusshield", symbols: ["ZSC"], cmcId: "zeusshield" },
  { name: "MCAP", symbols: ["MCAP"], cmcId: "mcap" },
  { name: "OriginTrail", symbols: ["TRAC"], cmcId: "origintrail" },
  { name: "Indicoin", symbols: ["INDI"], cmcId: "indicoin" },
  { name: "Xaurum", symbols: ["XAUR"], cmcId: "xaurum" },
  { name: "FlypMe", symbols: ["FYP"], cmcId: "flypme" },
  { name: "COSS", symbols: ["COSS"], cmcId: "coss" },
  { name: "InsurePal", symbols: ["IPL"], cmcId: "insurepal" },
  { name: "Dovu", symbols: ["DOV"], cmcId: "dovu" },
  { name: "Bitair", symbols: ["BTCA"], cmcId: "bitair" },
  { name: "Farad", symbols: ["FRD"], cmcId: "farad" },
  { name: "BitDice", symbols: ["CSNO"], cmcId: "bitdice" },
  { name: "Exchange Union", symbols: ["XUC"], cmcId: "exchange-union" },
  { name: "United Traders Token", symbols: ["UTT"], cmcId: "uttoken" },
  { name: "Authorship", symbols: ["ATS"], cmcId: "authorship" },
  { name: "Cloud", symbols: ["CLD"], cmcId: "cloud" },
  { name: "Eroscoin", symbols: ["ERO"], cmcId: "eroscoin" },
  { name: "Octanox", symbols: ["OTX"], cmcId: "octanox" },
  { name: "Opus", symbols: ["OPT"], cmcId: "opus" },
  { name: "Qvolta", symbols: ["QVT"], cmcId: "qvolta" },
  { name: "Cryptopay", symbols: ["CPAY"], cmcId: "cryptopay" },
  { name: "EthBet", symbols: ["EBET"], cmcId: "ethbet" },
  { name: "NEVERDIE", symbols: ["NDC"], cmcId: "neverdie" },
  { name: "Maecenas", symbols: ["ART"], cmcId: "maecenas" },
  { name: "Quantum", symbols: ["QAU"], cmcId: "quantum" },
  { name: "Fantomcoin", symbols: ["FCN"], cmcId: "fantomcoin" },
  { name: "CarTaxi Token", symbols: ["CTX"], cmcId: "cartaxi-token" },
  { name: "QuazarCoin", symbols: ["QCN"], cmcId: "quazarcoin" },
  { name: "Dashcoin", symbols: ["DSH"], cmcId: "dashcoin" },
  { name: "ExchangeN", symbols: ["EXN"], cmcId: "exchangen" },
  {
    name: "Useless Ethereum Token",
    symbols: ["UET"],
    cmcId: "useless-ethereum-token"
  },
  { name: "DAO.Casino", symbols: ["BET"], cmcId: "dao-casino" },
  { name: "CryptoInsight", symbols: ["TKR"], cmcId: "trackr" },
  { name: "BitAsean", symbols: ["BAS"], cmcId: "bitasean" },
  { name: "FundYourselfNow", symbols: ["FYN"], cmcId: "fundyourselfnow" },
  { name: "Starbase", symbols: ["STAR"], cmcId: "starbase" },
  { name: "Unity Ingot", symbols: ["UNY"], cmcId: "unity-ingot" },
  { name: "Soarcoin", symbols: ["SOAR"], cmcId: "soarcoin" },
  { name: "TechShares", symbols: ["THS"], cmcId: "techshares" },
  { name: "RouletteToken", symbols: ["RLT"], cmcId: "roulettetoken" },
  {
    name: "Dynamic Trading Rights",
    symbols: ["DTR"],
    cmcId: "dynamic-trading-rights"
  },
  { name: "Yocoin", symbols: ["YOC"], cmcId: "yocoin" },
  { name: "LEOcoin", symbols: ["LEO"], cmcId: "leocoin" },
  {
    name: "President Trump",
    symbols: ["PRES"],
    cmcId: "president-trump"
  },
  { name: "Chronologic", symbols: ["DAY"], cmcId: "chronologic" },
  { name: "Escroco", symbols: ["ESC"], cmcId: "escoro" },
  { name: "Nitro", symbols: ["NOX"], cmcId: "nitro" },
  {
    name: "UniversalRoyalCoin",
    symbols: ["UNRC"],
    cmcId: "universalroyalcoin"
  },
  { name: "OBITS", symbols: ["OBITS"], cmcId: "obits" },
  { name: "Elcoin", symbols: ["EL"], cmcId: "elcoin-el" },
  { name: "Veros", symbols: ["VRS"], cmcId: "veros" },
  { name: "Macro", symbols: ["MCR"], cmcId: "macro1" },
  { name: "CryptoCarbon", symbols: ["CCRB"], cmcId: "cryptocarbon" },
  { name: "UNCoin", symbols: ["UNC"], cmcId: "uncoin" },
  { name: "FinCoin", symbols: ["FNC"], cmcId: "fincoin" },
  { name: "Abncoin", symbols: ["ABN"], cmcId: "abncoin" },
  { name: "ReeCoin", symbols: ["REE"], cmcId: "reecoin" },
  { name: "First Bitcoin", symbols: ["BIT"], cmcId: "first-bitcoin" },
  { name: "Oxycoin", symbols: ["OXY"], cmcId: "oxycoin" },
  { name: "PiplCoin", symbols: ["PIPL"], cmcId: "piplcoin" },
  { name: "Helleniccoin", symbols: ["HNC"], cmcId: "helleniccoin" },
  { name: "Zilbercoin", symbols: ["ZBC"], cmcId: "zilbercoin" },
  { name: "AllSafe", symbols: ["ASAFE2"], cmcId: "allsafe" },
  { name: "Peerplays", symbols: ["PPY"], cmcId: "peerplays-ppy" },
  { name: "DIBCOIN", symbols: ["DIBC"], cmcId: "dibcoin" },
  { name: "FUNCoin", symbols: ["FUNC"], cmcId: "funcoin" },
  { name: "Dollar Online", symbols: ["DOLLAR"], cmcId: "dollar-online" },
  { name: "EventChain", symbols: ["EVC"], cmcId: "eventchain" },
  { name: "Rawcoin", symbols: ["XRC"], cmcId: "rawcoin2" },
  { name: "Avoncoin", symbols: ["ACN"], cmcId: "avoncoin" },
  { name: "Bitpark Coin", symbols: ["BPC"], cmcId: "bitpark-coin" }
];
