{
  "IOTA": ["IOT", "IOTA", "MIOTA"],
  "Bitcoin": ["BTC"],
  "Hshare": ["HSR"],
  "United Bitcoin": ["UBTC"],
  "Ethereum": ["ETH"],
  "Bitcoin Cash": ["BCH", "BCC"],
  "Etherparty": ["FUEL"],
  "Litecoin": ["LTC"],
  "Dash": ["DASH", "DSH"],
  "Emercoin": ["EMC"],
  "Ripple": ["XRP"],
  "Monero": ["XMR"],
  "Zcash": ["ZEC"],
  "Bytecoin": ["BCN"],
  "NEM": ["XEM"],
  "DigitalNote": ["XDN"],
  "BitConnect": ["BCC"],
  "Ormeus Coin": ["ORME"],
  "EOS": ["EOS"],
  "Ethereum Classic": ["ETC"],
  "Nxt": ["NXT"],
  "Lisk": ["LSK"],
  "NEO": ["NEO"],
  "Ardor": ["ARDR"],
  "SunContract": ["SNC"],
  "Bitcoin Gold": ["BTG"],
  "MaidSafeCoin": ["MAID"],
  "TRON": ["TRX"],
  "Dogecoin": ["DOGE"],
  "Bancor": ["BNT"],
  "MyBit Token": ["MYB"],
  "Animation Vision Cash": ["AVH"],
  "Stox": ["STX"],
  "Eidoo": ["EDO"],
  "Viberate": ["VIB"],
  "iXledger": ["IXT"],
  "WAX": ["WAX"],
  "Suretly": ["SUR"],
  "Tezos (Pre-Launch)": ["XTZ"],
  "Tierion": ["TNT"],
  "Speed Mining Service": ["SMS"],
  "Populous": ["PPT"],
  "bitJob": ["STU"],
  "Cryptonex": ["CNX"],
  "ICOS": ["ICOS"],
  "SwissBorg": ["CHSB"],
  "Dentacoin": ["DCN"],
  "AdEx": ["ADX"],
  "Stratis": ["STRAT"],
  "Kubera Coin": ["KBR"],
  "Hive": ["HVN"],
  "Siacoin": ["SC"],
  "AirToken": ["AIR"],
  "Pillar": ["PLR"],
  "Blackmoon": ["BMC"],
  "0x": ["ZRX"],
  "Hackspace Capital": ["HAC"],
  "Rivetz": ["RVT"],
  "SportyCo": ["SPF"],
  "Nimiq": ["NET"],
  "indaHash": ["IDH"],
  "MobileGo": ["EMGO", "MGO"],
  "Verge": ["XVG"],
  "Storm": ["STORM"],
  "Etheroll": ["DICE"],
  "VeChain": ["VEN", "VET"],
  "Veritaseum": ["VERI"],
  "Worldcore": ["WRC"],
  "Dent": ["DENT"],
  "ICON": ["ICX"],
  "Zeusshield": ["ZSC"],
  "MCAP": ["MCAP"],
  "SegWit2x": ["B2X"],
  "OriginTrail": ["TRAC"],
  "Titanium Blockchain": ["BAR"],
  "Bitcore": ["BTX"],
  "Hedge": ["HDG"],
  "Lamden": ["TAU"],
  "DigiByte": ["DGB"],
  "DIMCOIN": ["DIM"],
  "Cindicator": ["CND"],
  "Qtum": ["QTUM"],
  "NAGA": ["NGC"],
  "eBitcoin": ["EBTCNEW", "EBTC"],
  "Paragon": ["PRG"],
  "Peercoin": ["PPC"],
  "Po.et": ["POE"],
  "ZrCoin": ["ZRC"],
  "DigixDAO": ["DGD"],
  "FlypMe": ["FYP"],
  "Xaurum": ["XAUR"],
  "Chronobank": ["TIME"],
  "Substratum": ["SUB"],
  "Walton": ["WTC", "WALTON"],
  "Jibrel Network": ["JNT"],
  "Augur": ["REP"],
  "Covesting": ["COV", "COVX"],
  "HelloGold": ["HGT"],
  "Indicoin": ["INDI"],
  "OmiseGO": ["OMG"],
  "EchoLink": ["EKO"],
  "Coinlancer": ["CL"],
  "Cryptopay": ["CPAY"],
  "Presearch": ["PRE", "PRS"],
  "BitDice": ["CSNO"],
  "ClearPoll": ["POLL"],
  "SONM": ["SNM"],
  "COSS": ["COSS"],
  "Synereo": ["AMP"],
  "ATMChain": ["ATM", "ATMCHA"],
  "Waves": ["WAVES"],
  "LIFE": ["LIFE"],
  "TenX": ["PAY"],
  "VIBE": ["VIBE"],
  "KickCoin": ["KICK"],
  "FunFair": ["FUN"],
  "Enigma": ["ENG", "XNG"],
  "UTRUST": ["UTK"],
  "Ethos": ["BQX", "ETHOS"],
  "Decentraland": ["MANA", "MNA"],
  "CRYPTO20": ["C20"],
  "LockChain": ["LOC"],
  "Steem": ["STEEM"],
  "Voise": ["VOISE"],
  "Agrello": ["DLT"],
  "Aeternity": ["AE"],
  "Centra": ["CTR"],
  "Status": ["SNT"],
  "GameCredits": ["GAME"],
  "Ignis": ["IGNIS"],
  "Bitair": ["BTCA"],
  "Loopring": ["LRC"],
  "Octanox": ["OTX"],
  "CoinDash": ["CDT"],
  "UG Token": ["UGT"],
  "Maecenas": ["ART"],
  "Komodo": ["KMD"],
  "Zap": ["ZAP"],
  "Dovu": ["DOV"],
  "SmartCash": ["SMART"],
  "Authorship": ["ATS"],
  "SwftCoin": ["SWFTC"],
  "InsurePal": ["IPL"],
  "ETHLend": ["LEND"],
  "CarTaxi Token": ["CTX"],
  "Aeron": ["ARN"],
  "Royal Kingdom Coin": ["RKC"],
  "Super Bitcoin": ["SBTC"],
  "FirstBlood": ["1ST", "FirstBlood"],
  "Pluton": ["PLU"],
  "Swarm City": ["SWT"],
  "Metaverse ETP": ["ETP"],
  "Exchange Union": ["XUC"],
  "DRP Utility": ["DRPU"],
  "Trade Token": ["TIO"],
  "Neblio": ["NEBL"],
  "DAO.Casino": ["BET"],
  "Streamr DATAcoin": ["DATA"],
  "Edgeless": ["EDG"],
  "Aventus": ["AVT"],
  "Wings": ["WINGS"],
  "Matchpool": ["GUP"],
  "SkinCoin": ["SKIN"],
  "Cloud": ["CLD"],
  "Aeon": ["AEON"],
  "DubaiCoin": ["DBIX"],
  "Opus": ["OPT"],
  "Monetha": ["MTH"],
  "BOScoin": ["BOS"],
  "DECENT": ["DCT"],
  "CryptoInsight": ["TKR"],
  "Propy": ["PRO", "PROPY"],
  "BitClave": ["CAT"],
  "Gnosis": ["GNO"],
  "Indorse Token": ["IND"],
  "Monaco": ["MCO"],
  "district0x": ["DNT"],
  "Fujinto": ["NTO"],
  "Bytom": ["BTM"],
  "Nexium": ["NXC"],
  "Polybius": ["PLBT"],
  "Elementrem": ["ELE"],
  "Lunyr": ["LUN", "LUNYR"],
  "TokenCard": ["TKN"],
  "Aragon": ["ANT"],
  "Patientory": ["PTOY"],
  "Cofound.it": ["CFI"],
  "Eroscoin": ["ERO"],
  "MicroMoney": ["AMM"],
  "Open Trading Network": ["OTN"],
  "Qvolta": ["QVT"],
  "WeTrust": ["TRST"],
  "Civic": ["CVC"],
  "LAToken": ["LA"],
  "OAX": ["OAX"],
  "Iconomi": ["ICN"],
  "Everex": ["EVX"],
  "CryptoPing": ["PING"],
  "QuazarCoin": ["QCN"],
  "ExchangeN": ["EXN"],
  "Commodity Ad Network": ["CDX"],
  "Enjin Coin": ["ENJ"],
  "Lampix": ["PIX"],
  "YOYOW": ["YOYOW", "YOYO", "YYW"],
  "ATLANT": ["ATL"],
  "Mothership": ["MSP"],
  "Useless Ethereum Token": ["UET"],
  "Quantum": ["QAU"],
  "Happycoin": ["HPC"],
  "Santiment Network Token": ["SAN"],
  "Dashcoin": ["DSH"],
  "SingularDTV": ["SNGLS", "SNG"],
  "ATBCoin": ["ATB"],
  "iExec RLC": ["RLC"],
  "TaaS": ["TAAS"],
  "SISA": ["SISA"],
  "United Traders Token": ["UTT"],
  "Crystal Clear": ["CCT"],
  "Genesis Vision": ["GVT"],
  "Social": ["SCL"],
  "Steem Dollars": ["SBD"],
  "DomRaider": ["DRT"],
  "Farad": ["FRD"],
  "Obsidian": ["ODN"],
  "Target Coin": ["TGT"],
  "Ethbits": ["ETBS"],
  "BitAsean": ["BAS"],
  "NEVERDIE": ["NDC"],
  "EthBet": ["EBET"],
  "FundYourselfNow": ["FYN"],
  "Fantomcoin": ["FCN"],
  "Starbase": ["STAR"],
  "DigitalDevelopersFund": ["DDF"],
  "Blocktix": ["TIX"],
  "Minereum": ["MNE"],
  "Bibox Token": ["BIX"],
  "Spectre.ai Utility Token": ["SXUT"],
  "High Performance Blockchain": ["HPB"],
  "Gifto": ["GTO"],
  "IoT Chain": ["ITC"],
  "Trinity Network Credit": ["TNC"],
  "Genaro Network": ["GNX"],
  "CyberMiles": ["CMT"],
  "Change": ["CAG"],
  "Time New Bank": ["TNB"],
  "aelf": ["ELF"],
  "Bloom": ["BLT"],
  "Raiden Network Token": ["RDN"],
  "Maker": ["MKR"],
  "Olympus Labs": ["MOT"],
  " ": ["MKR", "LSK", "MOD"],
  "Snovio": ["SNOV"],
  "AI Doctor": ["AIDOC"],
  "Game.com": ["GTC"],
  "AWARE": ["AWR"],
  "ProChain": ["PRA"],
  "Bottos": ["BTO"],
  "": ["DTA"],
  "DATA": ["DTA"],
  "Show": ["SHOW"],
  "SIRIN LABS Token": ["SRN"],
  "Golem": ["GNT"],
  "AirSwap": ["AST"],
  "Kyber Network": ["KNC"],
  "Basic Attention Token": ["BAT"],
  "Aion": ["AION"],
  "Mysterium": ["MYST"],
  "Melon": ["MLN"],
  "INS Ecosystem": ["INS"],
  "Quantum Resistant Ledger": ["QRL"],
  "Neumark": ["NEU"],
  "SALT": ["SALT"],
  "Storj": ["STORJ"],
  "Sphre AIR": ["XID"],
  "Request Network": ["REQ"],
  "Golos Gold": ["GBG"],
  "vSlice": ["VSL", "VSLICE"],
  "Humaniq": ["HMQ"],
  "Incent": ["INCNT"],
  "BCAP": ["BCAP"],
  "Namecoin": ["NMC"],
  "Novacoin": ["NVC"],
  "Recently5NEO": ["NEO"],
  "Binance Coin": ["BNB"],
  "Nano": ["NANO", "XRB"],
  "Bluzelle": ["BLZ"],
  "Cardano": ["ADA"],
  "NAV Coin": ["NAV"],
  "Stellar": ["XLM", "STR"],
  "Metal": ["MTL"],
  "Bread": ["BRD"],
  "IOStoken": ["IOST"],
  "GXShares": ["GXS"],
  "Ambrosus": ["AMB"],
  "Nuls": ["NULS"],
  "Quantstamp": ["QSP"],
  "ChainLink": ["LINK"],
  "Gas": ["GAS"],
  "BitShares": ["BTS"],
  "ChatCoin": ["CHAT"],
  "AppCoins": ["APPC"],
  "Recently990x": ["ZRX"],
  "Bitcoin Diamond": ["BCD"],
  "Triggers": ["TRIG"],
  "Power Ledger": ["POWR"],
  "PIVX": ["PIVX"],
  "Ripio Credit Network": ["RCN"],
  "ZCoin": ["XZC"],
  "WaBi": ["WABI"],
  "Simple Token": ["OST"],
  "Recently1360x": ["ZRX"],
  "Ark": ["ARK"],
  "BlockMason Credit Protocol": ["BCPT"],
  "Modum": ["MOD"],
  "Moeda Loyalty Points": ["MDA"],
  "Viacoin": ["VIA"],
  "Tether": ["USDT"],
  "AidCoin": ["AID"],
  "QASH": ["QSH", "QASH"],
  "SpankChain": ["SPK", "SPANK"],
  "OceanChain": ["OC"],
  "CFun": ["CFUN"],
  "ACChain": ["ACC"],
  "ATN": ["ATN"],
  "SpaceChain": ["SPC"],
  "HalalChain": ["HLC"],
  "Profile Utility Token": ["PUT"],
  "Ink": ["INK"],
  "Energo": ["TSL"],
  "Internet Node Token": ["INT"],
  "SIGMAcoin": ["SIGMA"],
  "DeepBrain Chain": ["DBC"],
  "Qbao": ["QBT"],
  "Bodhi": ["BOT"],
  "Achain": ["ACT"],
  "Nebulas": ["NAS"],
  "iQuant": ["IQT"],
  "BITFID": ["FID"],
  "Vertcoin": ["VTC"],
  "Huobi Token": ["HT"],
  "Elastos": ["ELA"],
  "WaykiChain": ["WICC"],
  "QunQun": ["QUN"],
  "Zilliqa": ["ZIL"],
  "Red Pulse": ["RPX"],
  "STK": ["STK"],
  "LinkEye": ["LET"],
  "Ruff": ["RUFF"],
  "WePower": ["WPR"],
  "Theta Token": ["THETA"],
  "MediShares": ["MDS"],
  "All Sports": ["SOC"],
  "Zilla": ["ZLA"],
  "TopChain": ["TOPC"],
  "Odyssey": ["OCN"],
  "Matryx": ["MTX"],
  "SmartMesh": ["SMT"],
  "Medicalchain": ["MTN"],
  "CoinMeet": ["MEE"],
  "Yee": ["YEE"],
  "Datum": ["DAT"],
  "BitcoinX": ["BCX"],
  "REAL": ["REA"],
  "Selfkey": ["KEY"],
  "Dai": ["DAI"],
  "InvestFeed": ["IFT"],
  "$0$0.9531940.00%": ["WINGS"],
  "$0$1.390.00%Recently": ["ZRX"],
  "Unity Ingot": ["UNY"],
  "FirstCoin": ["FRST"],
  "Soarcoin": ["SOAR"],
  "CloakCoin": ["CLOAK"],
  "Shift": ["SHIFT"],
  "Syscoin": ["SYS"],
  "TerraNova": ["TER"],
  "MonaCoin": ["MONA"],
  "SIBCoin": ["SIB"],
  "Dynamic Trading Rights": ["DTR"],
  "Karbo": ["KRB"],
  "Voxels": ["VOX"],
  "Curecoin": ["CURE"],
  "Creditbit": ["CRBIT", "CRB"],
  "RouletteToken": ["RLT"],
  "Spectrecoin": ["XSPEC"],
  "Master Swiscoin": ["MSCN"],
  "PoSW Coin": ["POSW"],
  "MinexCoin": ["MNX"],
  "B2B": ["B2B"],
  "BitSend": ["BSD"],
  "Sexcoin": ["SXC"],
  "VeriumReserve": ["VRM"],
  "Uquid Coin": ["UQC"],
  "VeriCoin": ["VRC"],
  "Wi Coin": ["WIC"],
  "E-Dinar Coin": ["EDR", "EDR2"],
  "Rialto": ["XRL"],
  "Dimecoin": ["DIME"],
  "TechShares": ["THS"],
  "TransferCoin": ["TX"],
  "DynamicCoin": ["DMC"],
  "President Trump": ["PRES"],
  "Yocoin": ["YOC"],
  "Golos": ["GOLOS"],
  "UniversalRoyalCoin": ["UNRC"],
  "ArcticCoin": ["ARC", "ARCX"],
  "PutinCoin": ["PUT"],
  "Peerplays": ["PPY"],
  "SolarCoin": ["SLR"],
  "Capricoin": ["CPC"],
  "Burst": ["BURST"],
  "LEOcoin": ["LEO"],
  "OBITS": ["OBITS"],
  "Sumokoin": ["SUMO"],
  "BlackCoin": ["BLK"],
  "Vault Coin": ["VLTC"],
  "Bata": ["BTA"],
  "Veros": ["VRS"],
  "Groestlcoin": ["GRS"],
  "Macro": ["MCR"],
  "MojoCoin": ["MOJO"],
  "CryptoCarbon": ["CCRB"],
  "Moin": ["MOIN"],
  "Elcoin": ["EL"],
  "BlueCoin": ["BLU"],
  "Espers": ["ESP"],
  "Helleniccoin": ["HNC"],
  "Chronologic": ["DAY"],
  "Zilbercoin": ["ZBC"],
  "TrumpCoin": ["TRUMP"],
  "Escroco": ["ESC"],
  "Decision Token": ["HST"],
  "Adzcoin": ["ADZ"],
  "Diamond": ["DMD"],
  "PiplCoin": ["PIPL"],
  "Artex Coin": ["ATX"],
  "Flixxo": ["FLIXX"],
  "Rubies": ["RBIES"],
  "ReeCoin": ["REE"],
  "Oxycoin": ["OXY"],
  "BitBar": ["BTB"],
  "FinCoin": ["FNC"],
  "Eternity": ["ENT"],
  "Fastcoin": ["FST"],
  "TrueFlip": ["TFL"],
  "First Bitcoin": ["BIT"],
  "PostCoin": ["POST"],
  "DIBCOIN": ["DIBC"],
  "Nitro": ["NOX"],
  "AllSafe": ["ASAFE2"],
  "Abncoin": ["ABN"],
  "GOLD Reward Token": ["GRX"],
  "Dollar Online": ["DOLLAR"],
  "CrevaCoin": ["CREVA"],
  "GoldBlocks": ["GB"],
  "EncryptoTel": ["eETT", "wETT", "ETT"],
  "42-coin": ["FORTYTWO", "42"],
  "Bitpark Coin": ["BPC"],
  "EventChain": ["EVC"],
  "FUNCoin": ["FUNC"],
  "UNCoin": ["UNC"],
  "LandCoin": ["LDC"],
  "Avoncoin": ["ACN"],
  "Rawcoin": ["XRC"],
  "Luna Coin": ["LUNA"],
  "iTicoin": ["ITI"],
  "Recently3180x": ["ZRX"],
  "InsaneCoin": ["INSN"],
  "Counterparty": ["XCP"],
  "COMSA": ["CMS.ETH", "CMS.XEM", "CMS"],
  "Pepe Cash": ["PEPECASH"],
  "Bitcrystals": ["BCY"],
  "Storjcoin X": ["SJCX"],
  "Revain": ["R"],
  "Fortuna": ["FOTA"],
  "THEKEY": ["TKY"],
  "Oyster": ["PRL"],
  "Dragonchain": ["DRGN"],
  "KuCoin Shares": ["KCS"],
  "QLINK": ["QLC"],
  "Telcoin": ["TEL"],
  "SingularityNET": ["AGI"],
  "Zeepin": ["ZPT"],
  "RChain": ["RHOC"],
  "carVertical": ["CV"],
  "LOCIcoin": ["LOCI"],
  "Hawala.Today": ["HAT"],
  "Block Array": ["ARY"],
  "CoinFi": ["COFI"],
  "aXpire": ["AXP"],
  "Pareto Network": ["PARETO"],
  "CargoX": ["CXO"],
  "Bounty0x": ["BNTY"],
  "Solaris": ["XLR"],
  "CanYaCoin": ["CAN"],
  "Iungo": ["ING"],
  "adbank": ["ADB"],
  "DeepOnion": ["ONION"],
  "Aigang": ["AIX"],
  "Elixir": ["ELIX"],
  "Asch": ["XAS"],
  "Unikoin Gold": ["UKG"],
  "EncrypGen": ["DNA"],
  "Publica": ["PBL"],
  "Pura": ["PURA"],
  "Confido": ["CFD"],
  "Hacken": ["HKN"],
  "PACcoin": ["PAC"],
  "DraftCoin": ["DFT"],
  "SwapToken": ["TOKEN"],
  "GoldMint": ["MNTP"],
  "TOKYO": ["TOKC"],
  "Tokenbox": ["TBX"],
  "E-coin": ["ECN"],
  "WomenCoin": ["WOMEN"],
  "HitCoin": ["HTC"],
  "Peerguess": ["GUESS"],
  "HTML5COIN": ["HTML5"],
  "NewYorkCoin": ["NYC"],
  "Universal Currency": ["UNIT"],
  "ReddCoin": ["RDD"],
  "Bitvolt": ["VOLT"],
  "NoLimitCoin": ["NLC2"],
  "Bitcoin Atom": ["BCA"],
  "Rise": ["RISE"],
  "XTRABYTES": ["XBY"],
  "SONO": ["ALTCOM"],
  "Lightning Bitcoin": ["LBTC"],
  "HarmonyCoin": ["HMC"],
  "Zennies": ["ZENI"],
  "Veltor": ["VLT"],
  "Ethereum Cash": ["ECASH"],
  "Linda": ["LINDA"],
  "Bitcoin God": ["GOD"],
  "Regalcoin": ["REC"],
  "SwagBucks": ["BUCKS"],
  "iEthereum": ["IETH"],
  "Shadow Token": ["SHDW"],
  "RubleBit": ["RUBIT"],
  "Evil Coin": ["EVIL"],
  "BestChain": ["BEST"],
  "HempCoin": ["HMP", "THC"],
  "Quebecoin": ["QBC"],
  "MACRON": ["MCRN"],
  "DecentBet": ["DBET"],
  "Rupaya": ["RUPX"],
  "EcoCoin": ["ECO"],
  "VapersCoin": ["VPRC"],
  "Atomic Coin": ["ATOM"],
  "Rupee": ["RUP"],
  "Cream": ["CRM"],
  "Project-X": ["NANOX"],
  "TEKcoin": ["TEK"],
  "JobsCoin": ["JOBS"],
  "Ethereum Lite": ["ELITE"],
  "Pandacoin": ["PND"],
  "ArbitrageCT": ["ARCT"],
  "TittieCoin": ["TTC"],
  "Wagerr": ["WGR"],
  "Onix": ["ONX"],
  "FujiCoin": ["FJC"],
  "Elite": ["1337"],
  "PetroDollar": ["XPD"],
  "Braincoin": ["BRAIN"],
  "Advanced Internet Blocks": ["AIB"],
  "XDE II": ["XDE2"],
  "RoyalCoin": ["ROYAL"],
  "Bitcoin Red": ["BTCRED"],
  "Hexx": ["HXX"],
  "Vulcano": ["VULC", "VULCANO"],
  "Decred": ["DCR"],
  "Valorbit": ["VAL"],
  "TagCoin": ["TAG"],
  "CannabisCoin": ["CANN"],
  "SpaceCoin": ["SPACE"],
  "LanaCoin": ["LANA"],
  "Opescoin": ["OPES"],
  "TrickyCoin": ["TRICK"],
  "Carboncoin": ["CARBON"],
  "RabbitCoin": ["RBBT"],
  "Beatcoin": ["XBTS"],
  "BTCMoon": ["BTCM"],
  "Mao Zedong": ["MAO"],
  "Zetacoin": ["ZET"],
  "Wink": ["WINK"],
  "Cannation": ["CNNC"],
  "Quotient": ["XQN"],
  "BitTokens": ["BXT"],
  "AntiBitcoin": ["ANTI"],
  "BERNcash": ["BERN"],
  "Speedcash": ["SCS"],
  "LiteCoin Ultra": ["LTCU"],
  "Ecobit": ["ECOB"],
  "Bubble": ["BUB"],
  "Crown": ["CRW"],
  "Centurion": ["CNT"],
  "Tellurion": ["TELL"],
  "SmartCoin": ["SMC"],
  "LeaCoin": ["LEA"],
  "Unrealcoin": ["URC"],
  "MetalCoin": ["METAL"],
  "BioBar": ["BIOB"],
  "Universe": ["UNI"],
  "Coimatic 2.0": ["CTIC2"],
  "LePen": ["LEPEN"],
  "GeyserCoin": ["GSR"],
  "FuzzBalls": ["FUZZ"],
  "Cryptojacks": ["CJ"],
  "Zurcoin": ["ZUR"],
  "Internxt": ["INXT"],
  "Xios": ["XIOS"],
  "Rimbit": ["RBT"],
  "Chronos": ["CRX"],
  "ClubCoin": ["CLUB"],
  "Bitcoin 21": ["XBTC21"],
  "DNotes": ["NOTE"],
  "Argus": ["ARGUS"],
  "PrismChain": ["PRM"],
  "Global Currency Reserve": ["GCR"],
  "Wild Beast Block": ["WBB"],
  "Debitcoin": ["DBTC"],
  "PureVidz": ["VIDZ"],
  "LiteDoge": ["LDOGE"],
  "Visio": ["VISIO"],
  "LiteBitcoin": ["LBTCX", "LBTC"],
  "SpreadCoin": ["SPR"],
  "Titcoin": ["TIT"],
  "Magi": ["XMG"],
  "Acoin": ["ACOIN"],
  "DAPPSTER": ["DLISK"],
  "KingN Coin": ["KNC"],
  "Bitok": ["BITOK"],
  "Happy Creator Coin": ["HCC"],
  "GlobalBoost-Y": ["BSTY"],
  "PayPeer": ["PAYP"],
  "BigUp": ["BIGUP"],
  "InflationCoin": ["IFLT"],
  "NevaCoin": ["NEVA"],
  "Fazzcoin": ["FAZZ"],
  "Unify": ["UNIFY"],
  "RSGPcoin": ["RSGP"],
  "Theresa May Coin": ["MAY"],
  "Clams": ["CLAM"],
  "Zayedcoin": ["ZYD"],
  "Pirate Blocks": ["SKULL"],
  "Greencoin": ["GRE"],
  "SocialCoin": ["SOCC"],
  "Opal": ["OPAL"],
  "Ultimate Secure Cash": ["USC"],
  "Independent Money System": ["IMS"],
  "Crypto Bullion": ["CBX"],
  "ShellCoin": ["SHELL"],
  "SportsCoin": ["SPORT"],
  "BowsCoin": ["BSC"],
  "Pakcoin": ["PAK"],
  "Allion": ["ALL"],
  "iCoin": ["ICN"],
  "MarxCoin": ["MARX"],
  "Blackstar": ["BSTAR"],
  "Syndicate": ["SYNX"],
  "InPay": ["INPAY"],
  "Californium": ["CF"],
  "LetItRide": ["LIR"],
  "Verify": ["CRED"],
  "Voyacoin": ["VOYA"],
  "Comet": ["CMT"],
  "Deutsche eMark": ["DEM"],
  "PayCon": ["CON"],
  "PayCoin": ["XPY"],
  "Litecred": ["LTCR"],
  "Eurocoin": ["EUC"],
  "Bean Cash": ["BITB"],
  "GameUnits": ["UNITS"],
  "MaxCoin": ["MAX"],
  "SatoshiMadness": ["MAD"],
  "CryptoWorldX Token": ["CWXT"],
  "BuzzCoin": ["BUZZ"],
  "TajCoin": ["TAJ"],
  "Printerium": ["PRX"],
  "Motocoin": ["MOTO"],
  "HiCoin": ["XHI"],
  "Dollarcoin": ["DLC"],
  "ImpulseCoin": ["IMPS"],
  "Ride My Car": ["RIDE"],
  "LuckChain": ["BASH"],
  "Halloween Coin": ["HALLO"],
  "Signatum": ["SIGT"],
  "Digital Bullion Gold": ["DBG"],
  "Influxcoin": ["INFX"],
  "KushCoin": ["KUSH"],
  "Lazaruscoin": ["LAZ"],
  "Iconic": ["ICON"],
  "ParallelCoin": ["DUO"],
  "OsmiumCoin": ["OS76"],
  "2GIVE": ["2GIVE"],
  "MiloCoin": ["MILO"],
  "PosEx": ["PEX"],
  "TodayCoin": ["TODAY"],
  "MindCoin": ["MND"],
  "G3N": ["GEN"],
  "AudioCoin": ["ADC"],
  "OCOW": ["OCOW"],
  "SaluS": ["SLS"],
  "P7Coin": ["P7C"],
  "Firecoin": ["FIRE"],
  "Xaucoin": ["XAU"],
  "AmsterdamCoin": ["AMS"],
  "DarkLisk": ["DISK"],
  "Creatio": ["XCRE"],
  "Antilitecoin": ["ALTC"],
  "Ratecoin": ["XRA"],
  "Aces": ["ACES"],
  "Zonecoin": ["ZNE"],
  "Concoin": ["CONX"],
  "BiosCrypto": ["BIOS"],
  "BenjiRolls": ["BENJI"],
  "Coinonat": ["CXT"],
  "Privatix": ["PRIX"],
  "Crave": ["CRAVE"],
  "RichCoin": ["RICHX"],
  "EDRCoin": ["EDRC"],
  "netBit": ["NBIT"],
  "BitBoost": ["BBT"],
  "EGO": ["EGO"],
  "Shilling": ["SH"],
  "FireFlyCoin": ["FFC"],
  "DeltaCredits": ["DCRE"],
  "ALIS": ["ALIS"],
  "Francs": ["FRN"],
  "Colossuscoin V2": ["CV2"],
  "Expanse": ["EXP"],
  "UGAIN": ["GAIN"],
  "Destiny": ["DES"],
  "Flycoin": ["FLY"],
  "Netko": ["NETKO"],
  "BlazerCoin": ["BLAZR"],
  "Startcoin": ["START"],
  "Bolivarcoin": ["BOLI"],
  "Axiom": ["AXIOM"],
  "Kobocoin": ["KOBO"],
  "Uro": ["URO"],
  "Yescoin": ["YES"],
  "Auroracoin": ["AUR"],
  "The Vegan Initiative": ["XVE"],
  "PlatinumBAR": ["XPTX"],
  "Operand": ["OP"],
  "Digital Credits": ["DGCS"],
  "Cypher": ["CYP"],
  "Xonecoin": ["XOC"],
  "AmberCoin": ["AMBER"],
  "Cabbage": ["CAB"],
  "Bitcurrency": ["BTCR"],
  "GPU Coin": ["GPU"],
  "Swing": ["SWING"],
  "ChessCoin": ["CHESS"],
  "Kurrent": ["KURT"],
  "Coin2.1": ["C2"],
  "AquariusCoin": ["ARCO"],
  "Selfiecoin": ["SLFI"],
  "Mineum": ["MNM"],
  "MustangCoin": ["MST"],
  "ShadowCash": ["SDC"],
  "PX": ["PX"],
  "ARbit": ["ARB"],
  "TheCreed": ["TCR"],
  "Pulse": ["PULSE"],
  "Franko": ["FRK"],
  "PLNcoin": ["PLNC"],
  "Yacoin": ["YAC"],
  "Sharkcoin": ["SAK"],
  "PokeCoin": ["POKE"],
  "Dalecoin": ["DALC"],
  "Bitstar": ["BITS"],
  "GoldPieces": ["GP"],
  "Gulden": ["NLG"],
  "Moneta": ["MONETA"],
  "GlobalCoin": ["GLC"],
  "Cashme": ["CME"],
  "Prime-XI": ["PXI"],
  "TAGRcoin": ["TAGR"],
  "Omicron": ["OMC"],
  "LinkedCoin": ["LKC"],
  "ICOBID": ["ICOB"],
  "Joulecoin": ["XJO"],
  "BTCtalkcoin": ["TALK"],
  "VIP Tokens": ["VIP"],
  "OctoCoin": ["888"],
  "High Voltage": ["HVCO"],
  "Cycling Coin": ["CYC"],
  "Sativacoin": ["STV"],
  "ParkByte": ["PKB"],
  "Dashs": ["DASHS"],
  "Psilocybin": ["PSY"],
  "InvisibleCoin": ["IVZ"],
  "WayGuide": ["WAY"],
  "BillaryCoin": ["BLRY"],
  "Dreamcoin": ["DRM"],
  "EggCoin": ["EGG"],
  "VectorAI": ["VEC2"],
  "Karmacoin": ["KARMA"],
  "SecretCoin": ["SCRT"],
  "Hyper": ["HYPERX"],
  "NodeCoin": ["NODC"],
  "RonPaulCoin": ["RPC"],
  "Steps": ["STEPS"],
  "Bitz": ["BITZ"],
  "X-Coin": ["XCO"],
  "IslaCoin": ["ISL"],
  "SuperCoin": ["SUPER"],
  "MMXVI": ["MMXVI"],
  "GameLeagueCoin": ["GML"],
  "Jewels": ["JWL"],
  "TeamUp": ["TEAM"],
  "SophiaTX": ["SPHTX"],
  "WARP": ["WARP"],
  "Evotion": ["EVO"],
  "Version": ["V"],
  "SydPak": ["SDP"],
  "Rubycoin": ["RBY"],
  "Rcoin": ["RCN"],
  "Primulon": ["PRIMU"],
  "Dubstep": ["DUB"],
  "Spots": ["SPT"],
  "Stress": ["STS"],
  "PonziCoin": ["PONZI"],
  "Save and Gain": ["SANDG"],
  "Ixcoin": ["IXC"],
  "GameBet Coin": ["GBT"],
  "FrankyWillCoin": ["FRWC"],
  "Metal Music Coin": ["MTLMC3", "MTLMC"],
  "X2": ["X2"],
  "BitAlphaCoin": ["BAC"],
  "Synergy": ["SNRG"],
  "FlavorCoin": ["FLVR"],
  "iBank": ["IBANK"],
  "AvatarCoin": ["AV"],
  "Shorty": ["SHORTY"],
  "SproutsExtreme": ["SPEX"],
  "SongCoin": ["SONG"],
  "WMCoin": ["WMC"],
  "Orlycoin": ["ORLY"],
  "BeaverCoin": ["BVC"],
  "GuccioneCoin": ["GCC"],
  "LAthaan": ["LTH"],
  "MoneyCoin": ["MONEY"],
  "PIECoin": ["PIE"],
  "CyberCoin": ["CC"],
  "Sling": ["SLING"],
  "CBD Crystals": ["CBD"],
  "KashhCoin": ["KASHH"],
  "Electroneum": ["ETN"],
  "ZClassic": ["ZCL"],
  "LUXCoin": ["LUX"],
  "GoByte": ["GBX"],
  "WINCOIN": ["WC"],
  "CryptopiaFeeShares": ["CEFS"],
  "GrandCoin": ["GDC"],
  "Numus": ["NMS"],
  "Cappasity": ["CAPP"],
  "Pirl": ["PIRL"],
  "CrowdCoin": ["CRC"],
  "Divi": ["DIVX"],
  "Phore": ["PHR"],
  "SagaCoin": ["SAGA"],
  "Bulwark": ["BWK"],
  "HomeBlockCoin": ["HBC"],
  "Mintcoin": ["MINT"],
  "Skycoin": ["SKY"],
  "BlockCAT": ["BKCAT"],
  "StrikeBitClub": ["SBC"],
  "AdShares": ["ADST"],
  "Hush": ["HUSH"],
  "Pioneer Coin": ["PCOIN"],
  "Coin": ["OPC"],
  "Zoin": ["ZOI"],
  "Innova": ["INN"],
  "Flash": ["FLASH"],
  "Tokugawa": ["TOK"],
  "Denarius": ["DNR"],
  "Monkey Project": ["MONK"],
  "CampusCoin": ["CMPCO"],
  "ChainCoin": ["CHC"],
  "LeviarCoin": ["XLC"],
  "ProCurrency": ["PROC"],
  "Solarflarecoin": ["SFC"],
  "MyWish": ["WISH"],
  "Social Send": ["SEND"],
  "Unobtanium": ["UNO"],
  "Monoeci": ["XMCC"],
  "ZenCash": ["ZEN"],
  "Interstellar Holdings": ["HOLD"],
  "ToaCoin": ["TOA"],
  "Unitus": ["UIS"],
  "VIVO": ["VIVO"],
  "Photon": ["PHO"],
  "WeAreSatoshi": ["WSX"],
  "Bitdeal": ["BDL"],
  "Dotcoin": ["DOT"],
  "Pascal Lite": ["PASL"],
  "Nexus": ["NXS"],
  "MAZA": ["MZC"],
  "Bonpay": ["BON", "BONPAY"],
  "Zero": ["ZER"],
  "Einsteinium": ["EMC2"],
  "Musicoin": ["MUSIC"],
  "Skeincoin": ["SKC"],
  "DCORP": ["DRP"],
  "Ubiq": ["UBQ"],
  "Ellaism": ["ELLA"],
  "Harvest Masternode Coin": ["HC"],
  "Linx": ["LINX"],
  "CoinonatX": ["XCXT"],
  "AsiaCoin": ["AC"],
  "Upfiring": ["UFR"],
  "TrezarCoin": ["TZC"],
  "OKCash": ["OK"],
  "Embers": ["MBRS"],
  "Bitcloud": ["BTDX"],
  "Growers International": ["GRWI"],
  "DigitalPrice": ["DP"],
  "Copico": ["XCPO"],
  "Primecoin": ["XPM"],
  "Factom": ["FCT"],
  "Steneum Coin": ["STN"],
  "EquiTrader": ["EQT"],
  "AdCoin": ["ACC"],
  "TeslaCoin": ["TES"],
  "Wild Crypto": ["WILD"],
  "Everus": ["EVR"],
  "Ethereum Dark": ["ETHD"],
  "LBRY Credits": ["LBC"],
  "KlondikeCoin": ["KDC"],
  "Machinecoin": ["MAC"],
  "CannaCoin": ["CCN"],
  "Terracoin": ["TRC"],
  "300 Token": ["300"],
  "808Coin": ["808"],
  "Aricoin": ["ARI"],
  "Atmos": ["ATMS"],
  "OX Fina": ["OX"],
  "CORION": ["COR"],
  "Masternodecoin": ["MTNC"],
  "Condensate": ["RAIN"],
  "Guncoin": ["GUN"],
  "Creativecoin": ["CREA"],
  "BitBay": ["BAY"],
  "MagicCoin": ["MAGE"],
  "HEAT": ["HEAT"],
  "NetCoin": ["NET"],
  "Royalties": ["XRY"],
  "Myriad": ["XMY"],
  "Nyancoin": ["NYAN"],
  "Footy Cash": ["XFT"],
  "PinkCoin": ["PINK"],
  "DigiPulse": ["DGPT"],
  "Bitradio": ["BRO"],
  "NamoCoin": ["NAMO"],
  "Neutron": ["NTRN"],
  "HyperStake": ["HYP"],
  "IncaKoin": ["NKA"],
  "XGOX": ["XGOX"],
  "Musiconomi": ["MCI"],
  "PotCoin": ["POT"],
  "Zeitcoin": ["ZEIT"],
  "Feathercoin": ["FTC"],
  "Bitcoin Scrypt": ["BTCS"],
  "Recently249Memetic": ["PEPE"],
  "DaxxCoin": ["DAXX"],
  "Billionaire Token": ["XBL"],
  "DFSCoin": ["DFS"],
  "CoffeeCoin": ["CFC"],
  "NobleCoin": ["NOBL"],
  "PopularCoin": ["POP"],
  "Soma": ["SCT"],
  "CryptoForecast": ["CFT"],
  "ArtByte": ["ABY"],
  "FuelCoin": ["FUEL"],
  "Blockpool": ["BPL"],
  "Altcoin": ["ALT"],
  "Fonziecoin": ["FONZ"],
  "Digitalcoin": ["DGC"],
  "APX": ["APX"],
  "GoldCoin": ["GLD"],
  "Dinastycoin": ["DCY"],
  "Argentum": ["ARG"],
  "RussiaCoin": ["RC"],
  "Minex": ["MINEX"],
  "EverGreenCoin": ["EGC"],
  "DopeCoin": ["DOPE"],
  "Litecoin Plus": ["LCP"],
  "GAY Money": ["GAY"],
  "DROXNE": ["DRXNE"],
  "Animecoin": ["ANI"],
  "BipCoin": ["BIP"],
  "Quark": ["QRK"],
  "Gapcoin": ["GAP"],
  "Cubits": ["QBT"],
  "Bitcoin Fast": ["BCF"],
  "Phoenixcoin": ["PXC"],
  "Megacoin": ["MEC"],
  "Eryllium": ["ERY"],
  "Halcyon": ["HAL"],
  "PlexCoin": ["PLX"],
  "Cthulhu Offerings": ["OFF"],
  "Stealthcoin": ["XST"],
  "Senderon": ["SDRN"],
  "Kronecoin": ["KRONE"],
  "SoonCoin": ["SOON"],
  "RedCoin": ["RED"],
  "BitcoinDark": ["BTCD"],
  "Pesetacoin": ["PTC"],
  "BitCoal": ["COAL"],
  "Renos": ["RNS"],
  "Etheriya": ["RIYA"],
  "Triangles": ["TRI"],
  "Money": [""],
  "CacheCoin": ["CACH"],
  "SixEleven": ["611"],
  "Blakecoin": ["BLC"],
  "BlazeCoin": ["BLZ"],
  "Canada eCoin": ["CDN"],
  "C-Bit": ["XCT"],
  "WorldCoin": ["WDC"],
  "SHACoin": ["SHA"],
  "GCN Coin": ["GCN"],
  "Sakuracoin": ["SKR"],
  "BnrtxCoin": ["BNX"],
  "FlutterCoin": ["FLT"],
  "Alphabit": ["ABC"],
  "Prototanium": ["PR"],
  "Donationcoin": ["DON"],
  "Gold Pressed Latinum": ["GPL"],
  "Tigercoin": ["TGC"],
  "Coin(O)": ["CNO"],
  "TopCoin": ["TOP"],
  "Magnetcoin": ["MAGN"],
  "Bitcoin Plus": ["XBC"],
  "StarCredits": ["STRC"],
  "Bitgem": ["BTG"],
  "GAIA": ["GAIA"],
  "Marijuanacoin": ["MAR"],
  "RevolverCoin": ["XRE"],
  "Catcoin": ["CAT"],
  "ChanCoin": ["CHAN"],
  "SecureCoin": ["SRC"],
  "Piggycoin": ["PIGGY"],
  "CompuCoin": ["CPN"],
  "ZSEcoin": ["ZSE"],
  "AurumCoin": ["AU"],
  "BumbaCoin": ["BUMBA"],
  "LeafCoin": ["LEAF"],
  "Elacoin": ["ELC"],
  "$429": ["UR"],
  "I0Coin": ["I0C"],
  "e-Gulden": ["EFL"],
  "Darsek": ["KED"],
  "Marscoin": ["MARS"],
  "QubitCoin": ["Q2C"],
  "Coimatic 3.0": ["CTIC3"],
  "Bitcedi": ["BXC"],
  "Flaxscript": ["FLAX"],
  "HODL Bucks": ["HDLB"],
  "BunnyCoin": ["BUN"],
  "HoboNickels": ["HBN"],
  "Truckcoin": ["TRK"],
  "GeertCoin": ["GEERT"],
  "UniCoin": ["UNIC"],
  "Qwark": ["QWARK"],
  "Quatloo": ["QTL"],
  "Orbitcoin": ["ORB"],
  "Compcoin": ["CMP"],
  "Sterlingcoin": ["SLG"],
  "Emerald Crypto": ["EMD"],
  "8Bit": ["8BIT"],
  "IrishCoin": ["IRL"],
  "UltraCoin": ["UTC"],
  "SOILcoin": ["SOIL"],
  "Granite": ["GRN"],
  "Philosopher Stones": ["PHS"],
  "KekCoin": ["KEK"],
  "LiteBar": ["LTB"],
  "GoldReserve": ["XGR"],
  "SJWCoin": ["SJW"],
  "Byteball Bytes": ["GBYTE"],
  "Virta Unique Coin": ["VUC"],
  "Safe Exchange Coin": ["SAFEX"],
  "CryptCoin": ["CRYPT"],
  "Kayicoin": ["KAYI"],
  "Tattoocoin (Standard Edition)": ["TSE"],
  "Bismuth": ["BIS"],
  "Russian Miner Coin": ["RMC"],
  "Cobinhood": ["COB"],
  "BitDegree": ["BDG"],
  "**$79$1.120.01%": ["ZRX"],
  "Primalbase Token": ["PBT"],
  "TIES Network": ["TIE"],
  "Kolion": ["KOLION"],
  "Waves Community Token": ["WCT"],
  "MSD": ["MSD"],
  "Miners' Reward Token": ["MRT"],
  "Tracto": ["TRCT"],
  "Bowhead": ["AHT"],
  "BLOCKv": ["VEE"],
  "Starta": ["STA"],
  "EOT Token": ["EOT"],
  "ANRYZE": ["RYZ"],
  "Credo": ["CREDO"],
  "Mercury": ["MER"],
  "Oceanlab": ["OCL"],
  "Ripto Bux": ["RBX"],
  "Bankcoin": ["B@"],
  "WavesGo": ["WGO"],
  "FoldingCoin": ["FLDC"],
  "Omni": ["OMNI"],
  "Pascal Coin": ["PASC"],
  "NeosCoin": ["NEOS"],
  "Riecoin": ["RIC"],
  "Bela": ["BELA"],
  "GridCoin": ["GRC"],
  "FlorinCoin": ["FLO"],
  "Radium": ["RADS"],
  "Bitmark": ["BTM"],
  "Vcash": ["XVC"],
  "HunterCoin": ["HUC"],
  "Experience Points": ["XP"],
  "POLY AI": ["AI"],
  "BitSoar": ["BSR"],
  "Monero Gold": ["XMRG"],
  "ECC": ["ECC"],
  "LendConnect": ["LCT"],
  "StrongHands": ["SHND"],
  "SHIELD": ["XSH"],
  "Tristar Coin": ["TSTR"],
  "Magnet": ["MAG"],
  "Swisscoin": ["SIC"],
  "DavorCoin": ["DAV"],
  "Sprouts": ["SPRTS"],
  "B3Coin": ["KB3"],
  "FLiK": ["FLIK"],
  "CybCSec": ["XCS"],
  "Desire": ["DSR"],
  "Global Tour Coin": ["GTC"],
  "DigiCube": ["CUBE"],
  "Mooncoin": ["MOON"],
  "Vsync": ["VSX"],
  "BLUE": ["BLUE"],
  "Ethereum Gold": ["ETG"],
  "LevoPlus": ["LVPS"],
  "Sugar Exchange": ["SGR"],
  "LiteCoin Gold": ["LTG"],
  "UFO Coin": ["UFO"],
  "Equal": ["EQL"],
  "NEO GOLD": ["NEOG"],
  "Pure": ["PURE"],
  "Roofs": ["ROOFS"],
  "Playkey": ["PKT"],
  "Pabyosi Coin (Special)": ["PCS"],
  "BitSerial": ["BTE"],
  "FedoraCoin": ["TIPS"],
  "Safe Trade Coin": ["XSTC"],
  "Cyder": ["CYDER"],
  "Digital Money Bits": ["DMB"],
  "T-coin": ["TCOIN"],
  "Runners": ["RUNNERS"],
  "Zlancer": ["ZCG"],
  "BritCoin": ["BRIT"],
  "ELTCOIN": ["ELT"],
  "GlobalToken": ["GLT"],
  "LoMoCoin": ["LMC"],
  "ZoZoCoin": ["ZZC"],
  "Ebittree Coin": ["EBT"],
  "PeepCoin": ["PCN"],
  "ExclusiveCoin": ["EXCL"],
  "Coupecoin": ["COUPE"],
  "HOdlcoin": ["HODL"],
  "StarCash Network": ["STARS"],
  "BlakeStar": ["BLAS"],
  "Scorecoin": ["SCORE"],
  "Ammo Reloaded": ["AMMO"],
  "KiloCoin": ["KLC"],
  "Jin Coin": ["JIN"],
  "Jetcoin": ["JET"],
  "SafeCoin": ["SFE"],
  "Honey": ["HONEY"],
  "India Coin": ["INDIA"],
  "Topaz Coin": ["TOPAZ"],
  "Birds": ["BIRDS"],
  "Wowcoin": ["WOW"],
  "BROTHER": ["BRAT"],
  "CaliphCoin": ["CALC"],
  "iDice": ["ICE"],
  "Dutch Coin": ["DUTCH"],
  "Neuro": ["NRO"],
  "bitqy": ["BQ"],
  "Impact": ["IMX"],
  "GoldMaxCoin": ["GMX"],
  "Bitbase": ["BTBc"],
  "Protean": ["PRN"],
  "GlassCoin": ["GLS"],
  "Magnum": ["MGM"],
  "Akuya Coin": ["AKY"],
  "Goodomy": ["GOOD"],
  "Golfcoin": ["GOLF"],
  "Digital Rupees": ["DRS"],
  "Remicoin": ["RMC"],
  "High Gain": ["HIGH"],
  "Elysium": ["ELS"],
  "Natcoin": ["NTC"],
  "CHIPS": ["CHIPS"],
  "Huncoin": ["HNC"],
  "TurboCoin": ["TURBO"],
  "Bitcoin Planet": ["BTPL"],
  "Regacoin": ["REGA"],
  "FAPcoin": ["FAP"],
  "Bolenum": ["BLN"],
  "BOAT": ["BOAT"],
  "Cheapcoin": ["CHEAP"],
  "FairCoin": ["FAIR"],
  "MonetaryUnit": ["MUE"],
  "XTD Coin": ["XTD"],
  "Credence Coin": ["CRDNC"],
  "BetaCoin": ["BET"],
  "PlayerCoin": ["PLACO"],
  "Link Platform": ["LNK"],
  "FuturXe": ["FXE"],
  "Peacecoin": ["PEC"],
  "Prospectors Gold": ["PGL"],
  "Torcoin": ["TOR"],
  "Ulatech": ["ULA"],
  "NumusCash": ["NUMUS"],
  "AnarchistsPrime": ["ACP"],
  "HealthyWormCoin": ["WORM"],
  "ZetaMicron": ["ZMC"],
  "PoSToken": ["POS"],
  "Slevin": ["SLEVIN"],
  "Bastonet": ["BSN"],
  "MarteXcoin": ["MXT"],
  "Antimatter": ["ANTX"],
  "PinkDog": ["PDG"],
  "Aseancoin": ["ASN"],
  "Tattoocoin (Limited Edition)": ["TLE"],
  "REX": ["REX"],
  "VirtualCoin": ["VC"],
  "NuBits": ["NBT", "USNBT"],
  "ION": ["ION"],
  "Sphere": ["SPHR"],
  "Numeraire": ["NMR"],
  "adToken": ["ADT"],
  "Blocknet": ["BLOCK"],
  "Agoras Tokens": ["AGRS"],
  "Dynamic": ["DYN"],
  "Particl": ["PART"],
  "UnbreakableCoin": ["UNB"],
  "Sequence": ["SEQ"],
  "Elastic": ["XEL"],
  "Internet of People": ["IOP"],
  "Circuits of Value": ["COVAL"],
  "eBoost": ["EBST"],
  "WhiteCoin": ["XWC"],
  "I/O": ["IOC"],
  "$51,579$0.4854200.02%Recently182Memetic": ["MEME"],
  "Databits": ["DTB"],
  "Bytecent": ["BYC"],
  "Kore": ["KORE"],
  "vTorrent": ["VTR"],
  "EuropeCoin": ["ERC"],
  "Project Decorum": ["PDC"],
  "Legends Room": ["LGD"],
  "GIVE": ["2GIVE"],
  "Tokes": ["TKS"],
  "Energycoin": ["ENRG"],
  "Breakout Stake": ["BRX"],
  "Breakout": ["BRK"],
  "Blitzcash": ["BLITZ"],
  "Gambit": ["GAM"],
  "TrustPlus": ["TRUST"],
  "HTMLCOIN": ["HTML"],
  "Trollcoin": ["TROLL"],
  "Virtacoinplus": ["XVP"],
  "OFCOIN": ["OF"],
  "True Chain": ["TRUE"],
  "FairGame": ["FAIR"],
  "Delphy": ["DPY"],
  "ugChain": ["UGC"],
  "LightChain": ["LIGHT"],
  "Kcash": ["KCASH"],
  "Molecular Future": ["MOF"],
  "RealChain": ["RCT"],
  "StarChain": ["STC"],
  "Acute Angle Cloud": ["AAC"],
  "Health Mutual Society": ["HMC"],
  "Hydro Protocol": ["HOT"],
  "SelfSell": ["SSC"],
  "Primas": ["PST"],
  "Read": ["READ"],
  "Content and AD Network": ["CAN"],
  "Ace": ["ACE"],
  "OneRoot Network": ["RNT"],
  "RefToken": ["REF"],
  "Measurable Data Token": ["MDT"],
  "TokenClub": ["TCT"],
  "Viuly": ["VIU"],
  "Leverj": ["LEV"],
  "BT2": ["BT2"],
  "Maggie": ["MAG"],
  "IPChain": ["IPC"],
  "onG.social": ["ONG"],
  "Vezt": ["VZT"],
  "Gatcoin": ["GAT"],
  "FidentiaX": ["FDX"],
  "$0$0.9627880.00%Recently": ["STORJ"],
  "MktCoin": ["MLM"],
  "Polis": ["POLIS"],
  "Qbic": ["QBIC"],
  "Phantomx": ["PNX"],
  "BiblePay": ["BBP"],
  "JavaScript Token": ["JS"],
  "NuShares": ["NSR"],
  "Manna": ["MANNA"],
  "eGold": ["EGOLD"]
}